### ISSUE TITLE
Too much syncing time

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#103]
Yes, now I must mention that it depends of 2 different things: the server and the client. 
Yes, maybe Vinilox could be a slow server, but in the other hand, on other clients like Mustard, MustarMod or Twidere it's not a big problem and is not appreciated, the syncing is very fast.
I thought about the double accounts feature, but it's still too much time.

**Comment by yvolk** [comment]
Closing as too broad. Let's measure and optimize concrete critical parts of the application
