### ISSUE TITLE
Client information of a tweet/message/whatever: why have to tap the message to see?

### ISSUE THREAD

**Issue by xuhdev** [andstatus/andstatus#143]
On the timeline, for a message, there is an itatic line at the bottom of it indicating the time, such as "5 minutes ago", "two hours ago". If one taps on the message, this line becomes "n minutes ago from some_client". I don't see the reason why the client information cannot be available on the timeline. Maybe the timeline can be more informative?

**Comment by yvolk** [comment]
Implemented in v.26
