### ISSUE TITLE
Unsynchronized messages - two problems

### ISSUE THREAD

**Issue by kai11** [andstatus/andstatus#149]
I'm using GNU social - one account so far.
1) When my phone don't have connection and I'm posting message, it will not be displayed in UI after I clicked > button. Maybe it make sense show it in timeline with sync symbol instead of favorite star?
2) Is it possible to post "offline" messages with time when it was written? Right now it will have time of synchronization.

**Comment by yvolk** [comment]
"Commands in the Queue" view was greatly improved since the issue was created. 
E.g. currently you can "Share" full text of a unsent post from this view...
