### ISSUE TITLE
Feature: Adding and reading titles of pump.io notes.

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#150]
A lot of pump.io messages use titles and this is more information that we are not seeing here. It's there any possibility to improve it?

**Comment by jankusanagi** [comment]
This would be **REALLY** appreciated.

**Comment by iarenaza** [comment]
I would like to second this feature request. Using titles in Pump.io status messages is quite common, and sometimes the title conveys even more context for the status message that the message itself.

**Comment by Sothot** [comment]
The way pump.io network activities follow-up works and references/comments to notes makes more easy with the use of titles. It's not the same "someone has posted a comment to a note" that "someone has posted a comment to My cat likes drink water from tap."

**Comment by yvolk** [comment]
Titles are shown and can be posted since v.38. (May 2018)
