### ISSUE TITLE
Cursor jumping to start

### ISSUE THREAD

**Issue by vinzv** [andstatus/andstatus#152]
When I post a reply and switch between keyboard layers, the cursor jumps to the beginning of the line before the username to mention. Happens when I reply to someone and want to type in uppercase or to start with a semicolon.

**Comment by marjoleink** [comment]
I found this: [Put cursor at specific position in EditText component in Android](http://thedevelopersinfo.com/2009/11/15/put-cursor-at-specific-position-in-edittext-component-in-android/) - maybe it helps :-)

**Comment by yvolk** [comment]
Implemented in v.22
