### ISSUE TITLE
Drafts or confirmation 

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#153]
In my opinion, a drafts option would be great, or, at least, a confirmation ti exit of the texting mode.

E.i. We are writing, and we push by mistake the undone/back key. So we close the app or, the conversation view. But we miss the written text. It would be great if we add a draft option in the main menu or a exit confirmation (which I think it's the best choice).
In both of these cases we're written something, so, if we push the new message button by mistake and we don't write anything this isn't necessary.

**Comment by yvolk** [comment]
I believe fixing #194 solved this problem also: currently not posted "draft" is kept even after device reboot...
