### ISSUE TITLE
Feature: Show some info in notification

### ISSUE THREAD

**Issue by vinzv** [andstatus/andstatus#158]
Maybe the person who replied/mentioned me plus the first ~50 chars of what he wrote would be good.

(Low priority though, as I think other things are more important at the moment.)

**Comment by yvolk** [comment]
On notifications in Android N https://android-developers.blogspot.ru/2016/06/notifications-in-android-n.html

**Comment by yvolk** [comment]
Interesting observation: Some people may use the application mainly to get notifications, and they actually communicate with each other  ("catch up") using PC.
This makes "Notifications" part of AndStatus a separate application with its own features. Or rather "main" AndStatus app becomes just "an opened notification". So we need to think about some more focused (filtered) Notifications timeline than filtered mainly by account only?! E.g. opening a Conversation view (specially marking what's new). 
The "Conversation" may actually be interaction of users using @user mentioning, not by replying to previous message?!

**Comment by yvolk** [comment]
In v.36 in addition to a number of new events (activities/messages), notifications now show an Account (in a case a notification is for one account only) and time, when the last event occurred.
![screenshot_1514274527](https://user-images.githubusercontent.com/207716/34354478-8db9c58a-ea3f-11e7-9778-f376531bfe66.png)
