### ISSUE TITLE
Feature: Public / private posting

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#166]
### See #167 
One of the good points of Puma it's the option to select with who share the posts, this is another change to show that **AndStatus is the best Android client for Pump.io**.

Public / Private posting would show a merge list with:
- Public
- Private (Message)

The rest of the options would open a new merge menu to select: All of them / Select one or several users
- Followers
- Following
- Rest of the lists/groups/whatever (it would depend of the account used, in Pump.io is not ready tu use yet as I know)

**Comment by aroquen** [comment]
Just adding my thoughts here. At least for GNU social, I think it should be possible to send a message to
* Everyone (-> public)
* People at local instance
* Groups

And for groups, it should be possible to restrict the scope to private. This is important for me, as I want to keep some groups private. These are the options available via the GNU social web interface (community site, stock version) and it would be nice to be consistent with that IMHO.

**Comment by yvolk** [comment]
The same discussion on explicitly creating Public / Private posts and seeing easily which is which is here: #181 
Closing this as a duplicate
