### ISSUE TITLE
My view of AndStatus in the future

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#167]
What do you think? I've totally changed the way of posting (and replying) and added:
- Markdown toolbar (this should be explained in the 'User Manual') (#165) [ Pump.io and GNU social (and Reddit if it's added: #146) ]
- Title (See #150) [ Pump.io (and Reddit) ] 
- Public / Private posting (See #166) [ Pump.io, GNU social and Twitter (and Reddit) ]

![Loading picture](https://cdn.mediacru.sh/sUGMfTdgITOg.png)

↓↓↓**EDIT:** TEXT BELOW IT'S NOT NECESSARY IF HIDE BUTTON JUST HIDE THE SCREEN WITHOUT DELETING THE REPLY. ↓↓↓

An option to see the post we are replying too would be a nice feature too if we want to copy a part of the text to make a quote or just follow the test to reply in a more organized way. Maybe it could be a lateral panel of the Timeline (like Conversations) that way:
![](https://cdn.mediacru.sh/zoA6lGXfeE9u.png)

**Comment by moshpirit** [comment]
The picture was deleted by GitHub.

![Loading picture...](https://cloud.githubusercontent.com/assets/7888062/9341178/9f8e5fba-45f4-11e5-8a55-41658b46dbc5.png)

**Comment by yvolk** [comment]
@moshpirit Thank you for these inspirational pictures, they helped me compare what we have now with what we could have... 
As a lot of changes were done since the issue creation. I'm closing this issue as it's partially outdated now and _too_ wide to be implemented. And I hope you will continue contributing to the project.

**Comment by moshpirit** [comment]
It's a pleasure to contribute to this project and I love how is evolving, you're a great developer and I hope creating more issues :)

Thanks a lot for all your work and letting me to be part of it!!
