### ISSUE TITLE
RT/Reposts aren't showed like that in the Timeline

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#168]
It's just a minor issue. Would be nice to have a "RT by @user X minutes ago" instead of just "X minutes ago". The same with GNU social and Pump.io, it would be nice to have a "Reposted by @user X minutes ago", just like now does the "X minutes ago in reply to @user".

**Comment by yvolk** [comment]
I investigated possibility to add "retweeted by ..." to a Timeline: it requires redoing a way a message list is built, because there may be more than one "retweeter".
This will be done with #192

**Comment by quite** [comment]
Great, it's coming.

I just found andstatus and it seems excellent! Just missing this indication of who RTed this and that in the timeline.

**Comment by yvolk** [comment]
@quite If you find some message really interesting,  click on it and:
- you can see Retweeters;
- client application used;
- conversation context of the message;
- links become clickable so you can follow them.

Is it really so important to see Retweeters immediately in a Timeline?

**Comment by quite** [comment]
Maybe it isn't! Perhaps it's just a habit, that I may shake. Perhaps the
original author ought to be more important, when you think about it.

**Comment by yvolk** [comment]
@quite I understand that Retweet by a known user is like "Recommended by" the User. And this is why it is important for us.

**Comment by moshpirit** [comment]
why not just a symbol under the avatar or before the note to let us know that this note was repeated? or maybe the note could appear using a italic font

**Comment by yvolk** [comment]
@moshpirit Ok, will keep this in mind also.

**Comment by yvolk** [comment]
Implemented, will be released in v.26
![scr-timeline-light-buttons-rebloggers-v26](https://cloud.githubusercontent.com/assets/207716/14586004/5a915644-0492-11e6-8ba1-03fdc5952338.png)
