### ISSUE TITLE
DESIGN: blue theme and new toolbar

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#170]
I've been thinking in adding a new theme, but I don't know how to do it, I only know that the file of the themes is andstatus/andstatus/res/values/themes.xml. I'd like something like this one below and the same with the light.
Anyway, I've been thinking that adding a toolbar like this one could be very useful and I like how it looks like. What do you think?

![Loading...](https://cdn.mediacru.sh/lk5JONdDj1JL.png)

**Comment by yvolk** [comment]
As part of Material Design adoption #202 we added an option to choose between several Action bar colors and several background colors. New colors may be added easily...

Pictures, attached to the first post, are unavailable now, so I'm closing this issue. 
Please create a new one, based on currently available features.
