### ISSUE TITLE
Reply to All - Option to include all conversation participants into a reply

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#185]
Now it just replies the user who wrote the message replied, no matters if there are 10 users there.
I propose to include all these users (and if you want, name just the only one who wrote the message to reply).

**Comment by marjoleink** [comment]
I'm with Morphtown on mentioning users in the text as @**user**. Not only does it make dents more readable in clients like Identicurse and XMPP, this also applies to long conversations, especially if not shown hierarchically. And *any* non-private message can be shown outside of the context of a specific app, e.g. in search results of a search engine, in quotes in a blog, etc. If the adressees (reply-to *and* mentions) are missing, the message may make no sense any more.
IMO the automatic linkage is for internal use only but only private messages are truly "internal" to teh system.

**Comment by moshpirit** [comment]
Please, add "Reply to all" in Crowdin

**Comment by yvolk** [comment]
@moshpirit done

**Comment by moshpirit** [comment]
Translated!
