### ISSUE TITLE
AndStatus sometimes doesn't load some replies (Twitter and Pump.io)

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#186]
1. Twitter doesn't load replies except if they are made by people we follow. [[E.g.](https://twitter.com/elbaronrojo/status/540607585033146370), [pic](https://cdn.mediacru.sh/AuWzpG92xzN_.png)]
2. Pump.io sometimes doesn't load some replies to some notes. [[E.g.](https://cdn.mediacru.sh/z0IQJO0hnkEu.png)] (it's a reshare, so the post it's not public, but if you see it, victorhck has asked "logo de Debian??" and EVAnaRkISTO has mentioned him.

**Comment by yvolk** [comment]
In order to move solution of this potential bug forward I propose this way:
1. Please Set logging to VERBOSE
2. Turn on "Log Network level messages"
3. Turn on "Log everything to file".
This way each time you are in doubt why any particular message (which you see e.g. via Web UI) was lost in AndStatus, you will have enough information at hands to find out, where it was lost (each message has ID and text easily searchable in logs).
?!

**Comment by moshpirit** [comment]
I have these options enabled since they were available, so I think you could find this information in the last email I sent you

**Comment by yvolk** [comment]
Email with logs is not enough :-) 
1. Which exactly reply was not loaded?  - Please post me a link to it,  not a screenshot. And will search for it in the logs...
2. When exactly did you send me that email?

**Comment by moshpirit** [comment]
I think they're not loaded because the messages are not downloaded until we press "refresh".
About pump, I think it's a social network bug :\

On January 18th to andstatus@gmail.com 

I'm closing this issue and if I find this error again, I'll post the link.

**Comment by yvolk** [comment]
Screenshots are not ok, especially without logs. ..

**Comment by moshpirit** [comment]
Ok, I've said nothing, please, reopen the issue again, I can't see [this tweet replies](https://twitter.com/Barbijaputa/status/557842539034972160) on AS, I can't even download newer tweets neither (I've refreshed Barbijaputa's tweets TL like 10 times and still can't see them.

Should I include a screenshot?

**Comment by yvolk** [comment]
No screenshots now I need all logs (txt and json), starting from January 20

**Comment by moshpirit** [comment]
I think so, my configurations about storing are:
- 5000 messages
- A month

There's no txt files in backup folder, just json, 1 xml, 1 db and one sqlite. What should I send you?

**Comment by yvolk** [comment]
I mean "logs" folder. It has txt and json files.
