### ISSUE TITLE
Multiple attachments - Attach several pictures 

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#189]
No hurry, it's just another feature more.
Gnu social and Twitter allows attachment of several pictures, it would be great to implement it on AS.
Maybe when you add the Qvitter API, it could be added easier. I don't know.
Thanks for your awesome work, now I can enjoy of these 2 lines setting titles and the VERBOSE debugging without any id :)

**Comment by yvolk** [comment]
@moshpirit You're not the only one asking for Multiple pictures support https://mobile.twitter.com/AndStatus1/status/591851651419525121

**Comment by moshpirit** [comment]
Good! :+1:

**Comment by yvolk** [comment]
Multiple attachments in #AndStatus implemented in v.52.00, currently in Beta #456
![scr-multiple-attachments](https://user-images.githubusercontent.com/207716/68538775-d3ae3100-038a-11ea-943c-ad3347cab272.png)

**Comment by yvolk** [comment]
The same works for #ActivityPub #C2S also, see https://github.com/andstatus/andstatus/issues/499#issuecomment-552206437

**Comment by yvolk** [comment]
The same works for Twitter also since v.52.02
