### ISSUE TITLE
Feature: open and view images in full resolution

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#191]
just like all the features: there's no hurry! :-)

I've thought that it would be great to have an option to see the image in full resolution, allowing to open the picture, amplify it and move across it. I say it because sometimes, I see in Pump.io some XKCD comics and I can't read them on AS.

**Comment by moshpirit** [comment]
The option is gone of the menu, so there's no "View Image anymore".

It should be great if we could see the picture just pushing it, like a "click" on the picture.

**Comment by yvolk** [comment]
This definitely works in the latest commit.
Please test.

**Comment by moshpirit** [comment]
Yes, it is, thanks, (I don't know why I had this problem, maybe was an AIDE bug or something)

**Comment by yvolk** [comment]
@moshpirit Recently I did a lot of refactoring/redoing in AndStatus, so something may be broken. Currently I'm stabilizing the code in order to prepare new minor release with fixes...
