### ISSUE TITLE
Silly desing issue: send icon is too big

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#196]
It's just that, in my phone, send icon it's too big, I think it should use another one a little smaller.

![screenshot_2014-12-14-18-48-10](https://cloud.githubusercontent.com/assets/7888062/5428379/1247df22-83c2-11e4-9ddd-2ec2e91f6767.png)

Maybe AS could use one like this: ![](https://raw.githubusercontent.com/siacs/Conversations/development/src/main/res/drawable-xxhdpi/ic_action_send_now_offline.png)

**Comment by moshpirit** [comment]
My idea was eliminate the maximum space possible around the arrow, but it's better than before

**Comment by yvolk** [comment]
Buttons should have a lower size limit large enough to tap them...
