### ISSUE TITLE
If we're writing, let us copy other notes 

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#197]
Yo copy a some text it's basic, something that AndStatus hasn't implemented because the way to do it's pushing the note and selecting the he part of text we want to copy. But AS use this function to open a merge menu with a lot of possibilities and include "copy text" could be too much (indeed, I think it should open the picture view just touching the picture itself, without opening any menu, anyway, when AS included a profile view, some options could be disabled in this menu: like "follow/unfollow" and "send private message").  
That's why I'm thinking it could be included when we're writing: if the writer tab is open and we hold on a note, then, AS would select the part of the text we want to copy, but if the writer is closed, AS would open the current merge menu.

**Comment by yvolk** [comment]
I see these features here:
1. Add new context menu item: "Copy text to clipboard". I really don't think selection of a part of the message is an easy thing - unneeded text may be deleted after pasting...
Pasting text from Android clipboard is already available.
2. Different context menus depending Message Editor state (is it visible or not). The idea is to add special new items when the Editor is visible.

**Comment by yvolk** [comment]
Android docs on Clipboard usage: http://developer.android.com/guide/topics/text/copy-paste.html
We may have these copy options:
1. "Copy text to clipboard"
2. "Copy @author to clipboard" - for easy mentioning.
3. Maybe even "Copy image to clipboard"... Is this really needed?
