### ISSUE TITLE
Sharing a note with '&' appears like '&amp;'

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#199]
When we share a note with the symbol '&', it appears in the writer space like '&amp;'.

E.g.
Original: Andstatus allow Pump.io, Gnu social & twitter accounts.
If I press "share" it appears like:
Andstatus allow Pump.io, Gnu social &amp; twitter accounts.

**Comment by yvolk** [comment]
I couldn't reproduce this now :-(
E.g. I see this message in LoadAverage "@borabjra Привет & welcome :-)": https://loadaverage.org/notice/6703510
Sharing it both with AndStatus or with other apps gives the same text, as expected.

Please provide an easy to follow steps to reproduce the bug!

**Comment by yvolk** [comment]
Is this bug really about Twitter only? See #219

**Comment by yvolk** [comment]
No, posting to Twitter is Ok...

**Comment by yvolk** [comment]
@moshpirit Please give me exact text to post and exact server isnance

**Comment by yvolk** [comment]
Closed as couldn't reproduce
