### ISSUE TITLE
Material design

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#202]
AndStatus needs the "material design" http://www.google.com/design/spec/material-design/introduction.html
And we also need to stay compatible with older devices. The guide seems to give recipes for this: https://developer.android.com/training/material/compatibility.html
More on this: https://www.google.com/search?q=material+design+for+older+android

**Comment by yvolk** [comment]
I just got Lollipop firmware on my Sony XPeria and selected "Device default" theme in AndStatus.
Isn't it _almost_ Material?
![scr-lollipop-orange-black](https://cloud.githubusercontent.com/assets/207716/7190123/86d826be-e48c-11e4-8ec9-a8a5e77409e3.png)

**Comment by deavmi** [comment]
The ting is, we should all just be using stock android or A rom. The adding of more code to get the lollipop themeing is not nice, as it is more useless code. Screw OEMs.

**Comment by yvolk** [comment]
Please explain your thoughts. 
Do you agree that above screenshot looks as "Close to Material Design" but think that this is not for your case, because these nice colors are because of Sony's (OEM's) customizations of the stock ROM?
Did you try to apply custom themes to your device? As I see, something similar is for CyanogenMod 12 also: http://www.phonearena.com/news/Customize-that-Android-5.0-Lollipop-Here-are-some-gorgeous-themes-for-CyanogenMod-12_id65345
?!

**Comment by yvolk** [comment]
I read [here](http://www.phonearena.com/news/The-beauty-of-Android-features-of-custom-Lollipop-ROMs-that-could-have-made-stock-Android-5.0-better_id65972):

Custom theme support

Material Design is captivating, but some users are not that keen on white menu backgrounds. Even more, some might be looking forward to slightly altering the looks of the interface. While this is possible neither in Lollipop nor in any previous stock version of Android, custom ROMs that come with CyanogenMod's Theme Engine allows users to download a UI theme from the Play Store, apply it and voila, change the cosmetic looks of their UI. Simple as that. Many Android fans would have probably commended Google if Lollipop came right out of the box with similar theme support, but alas.

**Comment by yvolk** [comment]
@deavmi Did you try AndStatus with e.g. this (with custom Launcher, e.g. Nova launcher...) https://play.google.com/store/apps/details?id=com.szp.akai&hl=en

**Comment by deavmi** [comment]
Nope. I don't do not proprietary software.

Launcher3 for days.

**Comment by yvolk** [comment]
Which ROM do you use?

**Comment by deavmi** [comment]
The above is close to lollipop.

**Comment by deavmi** [comment]
I use the stock Samsung ROM. CyanogenMod does not support the Galaxy Note 4.

**Comment by yvolk** [comment]
So you don't have Lollipop on your device yet?

**Comment by deavmi** [comment]
I do. I got the OEM update.

**Comment by yvolk** [comment]
So you have Lollipop on your device, you agree that above screenshot (made on Lollipop also) is close to "Material design", but you are still asking for "Material design". 
What exactly are you currently missing? Please provide screenshots for us to understand each other better. ..

**Comment by deavmi** [comment]
Like, I hagveseen apps thyat have incorporated the code for material design into their app, so that it would even work on phones prior to Lollipo, such as ICS.

**Comment by yvolk** [comment]
I don't see much difference in how AndStatus looks now on Lollipop vs. KitKat...

**Comment by yvolk** [comment]
Interesting article on this topic: http://www.androidpolice.com/2015/04/25/androids-system-bars-and-your-interface-whether-and-how-to-theme/

**Comment by yvolk** [comment]
This  library and event its approach to theming may be used for these improvement: https://github.com/afollestad/material-dialogs

**Comment by yvolk** [comment]
The latest commit has huge step ahead in moving to Material design:
* Added "Action bar color" option, having 6 colors from [Material design color palettes](http://www.google.ru/design/spec/style/color.html). 
* Added "Background color for the Dark theme" option, having 7 dark colors, including Black color from [the List of HTML colors](http://www.computerhope.com/htmcolor.htm).

![scr-timeline-material-teal](https://cloud.githubusercontent.com/assets/207716/8635509/1e44eab6-282e-11e5-9afe-a097c1b237ea.png)

**Comment by deavmi** [comment]
Awesome. :)



-----------------------
Sent from Deavmi
Keep on hacking...

Contact Deavmi via:

Pjuu: https://pjuu.com/deavmi
GNU Social: deavmi@quitter.se
Twitter: https://twitter.com/deavmi
Main mailbox: deavmi@openmailbox.org

**Comment by yvolk** [comment]
I see that AndStatus logo could also be adjusted to the Material design pallette, see what I came to:
![screenshot_2015-07-12-23-14-13-v6](https://cloud.githubusercontent.com/assets/207716/8639791/92519a44-28ec-11e5-9755-0e0da8636e99.png)

**Comment by moshpirit** [comment]
mm I found a bug: there's no top tab in the appearance settings:
![screenshot_2015-07-12-23-43-16](https://cloud.githubusercontent.com/assets/7888062/8640216/0e88bb4a-28e0-11e5-9faf-e9f5170ca3f8.png)

**Comment by yvolk** [comment]
@moshpirit Will add this: there is a fix for this AppCompat library bug: http://stackoverflow.com/questions/17849193/how-to-add-action-bar-from-support-library-into-preferenceactivity

**Comment by deavmi** [comment]
The logo looks very sharpened around the edges of the words `AndStatus`, I think that is because it's just too low res or something idk. Maybe a higher res would be better.



-----------------------
Sent from Deavmi
Keep on hacking...

Contact Deavmi via:

Pjuu: https://pjuu.com/deavmi
GNU Social: deavmi@quitter.se
Twitter: https://twitter.com/deavmi
Main mailbox: deavmi@openmailbox.org

**Comment by yvolk** [comment]
@deavmi Yes, I agree. I'm considering some other color changes in this logo. 
I think this page should be the first page that a new User will see...

**Comment by deavmi** [comment]
Remind me please, what is the current first start page that the user sees?

Cause I think an Account Setup wizard on app first start would be great! :D

Yuri Volkov wrote:
> @deavmi Yes, I agree. I'm considering some other color changes in this logo.
> I think this page should be the first page that a new User will see...
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/andstatus/andstatus/issues/202#issuecomment-121298956
>

-- 


Your developer,
Deavmi
=================>

Twitter: https://twitter.com/deavmi
Site: https://deavmi.github.io

Code is poetry, embrace it, in an open-source way.

**Comment by yvolk** [comment]
Currently this screen with logo will be shown at a first launch (with "Get Started" button instead of "Skip" on the below screenshot). The "Get Started" button leads to the first Account creation, just like you expect.
I created another Action Bar Color (called "My Blue"), which is default now:
![screenshot_2015-07-14-22-49-09](https://cloud.githubusercontent.com/assets/207716/8683489/d34f7ada-2a7b-11e5-849f-66302eb2433f.png)

**Comment by yvolk** [comment]
Closing this issue as mostly done.
Please create more focused issues on any additions to what we already have. See e.g. #283 "Update icons for Material Design".

**Comment by deavmi** [comment]
It's beautiful :D

**Comment by yvolk** [comment]
Interesting article on future rotation animations using Google material design 
http://phandroid.com/2015/08/11/android-material-design-rotation-animation-concept/
@phandroid rocks!
