### ISSUE TITLE
[Pump.io] Private attachments are not downloaded

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#204]
Currently we're getting HTTP 403 error. It looks like no credentials are used for downloading, but public access to private images is disabled.

**Comment by moshpirit** [comment]
Maybe it's a server error, I think I remember Evan has been fixing a few things of Identi.ca and another server.

**Comment by yvolk** [comment]
I'm figuring this out. The truth is that currently no authentication is used to download images, so this should be fixed anyway...

**Comment by yvolk** [comment]
After a lot of refactoring this is fixed, please test!
I did this: successfully sent "Direct message" from one my pump.io account to another: the image is seen at both sides (i.e. by a sender and by a recipient).

**Comment by yvolk** [comment]
Note from a User, who reported this issue:
"
I successfully tested the new version. 
I am able to send and receive private/public messages with attachments from my pump.io instance.

I was running an old version of nginx and had to install some additional modules to get rid of the 411 error.
"
