### ISSUE TITLE
Cannot connect to server with SSL and self-signed certificate

### ISSUE THREAD

**Issue by aroquen** [andstatus/andstatus#208]
I am trying to connect to my self-hosted GNU social server (master branch) via https from my Samsung Note 8 (Android 4.2.2). I am using AndStatus 14.0 from f-droid. The certificate is self signed.

When I first tried to connect I got the error "Cannot verify hostname". I assume this is because the certificate is self-signed. I found an option to ignore SSL issues in "Logging and debugging" so I enabled it. Now the error is "SSL.PeerUnverifiedException: No peer certificate". Is there anything I can do to fix that and connect to the server?

Note I can connect to the server via web interface without problems.

**Comment by yvolk** [comment]
This is a common question, please search for solution here: https://github.com/andstatus/andstatus/issues?q=is%3Aissue+certificate
In particular, see step-by-step description (including installation of the certificate) here: Server hostname problem #116

**Comment by aroquen** [comment]
I had an old certificate installed on the device, which is why it didn't work. I updated it and everything works fine! Thanks for pointing me in the right direction!

**Comment by yvolk** [comment]
Another case:
No way to use self signed certificates, even choosing the "misconfigured" option.....

Solution: This is happening because the CA:TRUE flag is not enabled. This prevents android (not only AndStatus) to  use a certificate.

**Comment by markwaters** [comment]
I had to use insecure mode to connect to a new gnusocial instance that uses a SSL certificate from letsencrypt.

**Comment by yvolk** [comment]
@markwaters It's interesting, to which exactly instance did you connect? I would try to open its web site ( https://... ) in a browser on the same Android phone and look at the certificate info ( clicking on the "lock" icon in Chrome browser).

**Comment by markwaters** [comment]
Hi @yvolk , I connected to my own new instance at https://social.markwaters.eu/
I am using the same letsencrypt system for a few other websites and xmpp server without problems.
When I connected to my gnusocial instance with twidere it worked without a SSL warning , just that the app was unstable in other ways.

**Comment by yvolk** [comment]
@markwaters Your site's certificate looks OK from my device, but it doesn't mean that this is the same for your phone/device (you didn't answer my question on that...)
So you need either follow steps, described in above mentioned solutions and linked issues and reply there with your concrete findings...
or relax and live with "insecure SSL", if you don't want to spend time on that.

There could also be some Android firmware bug (I.e. bug in your phone's firmware), specific to a secure protocol, used by your site. This is cured by firmware upgrade, as usual :-)

**Comment by markwaters** [comment]
I've used the built-in browser to check the site certificate , it tells me 'this certificate is valid'.
I see the same issue on two devices , one is running Android 4.4.2 , the other runs 6.0.1
Insecure mode works fine for me.
