### ISSUE TITLE
Problem with conversation view

### ISSUE THREAD

**Issue by aroquen** [andstatus/andstatus#209]
I am using version 14.0 from f-droid on Samsung Note 8 with android 4.2.2. Notices in my home are not "threaded": they appear in chronogical order and are not grouped according to the conversation. I couldn't find an option to enable the conversation view. Is there a way to do that or is it a bug? I can provide more info if needed.

**Comment by morphtown** [comment]
Am 17.01.2015 um 16:48 schrieb aroquen:
>
> I am using version 14.0 from f-droid on Samsung Note 8 with android
> 4.2.2. Notices in my home are not "threaded": they appear in
> chronogical order and are not grouped according to the conversation. I
> couldn't find an option to enable the conversation view. Is there a
> way to do that or is it a bug? I can provide more info if needed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andstatus/andstatus/issues/209>.
>
By (short) tapping the notice its available context should extract in a
new screen.

**Comment by aroquen** [comment]
Right! It's just clicking on it. Closing this.

**Comment by yvolk** [comment]
Interesting, maybe we should add another way to see conversation of the selected message and / or amend a User's manual...

**Comment by aroquen** [comment]
Perhaps in the menu that appear after a long tap there could be an option "Open conversation" close to "Open on internet", since they are both supposed to display the same content. A thing I noticed is that clicking on a group or tag within a notice in the Home view does not do anything (you open the conversation instead) while doing it from the conversation open the tag or group in the web browser. If opening the conversation were only done via the menu, the behavior would be consistent (i.e. clicking on a link opens it in a broser). Anyway, it's just a minor thing.
