### ISSUE TITLE
Send message to group or people on server

### ISSUE THREAD

**Issue by aroquen** [andstatus/andstatus#211]
I don't know if there is already a way to do that, but right now notices can only be posted publicly. It would be nice to be able to send them to a server's users only or privately to a group (like via the GNU social web interface). I am not sure if that is feasible, anyway, it's just a feature request.

**Comment by morphtown** [comment]
Am 17.01.2015 um 17:14 schrieb aroquen:
>
> I don't know if there is already a way to do that, but right now
> notices can only be posted publicly. It would be nice to be able to
> send them to a server's users only or privately to a group (like via
> the GNU social web interface). I am not sure if that is feasible,
> anyway, it's just a feature request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andstatus/andstatus/issues/211>.
>
Direct messages to accounts on the same instance should work with
AndStatus. Note that this does not work between remote instances. But
this is a native OStatus issue.

**Comment by aroquen** [comment]
I really meant posting a notice to a group and being able to restrict the visibility to the group as in the GNU social web interface. It's essentially what was requested in #166 so I am closing this.

Concerning direct messages, the interface is not extremely intuitive. Following the help, I go to my direct messages but since I have none of them at the moment the screen is empty and I have no way to send one (at least I couldn't find a way to do that) I can from the home timeline by long pressing. Anyway, thank you for your help.

**Comment by yvolk** [comment]
AndStatus indeed doesn't have an interface to explicitly define a recipient of a Direct message. You may only send a Direct message to a User/Author of the selected message (long pressing on it).
Adding such interface (allowing e.g. type recipient username manually) should be a topic of a separate issue, I guess...
