### ISSUE TITLE
Andstatus crash while opening

### ISSUE THREAD

**Issue by esecamara** [andstatus/andstatus#215]
Hi, 
I have a Xperia Z3 (model D6603) with KK 4.4.4, i installed this morning the app but when i tried to open, it crashed. I have tried to open connected to wifi and LTE and, in both cases, i sent a report through Android.

![2015-01-19 20 51 53](https://cloud.githubusercontent.com/assets/10603731/5807637/7b79f94c-a025-11e4-85ac-501ef5a6d008.png)

**Comment by yvolk** [comment]
Thank you for the Crash Report sent to Google Play.
I fixed this bug more than two weeks ago but got only one report that time, so didn't hurry :-)
Now I see that it is quite critical,  so releasing an updated application today...

Java.lang.NullPointerException
at org.andstatus.app.TimelineActivity.prepareDrawer(TimelineActivity.java:476)
at

**Comment by esecamara** [comment]
Great! Thanks!!

**Comment by yvolk** [comment]
The fix is released in v.14.1
Please don't forget to update your review at Google Play!

**Comment by esecamara** [comment]
Done. Thanks!!
