### ISSUE TITLE
"Act as" on GNU social 

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#217]
It doesn't appear in the merge menu when we hold down a message using a several accounts of GNU social in AS.
Is is possible to improve? If we can do it using Twitter, why not with GNU social?

**Comment by yvolk** [comment]
This works if you have more than one account in one _instance_
Currently different GNU social instances in AndStatus are not related. 
See: Treat different "GNU social" systems as one "GNU social" federation #96

**Comment by moshpirit** [comment]
Ok, then, maybe changing the structure, and these two more are really related.
