### ISSUE TITLE
Improve changelog message after update

### ISSUE THREAD

**Issue by aroquen** [andstatus/andstatus#218]
Upon launching the app after updating to 14.1, one finds a changelog message. One can tap on "Learn More" or "Get Started". AndStatus assumes this is a fresh install, I don't need to "get started" if this is an update. I suggest "Launch app" instead or something like this. Actually I wonder if the changelog message is necessary at all, I'd rather have a link to it at the bottom of the app description e.g. on f-droid.

**Comment by moshpirit** [comment]
Sometimes, the User manual changes, anyway, you can just push "Start" to skip and using it, so, I don't see the problem here. The only thing I could say against the Manual is that it's not be able to translate it, that's all.

**Comment by aroquen** [comment]
I am just saying that "Get started" is confusing (at least to me)

**Comment by moshpirit** [comment]
Ok, so would you prefer something like "Skip"?

**Comment by aroquen** [comment]
Yes "Skip" would be fine.

**Comment by yvolk** [comment]
Thank you for suggestion. 
Actually this "Get started" confused me also...

**Comment by yvolk** [comment]
Will be included in v.14.3
