### ISSUE TITLE
Unable to send a message with an asterisk (*) on twitter

### ISSUE THREAD

**Issue by chibinah** [andstatus/andstatus#219]
When i try to send a message containing as asterisk with my twitter account, the message is not sent.

If I send "Test, with the asterisk * symbol" withouth the quotes, the "Commands in the queue" window displays :

>R; Tweeter "Test, with the asterisk * symbol"
>Created il y a 3 minutes
>executed:2, last:il y a deux minutes, retriesLeft:9, error:Soft,
>updateStatus, text:'Test, with the asterisk * symbol',
>Status code=UNKNOWN; soft;
>; statusCode:UNKNOWN (0); url:'https://api.twitter.com/1.1/statuses/update.json';; authenticated; posted:'{"status":"Test, with the asterisk * symbol"}';
>Caused by org.apache.http.client.HttpResponseException: Authorization Required,
>chibinah/Twitter, 

Any other message withouth the asterisk are working fine.

I reproduced this problem seven or eight time today, on my Samsung Galaxy Note II (android 4.4.2) with AndStatus 14.0 and 14.3 (after deleting all data and uninstalling version 14.0; and installing the 14.3 version from F-Droid).

It's not related with youtube/youtube video link, like I initialy thought.

**Comment by yvolk** [comment]
Yes, an asterisk "*" is really a special character in Twitter API. (And I suppose a Web client doesn't use this API)
I couldn't find any official documentation on this yet,  only this post: https://twittercommunity.com/t/asterisk/6343

**Comment by yvolk** [comment]
What do you think,  if I simply replace "*" in Twitter posts with "." (dot)
