### ISSUE TITLE
No URL link on Vinilox if the note it's not opened 

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#220]
Not a SSL issue (I've enabled it and nothing has changed) nor HTML (it's disabled in all the microblogging systems)

Screenshot: https://my.owndrive.com/public.php?service=files&t=01bb3a7835ac5e11bb1737a79648628e

As you can see, there's no problem with any other instance.

**Comment by yvolk** [comment]
If you turned HTML off than no wander that the is no "linkified" link.
In any case, Vinilox server may decide not convert some urls to links...
I don't see a bug here...

**Comment by moshpirit** [comment]
But in the Web UIs I can click these URLs

**Comment by yvolk** [comment]
Web UI is another client application, which may linkify text by its own rules. 
If you turn HTML on (in Microblogging system Editor) AndStatus shows messages the same way they are received from the server. ON sending text to be sent is "htmlified" for Pump.io...
But if you turn HTML off AndStatus cleans text from any HTML first, and then stores the message. 

For presentation in a Conversation view links are added in a case there were no links in the stored message. See ConversationViewAdapter.oneMessageToView

**Comment by moshpirit** [comment]
Ok, I'll say it to Vinilox

**Comment by moshpirit** [comment]
Ok, it was the HTML configuration, please, enable it by default :)

**Comment by yvolk** [comment]
By default, HTML is enabled for Vinilox server.

**Comment by moshpirit** [comment]
Now I can't write more than 140 chars :\
