### ISSUE TITLE
Edit message [Pump.io]

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#221]
This is a focused feature, extracted from the @moshpirit 's #165 suggestion.
Ability to edit posted messages is unique to Pump.io as it has documented "update" verb for this purpose, telling that the message's content has changed. See https://github.com/e14n/pump.io/blob/master/API.md

AndStatus correctly receives such "update" activities, but cannot send them so far.

**Comment by ArceePrime** [comment]
This one would be awesome :)

**Comment by jankusanagi** [comment]
+10000.

Updating an object on Pump is really quite easy. I imagine the problem here is the extra UI needed in AndStatus, since the other networks you support, don't have editing capabilities.

**Comment by yvolk** [comment]
Actually AndStatus _can_ edit (drafts) already. You can save a draft, edit it later. Then send...
So allowing to edit already send message is just a matter of configuration... plus additional "EditMessage" command at a network layer (we have add/delete... already...)

**Comment by yvolk** [comment]
I started implementation of the ”Edit message” feature for Pump.io, and I see that currently I don't know how to update an ”attacnment” because currently used procedure to upload an image to pump.io doesn't take any I'd as an input - it can only create new image with a new I'd.
This means that from inside AndStatus this will look like for messages with an attachment only the text part can be edited.
?!

**Comment by clacke** [comment]
I would expect that you're supposed to PUT the updated image. Did you try that?

**Comment by yvolk** [comment]
@clacke Any concrete example?
Currently what is "message with an attachment in AndStatus" is an "object" with "objectType":"image" and "content":"Text of the message". The "image" object has an "id", which is URL of the image.

Suppose my image is stored locally on a device. How do I upload it to the server so that it replaces the old version of this image and has the same "id" == URL ?

I would try "put", but this is just a json string with "put" (?) action?! There will be no image in it...

**Comment by yvolk** [comment]
And it works!
Successfully implemented editing both messages with and without attachments. A User can change both text and an attached image.
What is not allowed: adding an attachment to a message that didn't have one. Or removing an attachment. This is because messages with and without attachments are two different types of objects in Pump.io.
![image](https://cloud.githubusercontent.com/assets/207716/18807403/580539f6-824e-11e6-95f6-f7790dcda469.png)

**Comment by jankusanagi** [comment]
Excellent news! =)

However, regarding updating the image itself, I haven't experimented with that in my client yet. I don't know if the server actually supports that.

From what I see in https://1realtime.net/test425 your tests created a different post with the new picture, and didn't change the old one with the flower. Also, if you check that timeline without being logged in, you'll see that the new post's image doesn't load, because only the creator has permissions to the file.

Anyway, I'll try to add more info once I've done some testing, but really, supporting editing the title and the description of the post is more than enough for now ;)
Thank you!

**Comment by yvolk** [comment]
@jankusanagi Current version of the app doesn't upload new image on edit, if the image didn't change. 
New image is uploaded in a separate step, 
"image" object is returned by the server, confirming successful upload and giving the image's metadata, including its URLs:
'''
"image": {
    "url": "https:\/\/1realtime.net\/uploads\/test425\/2016\/9\/24\/NdrDag_thumb.jpg",
    "width": 320,
    "height": 180
  },
  "fullImage": {
    "url": "https:\/\/1realtime.net\/uploads\/test425\/2016\/9\/24\/NdrDag.jpg",
    "width": 909,
    "height": 512
  }
'''
In order to "update" existing image object, I replace above properties in it, so object with the same ID starts to point to the new uploaded images.

The question is if Pump.io server is able to find out, which uploaded image are not referenced anymore and clean them to free space. AndStatus does have such cleaning procedure: unreferenced images are deleted periodically.

v.29.02 is published to the Open Beta testing channel: https://play.google.com/apps/testing/org.andstatus.app

Actual Java code is in https://github.com/andstatus/andstatus/blob/master/app/src/main/java/org/andstatus/app/net/social/pumpio/ActivitySender.java
