### ISSUE TITLE
Following a mentioned User and How to use the content of a tweet?

### ISSUE THREAD

**Issue by loneuron** [andstatus/andstatus#224]
I would like follow users, mentioned in tweets.
But when I click on the user just the website from the gnusocial instance of this user will be open in the webbrowser. Because I left the andstatus app there can't be a possibility to follow this user.

Is there any description of the user interface concept? 
I have the impression that I didn't understood the whole concept. :-(

**Comment by yvolk** [comment]
You have many ways of using (acting upon) a message. These action are listed in the "Message context menu", which looks like the below.
In order to open this menu, please "hold down" on the message ("Long tap" on it) as User's Manual says, BTW.
The Message context menu is available in both Timeline and Conversation views. But it's a bit more convenient to use it in a timeline view, because all links of the message are not active in a Timeline view...
![scr-contextmenu-v13](https://cloud.githubusercontent.com/assets/207716/6014943/9cfa4bf8-ab7e-11e4-8116-af6f9b87ec19.png)

**Comment by loneuron** [comment]
I had known the "long tap" methode, but this dosn't help to access the mention userid.
I can just follow the sender of the tweet, but this isn't enough. I need frequently to follow or copy a mention userid.

**Comment by yvolk** [comment]
I'm using "Share" context menu item to copy/cite any part of the message, including its URL (!). 
Usually I "Share" to some "Notepad", e.g. to Open Source "Omni Notes" or to Google Keep, which allows me to have the full tweet/message information on my PC via automatic sync.
Having everything in a "Notepad" app, I can easily extract/edit anything without a need to make AndStatus another subpar Notepad application...
Please note that you can "Share" to AndStatus itself, selecting different AndStatus account. Thus you may easily cross-post/cite messages between microblogging systems.

**Comment by marjoleink** [comment]
I have the same problem here, and using the 'share' menu doesn't address it.
I have not found any way to 'interact' with any user account that is *mentioned* in a dent, to e.g. 'follow' or 'unfollow' or maybe 'show profile'. It's hard enough to select _just_ the username but this then only leads to the website, not any way to act on this user within AndStatus. The question of teh top poster has not been addressed, it is my question as well. Please re-open!

(Failing this, and no way to follow a mentioned user, I also don't see how I could follow a remote user.)

**Comment by yvolk** [comment]
@marjoleink The question was answered using means, which we currently have. 
This answers for users of current version of AndStatus.
You are writing about new features. Please search the list of already opened issues: most of your wishes are documented there and waiting in the development queue :-)
E.g. #185 #197

**Comment by marjoleink** [comment]
There is no answer to the actual issue, and if it's not implemented (yet) that isn't made clear either. None of what you describe allows to follow a mentioned user, so there are no "means we currently have". IMO this should remain open **until** there is an answer.

**Comment by marjoleink** [comment]
Also, neither #185 nor #197 address the issue *this* question is addressing: how to follow/unfollow a *mentioned* user.

**Comment by yvolk** [comment]
I got the problem: wrong issue title.
If you want your request(s) to be implemented, please create a separate issue for each with a proper title. Otherwise your wishes will be lost.

**Comment by loblue** [comment]
I really want to migrate to such a open software like andstatus and would accept some discomforts, but the essential basics to develop a proper following list is to easy follow and unfollow mention user.

I don't see that this requirement is understood. I guess this guy's don't understand this because they use parallel to the app also the web UI.

Unfortunately do I now migrate back to twicca and can't use gnusocial. But this is better as haven't a feature to following mention user.

**Comment by yvolk** [comment]
@loblue If a user is mentioned in a reply to his message,  following him (her) is simple: 
1. Tap on the message to open Conversation view.
2. AndStatus automatically downloads previous message,  where that mentioned user is an author. 
3. Tap on the message where your desired user is an author and follow him!

**Comment by marjoleink** [comment]
Thanks for reopening, @yvolk!
Following a mentioned user is not necessarily possible with your method: that user (all mentioned users) have not necessarily written anything yet. A dent mentioning other users is not necessarily a *reply* but can simply be *addressed* to a number of users. And someone reading this dent may decide  s/he wants to follow one of the mentioned users (who can be still unknown to the instance this user (reader) is on).

**Comment by yvolk** [comment]
1. As we discussed recently, if a user is unknown to this GNU social instance, we cannot follow him via AndStatus.
2. As a first step I would prefer to implement not "Follow mentioned user" but "Messages of a mentioned user" meaning downloading public user's posts to the User's timeline in AndStatus. 
I assume that we usually start from reading user's posts and then decide if we want to follow him. If you see user's posts, you follow/unfollow him the usual, already implemented way.

**Comment by marjoleink** [comment]
Generally, yes, a user's dents would inform whether or not to follow that user. But there are other use cases. E.g. a user I am already following is frequently mentioning that user in conversations I am interested in. What I usually do in the web interface is 1) visit the user's profile and read the self-description (and any self-tags); 2) read user's dents *if there are any* (the user may be new!). So sometimes I decide only on the basis of mentions or the user's self-description. :)

But it's entirely reasonable to start with a mechanism to retrieve a user's posts. (How about description & tags, though?)

**Comment by loneuron** [comment]
The last comments give me the hope, that andstatus will be useable to develop a follower list without an additional web UI.
Especially the use case as descripted from marjoleink in the last comment is also my use case.

But how can I unfollow a user without using the web UI? 
(sometimes when a user producing to much useless noise I want him quickliy unfollow. I don't want to wait until I have a web UI available)

**Comment by yvolk** [comment]
@loneuron There are Follow/"Stop following" items in a message context menu (long tap on a message/tweet). So you can unfollow now.

**Comment by loneuron** [comment]
It seems to be an issue with the localization.
I use the german smartphone setting.
In German is the item "stop following xyz@foobar.net" written in a different grammar:
"xyz@foobar.net nicht mehr folgen"
But the font is so large that the end of the item isn't display on my galaxy s3.
Therefore can I not see the german equivalent of "stop following"

When I activate the not identificable item, I don't get a feedback about what's happen.
Just the sync starts.
When I choose the item a second time for the same user the item dosn't switch from "stop following" to "follow"

**Comment by yvolk** [comment]
@loneuron Actually German translation is not even complete. Please help improve it here https://crowdin.com/project/andstatus

**Comment by loneuron** [comment]
I changed the translation.

**Comment by yvolk** [comment]
I'm thinking on how to implement this...
Message context menu is too large already, so currently I think of adding one item to the Message Context menu (and maybe delete sevel, related to Users...): "Users of this message...".

Clicking on this new item will open a list of these Users, related to this message:
1. Author
2. Sender (if not the same as an Author)
3. Replied to User (an Author of the message, to which this message is a reply. If any.
4. Mentioned users (not repeating all above)

Each row in this list will show some information on the User:
1. Avatar
2. Username
3. Real name
4. User's description
5. Home page URL 
6. If we (and which our account) follow him.
... 

Context menu of each row allows to act on the User:
1. Follow / Stop following
2. Show User's messages ("User timeline")
3. Open profile page in the Internet
4. Copy @Username to Clipboard.
5. Share the User's info in a text form...

**Comment by amunizp** [comment]
Hi @yvolk does the above mean nested context menus? 
Would it be OK to have two conxtte menu one related to use when tap on avarta or name and other relatedto message (reply to all)twidere seems to do something similar

**Comment by yvolk** [comment]
@amunizp No, the second context menu, described above, will be in the new "Users" view. I will update that post to avoid confusion. 
On different context menues please discuss here: #257

**Comment by yvolk** [comment]
@loneuron Answering original request:
As of AndStatus v.24+ in order to follow/unfollow mentioned User (or to show his/her friends and followers...) you need to select "Users of message" in a Context Menu.
"Users of message" UserList will be opened. In that list you will be able to do anything you want...

**Comment by loneuron** [comment]
Thanks yvolk, I tried again, after a long time, to follow unfollow a mention user and I found a way in the current version :-)
