### ISSUE TITLE
Where AndStatus logs are located?

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#225]
1. Andstatus logs are located in internal Device memory or on SD, depending on AndStatus settings -> Storage -> "External Storage" checkbox.

1.1. If you use "External storage", the path to logs is somewhere here: 
/storage/sdcard/Android/data/org.andstatus.app/files/logs
See the screenshot below

![andstatuslogslocation](https://cloud.githubusercontent.com/assets/207716/6043073/cec3668e-ac9a-11e4-822f-c88e3f5af039.png)

1.2. If you use internal storage, the path is, usually:
/data/data/org.andstatus.app/files/logs  - the path is not accessible on not-rooted device.

**Comment by moshpirit** [comment]
Oops, that's reminds me that I didn't send you mine!! Sorry for that!

**Comment by yvolk** [comment]
In order to have maximum information in logs:
1. Set Storage - Use External storage (in order to have access to log files).
2. Set logging to VERBOSE
3. Turn on "Log Network level messages"
4. Turn on "Log everything to file".

**Comment by yvolk** [comment]
In order to easily find a problem we need to have as few log files as possible. 
So, if you want to prepare logs to investigate a problem, could you please:
1. Sync everything first.
2. Delete all existing logs.
3. Make a test / reproduce the problem (e.g. Reload one Timeline of one account, Send a message etc...)
4. Immediately copy all logs and send them to me.
