### ISSUE TITLE
Accidental space in host definition crashes ANDstatus

### ISSUE THREAD

**Issue by mrvdb** [andstatus/andstatus#226]
On android some keyboards think that after a dot a space needs to appear. They are sometimes hard to see. If there is one in there (I used a gnu-social instance) AND crashes without useful message.

Looking with `adb logcat` revealed the URL contained spaces.

**Comment by yvolk** [comment]
I cannot reproduce this. 
1. Please type here _exact_ "host", which crashes AndStatus.
2. Which AndStatus version are you using?

**Comment by mrvdb** [comment]
AndStatus version: 14.4 (121)

Steps to reproduce:

1. add new microblogging system of GNU social type, using:
   - name: issue226
   - host: `o. mrblog. nl`
   - ssl: off
2. add account on the system, using any name/pass combination

**Comment by yvolk** [comment]
1. It's very strange: I cannot even _add_ new Microblogging system with this "host".
In a log I see:
```
02-05 09:31:44.637: V/Builder(8324): Is not valid: Origin:{name:issue226; url:null, OriginType: {id:3, title:'GNU social'}}
```
i.e. this "host" is not good...
2. Do you mean that you can add such a system, and the crash occurs, when an Account in such a system is being added?!
3. Please look into the already existing Microblogging system again: what do you see in the "Host" field?

**Comment by mrvdb** [comment]
For 2. i can 'save' the host with spaces, not 'add' one (then it beeps at me), So add `o.mrblog.nl` first, than add space and 'save'

**Comment by yvolk** [comment]
I'm still getting correct behaviour: Changed host is simply not saved (see the last line).
In the log I see the caught exception:
```
02-05 18:04:03.179: D/UrlUtils(20731): Malformed URL:'o. mrblog. nl'
02-05 18:04:03.179: D/UrlUtils(20731): java.net.MalformedURLException: Protocol not found: o. mrblog. nl
02-05 18:04:03.179: D/UrlUtils(20731): 	at java.net.URL.<init>(URL.java:176)
02-05 18:04:03.179: D/UrlUtils(20731): 	at java.net.URL.<init>(URL.java:125)
02-05 18:04:03.179: D/UrlUtils(20731): 	at org.andstatus.app.util.UrlUtils.fromString(UrlUtils.java:54)
02-05 18:04:03.179: D/UrlUtils(20731): 	at org.andstatus.app.util.UrlUtils.buildUrl(UrlUtils.java:89)
02-05 18:04:03.179: D/UrlUtils(20731): 	at org.andstatus.app.origin.Origin$Builder.setHostOrUrl(Origin.java:362)
02-05 18:04:03.179: D/UrlUtils(20731): 	at org.andstatus.app.origin.OriginEditor.saveOthers(OriginEditor.java:152)
02-05 18:04:03.179: D/UrlUtils(20731): 	at org.andstatus.app.origin.OriginEditor.access$1000011(OriginEditor.java)
02-05 18:04:03.179: D/UrlUtils(20731): 	at org.andstatus.app.origin.OriginEditor$SaveOrigin.onClick(OriginEditor.java:147)
02-05 18:04:03.179: D/UrlUtils(20731): 	at android.view.View.performClick(View.java:4633)
02-05 18:04:03.179: D/UrlUtils(20731): 	at android.view.View$PerformClick.run(View.java:19330)
02-05 18:04:03.179: D/UrlUtils(20731): 	at android.os.Handler.handleCallback(Handler.java:733)
02-05 18:04:03.179: D/UrlUtils(20731): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-05 18:04:03.179: D/UrlUtils(20731): 	at android.os.Looper.loop(Looper.java:157)
02-05 18:04:03.179: D/UrlUtils(20731): 	at android.app.ActivityThread.main(ActivityThread.java:5350)
02-05 18:04:03.179: D/UrlUtils(20731): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-05 18:04:03.179: D/UrlUtils(20731): 	at java.lang.reflect.Method.invoke(Method.java:515)
02-05 18:04:03.179: D/UrlUtils(20731): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
02-05 18:04:03.179: D/UrlUtils(20731): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
02-05 18:04:03.179: D/UrlUtils(20731): 	at dalvik.system.NativeStart.main(Native Method)
02-05 18:04:03.209: V/OriginEditor(20731): Saved: Origin [name:issue226; url:http://o.mrblog.nl; type:OriginType [ id:3; code:GNU social]]
```

**Comment by mrvdb** [comment]
Restarted the whole process and now indeed save trims out the spaces. Could it be a remnant from earlier version? (I upgraded today) 
I can't reproduce it anymore either now.

**Comment by yvolk** [comment]
Yes, it looks like some incompatible code was cached... I remember two years ago we had a long similar conversation with one user: we couldn't understand each other, because we even had different UI (!) although we thought that we are testing the same version... As I remember that was CM firmware, which wrongly cached something. Solved  by restart/reinstall...

**Comment by mrvdb** [comment]
Seems resolved. Thanks a lot for the quick responses!

**Comment by yvolk** [comment]
Thank you for bug reporting!
