### ISSUE TITLE
Design (background) problem on Android 4.1.1

### ISSUE THREAD

**Issue by blog2read** [andstatus/andstatus#227]
Found a design problem on a Fujitsu M532 tablet. When design is set to "clear" mentions and written posts are have still the **background** of design "dark".

![andstatus02](https://cloud.githubusercontent.com/assets/6249323/6066601/8d3dc982-ad6e-11e4-825a-24196622e4d2.jpg)

**Comment by moshpirit** [comment]
That's so weird, does it happens on your mobile phone too? Have you tried to change the theme again?

PD: Good screenshot ;)

**Comment by blog2read** [comment]
On mobile phone with Android 4.2.2 I don't see the problem. And yes I switched the design serveral times to "clear" and "black" and back again.

**Comment by yvolk** [comment]
As I see the screenshot, the problem with background is only for marked "Replies to myself"?
If yes, I would suggest simply turn off the option "Mark replies to myself in Timeline" (it's in "Appearance").

**Comment by blog2read** [comment]
@yvolk Ok, as workaround accepted, thx - background is "clear" now.
