### ISSUE TITLE
Suggestion: Background in "dark" design

### ISSUE THREAD

**Issue by blog2read** [andstatus/andstatus#228]
Hi
Would it be possible to have dark-gray (eg. #b3b3b3) as backround in the "dark" design.
Thanks.

**Comment by yvolk** [comment]
1. Actually, currently AndStatus uses existing device themes, it doesn't change them. So the color of a background on one device may be different from the background color on another device.
2. The only hack that we have for a background: True Black background, see https://github.com/andstatus/andstatus/issues/195
3. Which exactly background color do you have now? I thought it's sort of "dark-gray" already :-)

**Comment by blog2read** [comment]
The background color (without true black) is here #040000 - but it's quite black. On this list http://www.computerhope.com/htmcolor.htm it should be something between "Black Cow" and "Carbon Gray".

**Comment by yvolk** [comment]
Please try to play with manually (in code) changing Color.BLACK to your desired color.
Does this give you desired effect?

See the function in https://github.com/andstatus/andstatus/blob/master/app/src/org/andstatus/app/context/MyPreferences.java
```java
    private static void setViewToTrueBlack(View view) {
        if (view != null) {
            view.setBackground(null);
            view.setBackgroundColor(Color.BLACK);
        }
    }
```

**Comment by yvolk** [comment]
This is done:
Added "Background color for the Dark theme" option, having 7 dark colors, including Black color from [the List of HTML colors](http://www.computerhope.com/htmcolor.htm).

Currently I added these colors:
```
    <color name="black">#000000</color>
    <color name="night">#0C090A</color>
    <color name="midnight">#2B1B17</color>
    <color name="charcoal">#34282C</color>
    <color name="black_cat">#413839</color>
    <color name="grey_wolf">#504A4B</color>
    <color name="carbon_grey">#625D5D</color>
```
