### ISSUE TITLE
Update User manual format for easier translation and better usability

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#229]
Every time the user manual is modified I have to translate this entire part and Crowdin doesn't let me use the last version to change it, please, use more strings for that. That way, only the modified parts will be deleted and translators only will have to focus on this part.

**Comment by yvolk** [comment]
I agree,  this is a very annoying deficiency of Crowdin. I'm communicating with a Crowdin team on possible improvements ( see https://crowdin.com/project/andstatus/discussions/2 ) but it's not easy for them to solve the problem of changed long strings.

As you suggests,  I will split long strings into smaller... or will figure out something else...

**Comment by yvolk** [comment]
User Manual is updated already,  but it doesn't have images, so I guess we will have to consider a richer format for it. 
HTML with images? But how to organize its translation then... As we see,  even long text only format of a User Manual poses a challenge for translation...

**Comment by moshpirit** [comment]
Ok, thank you very much! ;)

**Comment by yvolk** [comment]
I'm having very productive communication with Crowdin.com team on the Translation system's support of AndStatus User Guide. See the discussion log here: https://crowdin.com/project/andstatus/discussions/5
It's amazing that Crowdin.com fixes some bugs/shortcomings literally on the next day.

**Comment by yvolk** [comment]
In short, User Guide is in FB2 format now (but the file has xml extension for convenience,  see it here: https://github.com/andstatus/andstatus/blob/master/app/res/raw/user_guide.xml )
About the format: http://en.wikipedia.org/wiki/FictionBook

Having a User Guide in FB2 format allows us to have one source for:
2.1. Offline help inside AndStatus application. 
2.2. Online help at a Web site (using XSLT).
2.3. And as a plus the same file may be distributed and read using any ebook reader. And edited using many existing tools.

As a next step I will experiment adding images to the file (FB2 format supports this...)
