### ISSUE TITLE
Push notifications for GNU Social

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#231]
Push notifications allow application to know,  when to start syncing. Thus get faster updates without frequent polling. 

Sample implementation by @kromonos,  which  uses GCM (Google cloud messaging):   http://git.bka.li/kromonos/gcmpush ("You can use the code I've written. But the server side plugin has to be made a bit more secure. Maybe using API Call instead of simple HTTP request")

See the post with Google GCM usage example: http://android-developers.blogspot.ru/2014/09/conference-data-sync-gcm-google-io.html

**Comment by yvolk** [comment]
Current AndStatus implementation already uses Sync Adapter to initiate sync of a selected account in a background. It should be extended to allow syncing of a specific timeline.
After this we will need to add some "Push notification receiver", which will tell,  which Timeline of which account should be synced...

**Comment by kromonos** [comment]
Attention: GCM needs Google Play Services. It doesn't work, when you don't have installed any Google Services.
Also, a plugin is needed on Statusnet/... side, for handling notifications. Sample implementation for a GNU social plugin can found here: http://git.bka.li/kromonos/statusnet-plugins/tree/master/GCMPush
But it's using a simple, unsecure HTTP request for saving device id, ... This could better made over authenticated API, after login with oAuth or Username/Password.
With an additional API response, you can fetch from client side, if the GCMPush is installed and push is usable.

**Comment by yvolk** [comment]
@kromonos 
1. So we need this to be properly implemented on both sides. 
2. Regarding dependency on Google Play Services (and I suspect,  on creation of Google account to use the notifications securely?!) This may be a real blocker for the GNU Social community. l would expect each GNU Social instance having its own (Optional) Push Notifications service...

**Comment by kromonos** [comment]
The GNU social plugin is already useable @yvolk ... The only thing to do is, to rewrite it to use API call for saving device id instead of HTTP call and the data, which it sends to the devices, if you decide, to open conversation on notification click.

I think, it shouldn't be any problem, to implement it as optional service in device, also in the GNU social instance. The GNU social plugin self has the option, to disable it, per user based

**Comment by yvolk** [comment]
As it's written here: http://android-developers.blogspot.ru/2014/09/conference-data-sync-gcm-google-io.html
"...This data must be shared across the user's Android devices, and also between the I/O website and Android. This means this data has to be stored in the cloud, in the user's Google account"
So yes, Google account is required for GCM.

**Comment by yvolk** [comment]
As @draven@quitter.no suggested, we will start from a "GNU Social Push notification plugin", which interface should be independent both from a messaging technology (e.g. GCM), from AndStatus and from the plugin itself. 
I don't think that this plugin will be convenient for a released version (as usually push notifications are in the same  apk as a notified application), but this surely may be used during testing/search for better solutions.

1. Notification intent (which AndStatus or other app will catch) should contain GNU social domain name, not the plugin's.
2. Notification should include this data:
2.1. Webfinger ID (e.g. andstatus@loadaverage.org) of the account to be notified. 
2.2. Timeline type, which has new data  ("home", "mentions" for the start...)

@kromonos Which part of the development you could take part in? The minimum is creating a server side code and making it available for testing at one of GNU Social instances?!
I will do at least AndStatus side.

**Comment by kromonos** [comment]
As I'm a web developer, i would love to help with the gnu social plugin

**Comment by yvolk** [comment]
Glad to hear. 
1. Please ensure you GNU Social server plugin sends this information: 
Webfinger ID (e.g. andstatus@loadaverage.org) of the account to be notified. 
Timeline type, which has new data ("home", "mentions" for the start...)

2. Please install the plugin at an instance, where I could test it and modify, if necessary, the sample at http://git.bka.li/kromonos/gcmpush to work with it.

Then I will do the rest.
?!

**Comment by yvolk** [comment]
@kromonos Did you have time to review my proposal above? What are your plans on this?

**Comment by lipsmega** [comment]
Hi yvolk.. can I download the app to use with my gnusocial installation?

**Comment by vinzv** [comment]
@lipsmega Sure, just grab and install it and add your own instance in the settings.

**Comment by yvolk** [comment]
@lipsmega AndStatus _is_ that application, which will allow you to use your own GNU Social instance.

**Comment by b2410** [comment]
I am not sure whether this here is right but the Push notifications don't work automatic. The notification seems only if the App is open. The notification seems only if one updates the time line manually.

**Comment by yvolk** [comment]
@b2410 Push notifications are still not implemented at GNU Social server side.
But this doesn't mean that AndStatus cannot update timelines automatically. Please see this: #295

**Comment by b2410** [comment]
@yvolk oh, ok. Thanks for the information.
