### ISSUE TITLE
Why doesn't AndStatus retrieve or post any dents?

### ISSUE THREAD

**Issue by marjoleink** [andstatus/andstatus#232]
Maybe the configuration for the server (node/instance) is incorrect?
Go to Settings, Manage microblogging systems and select your node.
If the server does not use SSL (check its web UI!), make sure 'SSL' is not checked.
If the server does use SSL, check 'SSL' and select the mode and security: Secure SSL | Insecure SSL | Misconfigured SSL (experiment if needed to find the correct mode).

Note that AndStatus does not auto-detect whether the server uses SSL (https) or not, so you must tell it what to use.

**Comment by Erkan-Yilmaz** [comment]
auto-detection of which ssl setting fits, would be very handy. (a user on the server here has/had repeated trouble with this)
