### ISSUE TITLE
Separate section in Settings for Attachments

### ISSUE THREAD

**Issue by marjoleink** [andstatus/andstatus#235]
Right now we have:
  * In Syncing: Download attachments over Wi-Fi only
  * In Appearance: Display attached images
  * In Logging and debugging: Modern interface to select an attachment

While the first two are still understandable (the second less so than the first), I fail to see what 'interface to select an attachment' has to do with either logging or debugging, and I would never have looked there for attachment-related settings! It looks like it was added there as an afterthought.

Given that there are also requests for other or more detailed options for attachments, it seems better to  give Attachments their own section in the settings.

**Comment by yvolk** [comment]
"Modern interface to select an attachment" was added to Logging and debugging because I was not sure if ordinary User needs this. 
I agree about a separate section.

**Comment by vinzv** [comment]
I completely agree with @marjoleink: There should be a separate attachements section. I keep searching for settings every time I need them. ;)
