### ISSUE TITLE
Default Timeline setting

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#236]
Currently Home Timeline is always default. One of users wanted to set Everything Timeline as default. 

Please note though that reloading Everything (same as Public)  Timeline doesn't take into account already loaded messages: it always requests the same number of latest messages from a Public timeline (assuming that loading the whole timeline may be too much...). This is not a case for small instances, so maybe "Load full Public timeline" setting should be added to the Microblogging system Editor?!

**Comment by marjoleink** [comment]
Maybe a setting for how many messages to load at a time (e.g., 10/20/50/100/All) would cover "*full* public timeline" and behavior on other time lines as well. Or did I miss a setting for that?
(I have a problem with how many messages are loaded that I'll never read - but that would be another issue.)

**Comment by lulivi** [comment]
The default timeline could be Public without loading new queets every time it opens (I don't know if you understand me, I'm not so good at English, sorry)

**Comment by moshpirit** [comment]
I think it's perfect as it is right now, the settings menu it's very complete and it could confuse some people, maybe should be better to keep it simple and include only other options.

**Comment by lulivi** [comment]
But I think that the main topic of this open code social networks is the public conection betwen people so... (my opinion)

**Comment by moshpirit** [comment]
Maybe #237 could be a good solution, but I don't know if android allows it.

**Comment by lulivi** [comment]
It could be a good idea, I think.

**Comment by yvolk** [comment]
v.20.0. Published to the Open Beta testing channel, please opt in here: https://play.google.com/apps/testing/org.andstatus.app at test it!
