### ISSUE TITLE
No pump notes since 2 months

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#242]
I'm refreshing the TL, but I can't update it including pump.io messages (using 5 accounts: pump, twitter and 3 of GNU social)

**Comment by yvolk** [comment]
If you noticed that you stopped getting updates from some account:
1.Go to AndStatus Settings - Manage existing accounts - select that account from a list.
Account settings window will be opened. 
2. Press "Reverify credentials" button to check and fix authentication-rrelated problems.

**Comment by moshpirit** [comment]
Re-verified, but still the same problem

**Comment by moshpirit** [comment]
I've tried to remove it and add it again, but I only could delete it, if I try to add it, Andstatus crashes (Andstatus has stopped) when verifying

**Comment by yvolk** [comment]
@moshpirit Let's separate different issues.  Crash on adding account and timeline not updated.
I don't have problems getting updates from identi.ca...

Did you succeed in adding account, so we could move further in _this_ ticket? If no, please raise another issue on that, trying to provide me a stack trace,  log...

**Comment by moshpirit** [comment]
But I think it crashes **because** it can add the account.

**Comment by yvolk** [comment]
@moshpirit Anyway, in order to fix the problem, I need to reproduce it or to get logs from who can reproduce it...

**Comment by yvolk** [comment]
I deleted my identi.ca account from AndStatus and created it again - no problems.

**Comment by moshpirit** [comment]
Could you please try to add mine to see if it crashes on your phone? (I had no time to add the password, so there's no need to know it)

**Comment by yvolk** [comment]
I'm getting "Internal error" error message after entering username without a passwort at 1realtime.net site. Please set password and email it to me.

**Comment by moshpirit** [comment]
sent

**Comment by yvolk** [comment]
I created this account, synced all timelines - this works. 
Then deleted it and created again - also no problems. I even posted a test message, sorry :-)

**Comment by moshpirit** [comment]
Ok, I have no idea about what I'm doing wrong, I've recompiled it and it is still crashing.

**Comment by yvolk** [comment]
As you can easily reproduce the crash, you should be able to capture a crash report / log from Android Logcat using Eclipse. 
See https://www.google.com/search?q=android+logcat+in+eclipse

**Comment by moshpirit** [comment]
OK, I've just reinstalled it using a newer version of AIDE. Everything works fine again :+1:

**Comment by moshpirit** [comment]
Ok, the TL doesn't get updated and looks like I'm not the only one with this problem:

>Trying AndStatus again hopefully my automatic syncing of the timeline is back.

[source](https://identi.ca/freemor/note/n1QMAs3QTPmwNNONFcn5zQ)

**Comment by yvolk** [comment]
@moshpirit Is the problem still actual? If yes please check if you can Reload a Timeline manually.

**Comment by moshpirit** [comment]
**Update**: I still can't see any new note from 4 months ago. I think it's a very big bug. Can you see your pump.io TL? How could I delete just the Pump TL without deleting both accounts? Maybe it's because it can't load the next message from the last it downloaded 4 months ago.

**Comment by moshpirit** [comment]
I can see everything perfectly using another clients like Dianara, Puma or Pumpa.

**Comment by yvolk** [comment]
I see pump.io timeline normally.
The fact that you don't see new posts doesn't mean that there is any "bug" ☺
1. Please check if you can Reload a Timeline manually.
2. If you don't see anything loaded,  look in a "Commands in a queue". Is anything there about this?

**Comment by yvolk** [comment]
3. Re-Verify credentials for your Pump.io accounts.

**Comment by moshpirit** [comment]
I tried reloading manually all the time (in every message I wrote here) but I found this error in the "commands in a queue":

R; Avatar para cmhobbs@pump.libernil.net para pump.io R; Avatar , foreground , manual para cmhobbs@pump.libernil.net para pump.io
Creado hace 22 días
executed:1005, last:hace 16 minutos, retriesLeft:10, error:None, 

"Creado hace 22 días" means "made 22 days ago"

**Comment by moshpirit** [comment]
3. I did it a few times too and got nothing :\

**Comment by yvolk** [comment]
Could you please switch AndStatus interface to English and repeat this.

**Comment by moshpirit** [comment]
Sure! (sorry)
R; Avatar for cmhobbs@pump.libernil.net at pump.io
Created 22 days ago
executed:1006, last:4 minutes ago, retriesLeft:10, error:None,

**Comment by yvolk** [comment]
This error is nothing to do a Timeline loading. This means that there was no error downloading a timeline.
The question is, why no new messages are downloaded and/or shown. In order to have an answer to this question, I need a log, created during the Pump.io timeline reload + all "Network level messages", 
saved to files:
"Log everything to file" and "Log Network Level Messages" should be turned on, Minimum logging level: VERBOSE.
Can you find these logs?

**Comment by moshpirit** [comment]
No, sorry, there's no "logs" folder in /storage/sdcard/Android/data/org.andstatus.app/files/logs :( just "database" and "avatars"

**Comment by yvolk** [comment]
ok, this means that you are using internal storage now?!
Is your device rooted? 
If yes, you will see these folders on your internal SD. If no, please switch to External storage first and then repeat  the test and logs search.

**Comment by yvolk** [comment]
...or maybe that path is internal SD? Try to search the same on ExtSdCard...

**Comment by moshpirit** [comment]
In the internal storage I don't have any org.andstatus.app in Android/data :\

Yes, I have enabled the external storage and my phone is *not* rooted.

**Comment by moshpirit** [comment]
I  don't see anything about pump in the logs, do you?

**Comment by moshpirit** [comment]
Sorry for bothering you, but is there any news?

**Comment by yvolk** [comment]
I didn't have a chance to look into all logs. But my first thought is that in order to easily find a problem we need much less files. 
Could you please:
1 . Sync everything 
2. Delete all logs.
3. Make a test of reloading one Timeline of the account only  (not in a Combined mode )
4. Immediately copy all logs.

**Comment by moshpirit** [comment]
I've deleted the account and I can't fix it (see #268 )

**Comment by moshpirit** [comment]
Fixed resintalling it without restoring.Thank you for the support!
