### ISSUE TITLE
@Webfinger configuration: 2 issues.

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#246]
1. On Pump.io: I've disabled the option and nothing happens. No changes at all :(
2. On GNU social (Quitter.es): just changes @username@server to @username

I don't know if you made this option to get these results but my view it's just it should be hidden, just that. No @username@server nor even @username.

IMO, it should add the @server thing only if we're not following this user automatically.

**Comment by yvolk** [comment]
Yes, the behavior you described, is expected.
Regarding pump.io, as I understand, username in pump.io _is_ webfinger_id i.e. already has servername. This allows treating the same user in different pump.io instances as one user. What is quite hard for GNU Social (if not using Webfinger_id to address a user!)

Putting pump.io recipients not in a message body but in a "to" field is another story to be implemented. Do we have a ticket for it already? 

Regarding omitting servername for a followed user in GNU social. I think it's safer to have server appended  for current situation, when I don't have any reliable information on the server behavior.

**Comment by moshpirit** [comment]
OK, looks like rebooting my phone made AS works fine about webfinger

**Comment by yvolk** [comment]
For the reference: we already have "Mention as webfingerId" option in AndStatus Settings -> Manage Social Networks -> (Select an instance, for which you need to change default setting)
