### ISSUE TITLE
[Suggestion] Update AIDE instructions

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#247]
I've updated the version of AIDE because looked like Xperia phones had problems with the last versions. With the change of the github page design, the Android Manifest has changed from the master folder to /app That's why I think you should add this step on [the wiki](https://github.com/andstatus/andstatus/wiki/Building-AndStatus-from-Source-code-on-your-Android-device-using-AIDE-application)

**Comment by yvolk** [comment]
You could do it as you tried this ;-)

**Comment by yvolk** [comment]
I did this, thanks!
