### ISSUE TITLE
  HTTP 411 Length Required error while sending with media

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#249]
I've sent a picure to Quitter.es and the result was: text was sent but not the picture (hosted in the microSD 119Kb, 1280x720). 

Android 4.3, using WiFi

**Comment by yvolk** [comment]
Please provide URL of the post: I will look at it...

**Comment by moshpirit** [comment]
The post looks like just any other post

**Comment by yvolk** [comment]
If you don't want to share _that_ post, please send another one mentioning !andstatus and please post its URL here.

**Comment by moshpirit** [comment]
Done, but now it's not even sent. I'm connected to 3G and WiFi. 
I've checked the queue messages list. I found the message with some error, before reading it, I resent it and now I have: 

>**E**         Post "!andstatus @andstatus testing multimedia" (with media) Created 7 minutes ago  
executed:2, last:6minutes ago, retriesLeft:10, error:None,

**Comment by moshpirit** [comment]
I've tried it again using "text" instead of "!andstatus @andstatus testing multimedia". The same picture, I got [this error](https://quitter.es/notice/300380):

>E; Post "Text" (with media) E; Post "Text" (with media="content://media/external/images/media/256858",)
Created a minute ago
executed:1, last:a minute ago, retriesLeft:9, error:Hard,
updateStatus, text:'Text',
Status code=CLIENT_ERROR; hard;
; statusLine:'HTTP/1.1 411 Length Required'; statusCode:CLIENT_ERROR (411); url:'https://quitter.es/api/statuses/update.json'; authenticated; posted:'{"media_part_name":"media","source":"AndStatus","status":"Text","media_part_uri":"content:\/\/media\/external\/images\/media\/256858"}'; response:'<?xml version="1.0" encoding="iso-8859…'; error='?';
Caused by org.json.JSONException: Value <?xml of type java.lang.String cannot be converted to JSONObject,
moshpirit/Quitter.es,

**Comment by yvolk** [comment]
@moshpirit  This is about the issue we are discussing here: https://quitter.no/notice/341434
I hope that @knuthollund@quitter.no will figure out a solution collaborating with @hannes2peer@quitter.se and then we will be able to recommend the same for quitter.es 
@majestyx@gnusocial.no 

This is some incompatibility between Quitter.no server software and apache.httpclient used by AndStatus. 
As articles mentioned below suggest, this may mean some outdated libraries used at a server side. BTW, there is no such a problem at Quitter.se and Loadaverage.org 
http://stackoverflow.com/questions/15552276/411-content-length-required
http://stackoverflow.com/questions/3208861/http-response-411-length-required-http-client-4-0-1-android
@majestyx@gnusocial.no @knuthollund@quitter.no

As I see here https://github.com/andstatus/andstatus/issues/204 the "411 length required" problem was solved this way: "I was running an old version of nginx and had to install some additional modules to get rid of the 411 error".

**Comment by moshpirit** [comment]
OK, so, how many time do you think it should need? just to know : )

Thank you both for your work!

**Comment by yvolk** [comment]
@knuthollund @andstatus There's this setting in FastCGI that restricts the request size (which is yet another setting apart from PHP's own max_upload_size and max_post_size). Is that related perhaps? When running Apache and mod_fcgid at least, the setting is: FcgidMaxRequestLen - probably something similar for mod_fastcgi.
-- 
mmn@social.umeahackerspace.se
 URL: https://loadaverage.org/notice/6849737

**Comment by yvolk** [comment]
As the below report shows, the problem may be actually not (only) in the content-length.
As someone suggested,  this is more about "request validation" in general. This is fixing the problem by configuration looks more feasible. 

@hannes2peer It's about an error we experience with .no and AndStatus - The following error occurs on the server when posting e.g. a image via AndStatus - "chunked Transfer-Encoding forbidden: /php5-fcgi/index.php" Have traversed the amazing internet , but yet not found solution to it, just simular errors which is old apache/fastcgi stuff.  /cc @andstatus
-- 
knuthollund@quitter.no
 URL: https://fediverse.com/notice/683585

**Comment by knuthollund** [comment]
Just a fyi:

quitter.se -> Apache2 - mod_php - works ok
quitter.no-> Apache2 - mod_fcgi - php5-fpm - experiencing the issue
quitter.es -> nginx - fcgi - php5-fpm - experiencing the issue

Also lnxw48 - reports to see this issue with the setup I'm using on quitter.no -> https://fresh.federati.net/notice/213189

I got a test server kollektivet0x242.no - which is using nginx - fcgi - php5-fpm.
When I get back home from work I will test and verify if the error is experienced there as well. (Which it should). If so I will test the suggestion of using chunkin on; when I get home from work. ( http://wiki.nginx.org/HttpChunkinModule )

**Comment by knuthollund** [comment]
FYI:
Does not work with my nginx - fcgi - php5-fpm installation either.
nginx v.1.2.1 (default in stable debian).
The proposed HttpChunkinModule must be installed separately (not standard debian yet) and have not been tested with my version. Thus I will not install this. I guess you must find another way andstatus can resolve this. All GNU social instances with apache2 mod_fcgi will fail on this. Also typically "stable" version of nginx.

**Comment by yvolk** [comment]
As I understand now, lack of chunked encoding support is a real cause of this incompatibility. Chunked encoding is used exactly when content length is unknown beforehand. 
As suggested here: http://stackoverflow.com/questions/7721554/httpclient-disabling-chunked-encoding , switching to HTTP 1.0 protocol reliably turns this feature off, and this will ensure compatibility with different legacy/"simple" server implementations. 
I will test this and will add corresponding compatibility option to the Social network editor ("Manage Microblogging systems" now).

**Comment by knuthollund** [comment]
Thanks for looking into another way of solving this.
Yes - It seems that not all "popular" http server implementations support all of the HTTP 1.1 protocol, which is only 9(?) years old. :)

**Comment by yvolk** [comment]
As I understand now, lack of chunked encoding support is a real cause of this incompatibility. Chunked encoding is used exactly when content length is unknown beforehand. 
As suggested here: http://stackoverflow.com/questions/7721554/httpclient-disabling-chunked-encoding , switching to HTTP 1.0 protocol reliably turns this feature off, and this will ensure compatibility with different legacy/"simple" server implementations. 
I will test this and will add corresponding compatibility option to the Social network editor ("Manage Microblogging systems" now).
PS: I don't set content length in AndStatus code. Nowhere. It's done or not by underlying apache.httpclient or java.net libraries.

**Comment by yvolk** [comment]
I succeeded in  posting a message with an attachment to Quitter.no. 
This required two changes:
1.  Set apache HttpPost request to HTTP 1.0 protocol:
```
HttpPost request;
...
request.setProtocolVersion(HttpVersion.HTTP_1_0);
```

2. When creating Multipart post request I'm providing as an input for an attachment not a InputStream (as for HTTP 1.1, which causes chunked encoding), but an array of bytes,  which I have to create from the same stream beforehand. This is why content length is known. 

BTW, I still don't set content length header anywhere in AndStatus code. This is done at HTTP library level.

**Comment by yvolk** [comment]
The only thing left is to add the "USE legacy HTTP protocol" option to a "Social network".

**Comment by knuthollund** [comment]
I support what MMN-o proposed on "GNU social" conversation. A autmatically fallback. Try with HTTP 1.1 - if it fails , do the 1.0 legacy stuff.

**Comment by yvolk** [comment]
As we discussed already regarding "SSL Mode" in AndStatus, indeed, it would be good for a client application to adapt to a server automatically. 
But as for an "SSL Mode", for the second option: "Use legacy HTTP protocol" - automatic discovery _during normal operation_ of a proper connection option is not practical. Because this will mean substantial time delays and network traffic increase. E.g. in this "411-content-length-required" case, for each attempt to send a message with an attachment, AndStatus will first do failed attempt and succeed on a second attempt only.
I think we better integrate such server parameters discovery into Account creation / verification. Which may be repeated on User's explicit request to "Reverify account".
?!

**Comment by yvolk** [comment]
Automatic fallback in a case of 411 error already works.

**Comment by moshpirit** [comment]
After a few installations, I found that I can't use AS if I use some configuration to logging and debugging settings.

The result: AS crashes. I'll search the specific configuration tomorrow

**Comment by yvolk** [comment]
Please see an example of "Use legacy HTTP protocol" set to "Yes"
![scr-origin-editor-legacy-http](https://cloud.githubusercontent.com/assets/207716/6994407/7904b724-db21-11e4-8d10-fe9c6da11ee1.png)

**Comment by yvolk** [comment]
@moshpirit This may be language specific, please test the same while switching AndStatus to English interface...
BTW I have full VERBOSE logging always turned on, including saving everything to file: I had a crash related to logging only once, and fixed the bug more than a week ago.

**Comment by moshpirit** [comment]
Nope, I have the last beta version with all my accounts using Legacy HTTP protocol enabled and I only get this error if I use VERBOSE, the language doesn't seem a difference.
