### ISSUE TITLE
A lot of crashes in the last ß version auto refreshing the TLs

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#250]
It's very annoying: every time I open AS or change the TL, it crashes, I think it's a bug made every time it refresh automatically the TL.

**Comment by moshpirit** [comment]
I've disabled "sync when using the app" option and it doesn't crash when it get opened but it does if I select the "User" TL (my notes).

**Comment by yvolk** [comment]
As I wrote in different places, I need to reproduce this or to receive a crash dump/log with a stack trace in order to know, where and when the problem occurs.
I constantly use AndStatus on two devices - it never crashes. Both devices a manufactured in 2014...

**Comment by moshpirit** [comment]
The thing is that, I can't use the correct debugging settings to share you the log because AS crashes and I have to delete the data to use it again.

**Comment by moshpirit** [comment]
Maybe it's an AIDE bug or something and I'm installing it wrongly (I'll git pull it and install it again) btw, I'm translating the user manual and I've written a note about Syncing on Crowding.

**Comment by yvolk** [comment]
If application crashes, its own log may not have the needed stack trace. So in order to receive the needed information on a crash you should (as one of ways...) connect your device to PC and read/copy logs from PC...

**Comment by moshpirit** [comment]
I have no "logs" from today, but I'll send you the entire "files" folder.

**Comment by moshpirit** [comment]
Ok, /storage/emulated/0/android/data/org.andstatus.app/files/logs is empty, but databases is not. What should I do?

**Comment by yvolk** [comment]
@moshpirit  Logs, created by AndStatus itself, are _not_ for crash dumps. 

Crash dumps / log records, containing detailed crash information, are recorded by Android system and may be captured by special tools.

Tool examples are below:

1. If your device is rooted, you may use CatLog application to capture crash logs: https://play.google.com/store/apps/details?id=com.nolanlawson.logcat&hl=en

2. Please see here about another way to get crash report: https://github.com/andstatus/andstatus/issues/183

3. Eclipse application on a PC, connected to the device, is one of such tools. 

About such ways see e.g. here: https://testlio.com/question/how-to-get-consolecrash-logs-for-android

**Comment by yvolk** [comment]
I think that getting used to such tools may be too much for most of users, this is why I'm usually asking to install AndStatus from Google Play, which enables crash reporting out of the box (and I use it!).
For users downloading AndStatus from other sources (or building AndStatus themselves), I guess the only answer would be integrating such crash reporting tool inside AndStatus (e.g. this: https://github.com/ACRA/acra )

**Comment by yvolk** [comment]
@moshpirit I added ACRA (https://github.com/ACRA/acra ) crash reporting to AndStatus. It automates collecting of all required information and allows a User to send the report via email to AndStatus team.
Please use it for your crash reports!

**Comment by moshpirit** [comment]
Of course, thank you!!!

**Comment by moshpirit** [comment]
Hmm looks like it doesn't crashes anymore (yet). I'll close it the sunday if it doesn't crashes anymore in the entire week, OK?

**Comment by yvolk** [comment]
@moshpirit  Thank you for the Report!
The "Out Of Memory" Error occurs at a seemingly harmless place while listing AndStatus log files:

 for (String filename : dir.list()) {

The problem may be only in a case the directory with log files has too many files (see e.g. here: http://stackoverflow.com/questions/3139073/how-to-list-a-2-million-files-directory-in-java-without-having-a-out-of-memory-e ).

Q1. Could you find the log folder and count (or maybe even list them)?
Q2. How often do you get this error? Please keep me informed...

Suggestions: 
1. In order to clean the storage (including directory with logs) I would suggest Backup AndStatus - > Uninstall -> Install AndStatus -> Restore Backup.
2. Please investigate memory (RAM) consumption by different applications. Maybe some other app takes too much memory...

**Comment by moshpirit** [comment]
That's because I changed the storage settings, letting AS to download more attachments than usual.

**Comment by yvolk** [comment]
I would recommend you to set logging level to default "INFO" and to stop logging to file.
Please also try my above suggestions.

Regarding attachments: Yes, images seem to be the most memory consuming element. I will implement an option to reduce a size of images, displayed in a Timeline: this will certainly help in a cases, where there is not enough RAM. BTW, images are smaller in a portrait mode...
However, I would ask you to investigate, how _other_ applications use your device's memory. Maybe some of the other applications is taking too much memory...

**Comment by yvolk** [comment]
@moshpirit Please test with the latest commit: I changed scaling of attached images to produce smaller images (and hence to occupy less memory). 
You should get "Out of Memory" less often now.

**Comment by moshpirit** [comment]
Ok, I'll do it! Thank you! Btw, I think I remember that I made an issue asking for it :-)

**Comment by moshpirit** [comment]
Thank you but I think that there should be 2 different menus when we hold down a message:

- If we push the note/user → Normal menu except "view image"
- If we push the picture → View image in full resolution

That would make the menu a little more clear and if we separate it in 3 menus would be something even better: 

- Note: 
  - reply
  - reply to all
  - share
  - favourite
  - repeat
  - open on Internet (I think it should be "open using a browser")
  - open conversation

- User:
  - Direct message
  - Messages by "Username"
  - Follow "Username"

- Picture:
  - View in full resolution

I'll open a new issue for that.

**Comment by moshpirit** [comment]
OK, it was Telegram, it was consuming 500+ MB of cache ¬¬
