### ISSUE TITLE
Widget seems stuck

### ISSUE THREAD

**Issue by sevan6** [andstatus/andstatus#251]
Hi,

First of all, thanks for this great app!

On my android device (4.2.2) with AndStatus v16.0 the widget is sometimes frozen : displays "no data since <hour>" and never refreshes anymore. By removing and putting the widget back, it displays "no data yet." forever. Even when opening the app and refreshing the timeline, the widget seems ignoring the update.

Only have a twitter account configured.

Keep up the good work!
Sevan

**Comment by yvolk** [comment]
Hi Sevan,
The widget shows new messages _only_ when these new messages are received in a background, while you are _not_ using AndStatus.
Number of new messages is reset, when you open AndStatus application.

**Comment by sevan6** [comment]
Hi Yvolk,

Thanks for your quick answer!

Yes, that was the case : when I opened the app, the widget was reset and displayed the time since which there was no new messages.
But when syncing in background, the last sync time was updated on the widget.

Now the time is frozen, or (when I remove the widget and set it up again) the 'no data yet' message is displayed forever.

Maybe it is linked to the syncing mechanism of Android itself : I tried to restart my phone and the widget displays "Nothing new since: <hour>" which is the expected behaviour.

But at the end of the day, widget was stuck again.

Can it be linked to a limit of 'sync request' on Twitter ? Does third party app like AndStatus have a limited request number via the tiwtter API ?

Thanks,
Sevan

**Comment by yvolk** [comment]
Hi Sevan,
I think automatic syncing is turned off in Androis "Settings" application: for all accounts or only this AndStatus one.
Please check.
See below an example Android screenshot where sync for some accounts is "on", and is "off" for others...
![scr-manage-accounts](https://cloud.githubusercontent.com/assets/207716/7043109/d0751ce4-ddef-11e4-9ef4-e1b1365f8f2f.png)

**Comment by sevan6** [comment]
OK will check.

Thanks again !
