### ISSUE TITLE
Preconfigured accounts: Quitter.Zone, Quitter

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#252]
I've just installed the last ß version and I've seen that it show 7 types of accounts preconfigured by default and one of them it's Quitter.Zone, which is no longer available. I think that Quitter should be called Quitter.se and pump.io should be capitalized (**P**ump.io).

**Comment by moshpirit** [comment]
Btw, I've also seen that the last translations I made are not included yet, could you please include them? (I know you have made 2 commits for translations updates, but I couldn't get them before)

**Comment by vinzv** [comment]
As far as I understand preconfigured nodes are fetched from gstools.org. So maybe the admin there has to remove dead instances?

**Comment by yvolk** [comment]
@moshpirit  I checked current code: everything is already exactly like you suggested. https://github.com/andstatus/andstatus/blob/master/app/src/org/andstatus/app/data/MyDatabase.java
You have old names because you didn't do fresh install for a while :-)

**Comment by moshpirit** [comment]
I've installed the app doing a fresh install since I uninstalled the beta version to use the stable and later I did the same to install the beta version once again, maybe it's a restore bug or something :\

**Comment by yvolk** [comment]
This is a feature of Restore :-) You restored old Social networks also:-)
