### ISSUE TITLE
Behavior of back button/key

### ISSUE THREAD

**Issue by vinzv** [andstatus/andstatus#253]
When I search for something and I want to go back to main timeline the back button/key closes AndStatus despite going back as expected. Same thing for going back from Mentions to main timeline.
I think that's no big problem but a bit confusing compared to other (social networking) apps.

**Comment by yvolk** [comment]
Actually a User has a clue when he is on a Home screen: no Up button on an Action bar. 
But I agree that maybe we should have a "Default Timeline" as suggested in #236, and Back button would return to this timeline first?!

**Comment by yvolk** [comment]
BTW,  Back and Up buttons are not the same...

**Comment by clacke** [comment]
Agree, back button should go back from current view state to previous view state. If I change the view state and back button closes the app, that's confusing -- especially when in a "custom" mode like search. I have closed AndStatus many times due to this.

**Comment by yvolk** [comment]
@clacke I recently thought about allowing the Timeline Activity to have multiple instances. The main problem,  which we may face in that case, will be "Out of memory" error. 
Anyway, I will definitely try this. Now I'm redoing Timeline content loaders #313 , so this change, maybe as an option, looks like natural...

**Comment by yvolk** [comment]
I think that we don't need multiple instances of a Timeline. We could just remember a history of timeline switching. And go back that history (switching in reverse direction...

**Comment by bulletbites** [comment]
I just posted #356 which is pretty much the same issue. Is it not possible to have a "home/back-option with the home setting being the default TL position?

**Comment by b2410** [comment]
referred of #422

Yes, I think we mean the same.

I summarize again:

This symbol is above if I am the start time line on. on the left:

![11](https://cloud.githubusercontent.com/assets/8990939/19000696/414bbbfe-8744-11e6-97ce-6da6576432b8.jpg)

I have this back arrow at many but not all undersides:

![22](https://cloud.githubusercontent.com/assets/8990939/19000824/e454f8d8-8744-11e6-8191-f14a744d6c21.jpg)

It would simplify the navigation very much if this arrow on every underside existed.

**Comment by yvolk** [comment]
@b2410 What you show on your screenshots is "Up" button, which is about navigation in a hierarchy of views. "Back" button is a hardware button below the device's display. _That_ button is about history of navigation between views (e.g. history of switching between different timelines of AndStatus.

Please read this carefully: https://developer.android.com/design/patterns/navigation.html (I did this right now...)

Taking that Android guidelines and terminology into account I think that "Up" button, which you showed above, works correctly (at least in most cases...).
What definitely needs to be improved - the dedicated (usually hardware) "Back" button, which generally looks like this:
![back_button](https://cloud.githubusercontent.com/assets/207716/19012215/7adfe7a0-87b7-11e6-9180-775d7a846d3d.png)
or like this (onscreen button):
![back_button_android-7](https://cloud.githubusercontent.com/assets/207716/19012223/e794daf4-87b7-11e6-97f4-37725b01189e.png)

**Comment by b2410** [comment]
Excuses my mistake. I have never noticed the difference.

It is working now as described in the link. Perfect.

**Comment by yvolk** [comment]
Implemented in v.30.00. Please test: the Open Beta testing channel https://play.google.com/apps/testing/org.andstatus.app

**Comment by b2410** [comment]
@yvolk It functions perfectly. Thank you.

**Comment by yvolk** [comment]
@b2410 Actually the change was trivial. Why I didn't do this earlier: I was afraid that this would cause out of memory issues. Please report if you have them after this change.

**Comment by b2410** [comment]
@yvolk I test it 5 days without problems. The app or the phone was not restarted. More Ram is not required.

**Comment by yvolk** [comment]
@b2410 Thank you for the feedback!
