### ISSUE TITLE
no way to cancel the draft 

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#258]
If I'm going to reply something and I hide the message, it's saved in the draft, but if I try to share any other post, it appears the draft. I don't want the draft, I want to share the other note. Does really exist a way to cancel this draft? If so, I think it should be improved to be more intuitive.

**Comment by yvolk** [comment]
Pressing the "minus message" button on an Action bar should cancel the Draft.

**Comment by moshpirit** [comment]
It doesn't :\ I'll try it on the last version!

**Comment by moshpirit** [comment]
Ok, it doesn't, just clean the draft, so if I'm writing something, I hide the message and want to share anything  with this account, the message looks empty. So I have not the message I want to share nor the message I was writing neither.
