### ISSUE TITLE
Sync via WiFi only

### ISSUE THREAD

**Issue by vinilox** [andstatus/andstatus#259]
Could you add an option to sync via wifi only please ?

**Comment by yvolk** [comment]
We do have an option to download attachments via WiFi only.
Why do you need to stop sync completely without WiFi?

**Comment by vinilox** [comment]
Yes we already have download attachments via wifi only and it's great !
The option to sync timeline via wifi only is usefull when you want to sync your timeline frequently at home but don't want on 3G/4G to prevent using data (even if andstatus doesn't use a lot of data) or to save battery (I am in this case).

**Comment by yvolk** [comment]
Thank you for explanation, will definitely add this.

**Comment by vinilox** [comment]
Thank you !

**Comment by DoctorJellyface** [comment]
Any updates?

**Comment by yvolk** [comment]
Implemented in v.27.00 (180), available at the Open Beta testing channel https://play.google.com/apps/testing/org.andstatus.app
