### ISSUE TITLE
[Jolla phone] Application freezes at different places

### ISSUE THREAD

**Issue by SebasFC** [andstatus/andstatus#260]
I use a Jolla phone, I can use both SailfishOS and Android apps.
When I searched the Andstatus version I was using I tried to leave the page. 
Impossible, neither Gesture based commands nor pushing the arrow back button would 
let me go back, so I had to Force close the App and reopen it.

**Comment by SebasFC** [comment]
version v.17.0 (124)

**Comment by yvolk** [comment]
Reading [the article](https://jolla.zendesk.com/hc/en-us/articles/201440787-What-Android-apps-does-Jolla-support-and-how-do-I-get-them-) I would say that if this is the biggest problem then AndStatus is compatible with Jolla phone :-)
1. Please provide a screenshot where you have the crash.
2. Does the window asking you to send crash report to AndStatus team, opens after a crash?

**Comment by SebasFC** [comment]
1) There is no specific error message it just showed the information of the version of AndStatus but nothing else.
2) I have not seen any window asking me to send crash report yet. It simply gives you two options: Wait or Close Andstatus.

**Comment by yvolk** [comment]
1. I would like to see how that screen looks on your phone. 
2. Try different options,  maybe you will be able to send crash report... although I don't think that I will be able to fix the problem. But maybe somebody else, who has this device...

**Comment by SebasFC** [comment]
Now that I have wifi I am going to download a screenshot app for Jolla. right now I am unable to use Twitter in Andstatus. Gnusocial.de loads fine. Let me take the screenshots for you. Just cradhed again but no crash report. Is there a way to force a crash report if it does not show up automatically?

**Comment by SebasFC** [comment]
![screenshot-25-04-15-13-05-45](https://cloud.githubusercontent.com/assets/12103021/7332678/1d816aa6-eb4c-11e4-8e12-b3839d9da411.png)

**Comment by yvolk** [comment]
Aha, so now I got this:
1. Timeline loads Ok for Gnusocial.de
2. Timeline for Twitter loads also, but when we see Twitter timeline at some point (when, please describe!)  AndStatus _freezes_
Please note that this is not crash but _freeze_. I think this is why you don't get any crash notification.

**Comment by SebasFC** [comment]
What should I do when my only interaction with AndStatus is freezing? :(

**Comment by yvolk** [comment]
@SebasFC Can you use PC to capture Android logs to figure out at which operation the freeze occurs?

**Comment by yvolk** [comment]
Some clues for those who will decide to investigate this compatibility problem. 
1. AndStatus actively uses multithreading and the fact that Android supports multitasking. 
This didn't produce any problems on Android devices so far. 
2. The only weak place is access to a database: it doesn't handle concurrent requests good enough. This is why (almost?) all database requests are asynchronous (I.e. in separate threads)
3. One may decrease probability of freezes by disabling AndStatus sync in a background  (Turn off "Sync while using AndStatus" option)
