### ISSUE TITLE
HTTP 401 when using User's own GNU Social server installation

### ISSUE THREAD

**Issue by zackp30** [andstatus/andstatus#261]
```
I/VerifyCredentialsTask(26549): A connection error occurred
I/VerifyCredentialsTask(26549): Status code=UNAUTHORIZED; hard;
I/VerifyCredentialsTask(26549): statusLine:'HTTP/1.1 401 Unauthorized'; statusLi
ne:'HTTP/1.1 401 Unauthorized'; statusCode:UNAUTHORIZED (401); url:'https://soci
al.apertron.net/api/account/verify_credentials.json'; authenticated
```

I get that when trying to login for the url `https://social.apertron.net`, it then produces a 401, but I can login on the website fine.

If you would like to test I'd be happy to provide an account.

Thanks!

**Comment by yvolk** [comment]
Please look at the similar problem and solution: #214 
Looks like you need to change "SSL mode" n a Social network editor?!
