### ISSUE TITLE
Reducing the amount of storage used 

### ISSUE THREAD

**Issue by akwala** [andstatus/andstatus#262]
The app is taking up a whopping 2.36GB on my Nexus 5, which is likely due to my history settings of 1year & 100K messages. I changed them to 1 week &  500 messages. How can I trigger a purge of my history to bring it down to the new limits, and consequently freeing up disk space?

**Comment by yvolk** [comment]
The purge occurs once in a day, so please wait for awhile :-)
Please report if the purge happened?

**Comment by akwala** [comment]
Yes, the purge did happen at some point, it's now down to about 700MB.

Would be good to have the option to trigger the purge immediately in case space needs to be freed up urgently.

Re the max no. of messages: Is that for each account or the total of messages in all account?

If both time and no. of messages are specified, the limit (time/messages) that's reached first causes the purge to happen, yes?

**Comment by yvolk** [comment]
@akwala Maximum number of messages is total,  for all accounts. 
AndStatus checks both conditions sequentially. See the code here: https://github.com/andstatus/andstatus/blob/master/app/src/org/andstatus/app/data/DataPruner.java
You may create new feature request for "Purge now"...
