### ISSUE TITLE
Auto complete username in new message.

### ISSUE THREAD

**Issue by amunizp** [andstatus/andstatus#265]
#224 #257 are related but not quite. This is an optional non-default non-critical feature request. As the default behaviour of selecting a userpost works fine but what if person you want to mention is not in latest timeline?

When typing @x in message where x is caracter if it corresponde to first caracter of someone you follow (by name or username) it will show options in a scrollable dropdown menu. 

External reference where this kind of works is twidere https://github.com/TwidereProject/Twidere-Android/releases

**Comment by schiessle** [comment]
I would also love to have autocomplete for user names while composing a new message. Also automcompletion for GNU Social groups would be great!

**Comment by yvolk** [comment]
This request duplicates #151 . please followup there.
