### ISSUE TITLE
Can't add any pump.io account. AS crashes after trying it.

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#268]
I've seen that I always got the same error to pump.io in the queue, so I decided to unfollow this account (actually, the server isn't available anymore), delete my account from AS and add it again, but AS crashes everytime I try to add it.

**Comment by yvolk** [comment]
So please send me that crash rdumpreport.
It's _very_ easy to fix a crash having  that report.

**Comment by moshpirit** [comment]
How can I do it? Is it in the logs too?

**Comment by yvolk** [comment]
If AndStatus really crashes  (not "freezes"), a prompt to send a crash report should appear automatically. 
I'm not sure, if the project, compiled with AIDE, will behave this way... (I read somewhere that it doesn't fully support Java annotations...)
Please try building AndStatus using Eclipse or use prebuilt package  (ffrom f-droid or Google Play ).

**Comment by moshpirit** [comment]
I get "unfortunately AS has stopped".
Mm OK, I'll install it later from F-Droid to see what happens and I'll let you know

**Comment by moshpirit** [comment]
Fixed resintalling it without restoring.Thank you for the support!
