### ISSUE TITLE
Support for /api/conversation/show and /api/statusnet/conversation/

### ISSUE THREAD

**Issue by annando** [andstatus/andstatus#270]
Friendica and Statusnet support commands for fetching all posts of a thread. Friendica and Statusnet are using different commands for that.

For Friendica it is "conversation/show". For parameters see the documentation: https://github.com/friendica/friendica/wiki/Friendica-API

This command is used in Twitter as well - but can only be used with the application keys for the original Twitter app.

Statusnet has a slightly different approach. The API call is "statusnet/conversation/4711.as"  (where "4711" is the conversation id). The extension ".as" is important.

Using these commands would speed up the showing of threads very much.

**Comment by yvolk** [comment]
Will be implemented in #328
