### ISSUE TITLE
[pump.io] Some activities sent to Public instead of letting the server decide

### ISSUE THREAD

**Issue by ArceePrime** [andstatus/andstatus#271]
Related to #190, I've noticed from a desktop client that other activities done via AndStatus, such as liking notes or comments, or following people, are also sent "To: Public" instead of just using the original addressing of the post in question.

I imagine the solution is the same as @yvolk commented there: just send the activity without addressing and let the server handle it.

Thanks for all your hard work; it's appreciated! :)

**Comment by yvolk** [comment]
@ArceePrime Thank you for noticing. This looks like a bug after fixing #190

**Comment by jankusanagi** [comment]
Fixing this would probably be easy (mostly _removing_ code), and really appreciated.

**Comment by yvolk** [comment]
Done, although solution is not supported by any documentation. Let's try if anything needs more adjustment. 
Now "Public" is added to "to" in a case no other recipients are found only for "post" and "share" activity types.
Please see ActivityType(s) the definition: https://github.com/andstatus/andstatus/blob/master/app/src/main/java/org/andstatus/app/net/social/pumpio/ActivityType.java

**Comment by jankusanagi** [comment]
> Done, although solution is not supported by any documentation.

Well, if it helps, it's supported by years of proper implementation in the Pumpa and Dianara clients =)

> Now "Public" is added to "to" in a case no other recipients are found only for "post" and "share" activity types.

In my opinion, To/Cc should not be specified for "share" activities, only for "post", and only if the "post" activity doesn't have "inReplyTo" set; that is, original content: creating a note, an image, a video, an audio...

**Comment by yvolk** [comment]
@jankusanagi I relied on your experience and made this change also:
"share" activity now don't have any recipients

So the only activity, which has "Public" collection automatically added as a recipient, is "post", and only in a case:
- the message is not addressed to a concrete user (i.e. it is not a "Direct message" in terms of AndStatus' context menu) and
- the message is not a reply to any other message.

**Comment by yvolk** [comment]
The fix is available since v.29.00. Currently in the Open Beta Testing Channel: https://play.google.com/apps/testing/org.andstatus.app
