### ISSUE TITLE
Immediate Crash on Nexus 5 Android 4.4.4

### ISSUE THREAD

**Issue by BoringUserWhoCantCode** [andstatus/andstatus#272]
Reproduce:

Install AndStatus, read the welcome screen, click "Get Started"... The application crashes with a non-typical crash screen.

![ghjmk](https://cloud.githubusercontent.com/assets/8726042/8274771/19f05e70-18a0-11e5-8b73-d24bb966ebcf.JPG)

**Info**
Nexus 5
Android 4.4.4
AndStatus 17.1

**Comment by yvolk** [comment]
Hello @BoringUserWhoCantCode,
This Crash screen is created by ACRA (https://github.com/ACRA/acra ) crash reporting library. It automates collecting of all required information and allows a User to send the report via email to AndStatus team.
Please press OK and send me the Crash report via email, because I cannot reproduce the problem. 
Please use it for your crash reports!

**Comment by yvolk** [comment]
I had to add this "non - typical" crash reporting, because it appeared that many AndStatus users download it NOT from the Google Play Store and hence cannot use "typical" Crash reporting facility, provided by Google. 
See e.g. this discussion: https://github.com/andstatus/andstatus/issues/250

**Comment by BoringUserWhoCantCode** [comment]
Fair enough.

I sent you a report :)

Thank you for your time and effort.

**Comment by yvolk** [comment]
@BoringUserWhoCantCode Thank you, now the place, which caused exception, is located. 
```
Caused by: java.lang.NullPointerException
at org.andstatus.app.origin.OriginList.processNewIntent(OriginList.java:89)
at org.andstatus.app.origin.OriginList.onCreate(OriginList.java:69)
```

**Comment by BoringUserWhoCantCode** [comment]
Well, good luck :D

I see some gibberish there, I have no idea what it says.
Could be that my phone is swearing at me for all I know. Seems fun though :p

**Comment by yvolk** [comment]
@BoringUserWhoCantCode I didn't find any evidence that AndStatus has a "bug" in this case. This is more like a incompatibility, which I cannot reproduce and hence I don't know,  which solution will work. 

As you are the only available user, who can reproduce the issue, I'm trying to figure out how we can solve the problem together. I hope you you're not completely bored as you are posting here?! :-)
If so, could you try https://github.com/andstatus/andstatus/wiki/Building-AndStatus-from-Source-code-on-your-Android-device-using-AIDE-application or maybe Android Studio? !

**Comment by BoringUserWhoCantCode** [comment]
@yvolk, sure I can try AIDE. Seems interesting.

But what a should I clone?

**Comment by BoringUserWhoCantCode** [comment]
I compiled it and ran it. It then prompted me to install, I did. Ran the app, still same error.

**Comment by yvolk** [comment]
Good  :-)
I will create a branch for this investigation and will let you know.

**Comment by BoringUserWhoCantCode** [comment]
Thanks for your support and time :)

I will be here.

**Comment by yvolk** [comment]
1. Please switch to the branch "issue272" and test it.
2. BTW, do you see any "Action bar" at the first screen? If should have "Overflow button" with a link to Settings. Please try to go there...

**Comment by BoringUserWhoCantCode** [comment]
Can you please tell me what link do I clone to get the branch, not the master tree?

I couldn't figure this out, sorry.

**Comment by BoringUserWhoCantCode** [comment]
Building finished with no errors.

I installed the AndStatus and immediately when I click Open, it crashes. Nothing was seen of the app this time.
![_20150629_220328](https://cloud.githubusercontent.com/assets/8726042/8415939/e32602c6-1eaa-11e5-90c2-da1f352c4198.JPG)

**Comment by BoringUserWhoCantCode** [comment]
About your second point in your comment, yes, I just installed F-Droid version again, and I can indeed get to the settings.

**Comment by yvolk** [comment]
I think that maybe your device's "Default theme" is not compatible with AndStatus now. please:
1. Go to Settings -> Appearance -> Color theme -> Dark (or Light...)
and see if this helps?!

**Comment by BoringUserWhoCantCode** [comment]
Nope. Didn't do it.

I also toggled External Storage, Color, language, and nothing helped.

Anyhow, seeing as I've been seeing quite a bit of apps not working properly lately, I think I'll format my phone and start fresh. 

It's not fair wasting your time on one person bug.

Thank you so much for making open source software.

I'll close this, but will try the app again some time later with a fresh OS install.

**Comment by yvolk** [comment]
Thank you. Anyway, it would be good to know if the problem was solved :-)

For my future record, to try this:

Add the element to your style definition:
```
<item name="android:windowActionBar">true</item>
```

**Comment by yvolk** [comment]
@BoringUserWhoCantCode Please test the latest commit  or release 18.0 at Google Play:
Yesterday I noticed and fixed another possible cause of AndStatus stopping immediately and without any visible errors.
I disabled Android backups: some bug faced on Lollipop, like here: http://stackoverflow.com/questions/27029273/backupmanagerservice-restoration-timeout-leads-to-force-stop

**Comment by BoringUserWhoCantCode** [comment]
@yvolk, sorry I haven't gotten back to you. I don't really get on Github unless I have someone (or some project) to reach out to.

I did test that, and it now works like a charm.

Thank you very much.

**Comment by yvolk** [comment]
Glad to hear!
