### ISSUE TITLE
[Pump.io] Timeline shouldn't show messages, which I'm not subscribed to 

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#275]
Sometimes I notice that my Pump.io timeline has messages from unknown users. I figured out that these messages were connected with messages by users, whom I'm following, but I couldn't figure out how.
Recent ticket #274  made me understand that AndStatus takes from Pump.io timeline not only "items" of the Timeline, but also "notes", which these items are Replies to (they are embedded into the Replies - items of a Timeline)

Correct behavior would be to download such related messages (optionally!) , but mark them explicitly as "not subscribed" during parsing. So such messages will not appear in the Home Timeline, but will be present in Everything Timeline and in a Conversation view.

**Comment by moshpirit** [comment]
That can be happening because some of your contacts is sharing these motes. Try to sharing them, if I'm right you couldn't.

**Comment by jankusanagi** [comment]
@moshpirit
>That can be happening because some of your contacts is sharing these motes.
I don't really understand @yvolk's post, but yes, 99% probability that what he's seeing is shared messages by people he follows, from people he does not. That's normal, and the client just needs to show it properly.


> Try to sharing them, if I'm right you couldn't.
No, you can share whatever you see, the author doesn't matter.

**Comment by yvolk** [comment]
Done: message, to which subscribed message is a reply, is explicitly marked as not subscribed.

**Comment by yvolk** [comment]
The fix is available since v.29.00. Currently in the Open Beta Testing Channel: https://play.google.com/apps/testing/org.andstatus.app
