### ISSUE TITLE
I can't compile AS using AIDE

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#277]
I can't find the AndroidManifest.xml file and when I compile AS using any other file I get a lot of errors. What can I do?

**Comment by yvolk** [comment]
Just follow [the instruction](https://github.com/andstatus/andstatus/wiki/Building-AndStatus-from-Source-code-on-your-Android-device-using-AIDE-application) and it will allow you to build AndStatus without any code changes.
Regarding location of the AndroidManifest.xml file: its location changed according to the new project structure, imposed by [Android Studio](http://developer.android.com/tools/studio/index.html), and now it's deeper in the folders, inside "/app/src/main" folder.

**Comment by moshpirit** [comment]
I've got 515 errors opening the project in the "app" folder :(

**Comment by yvolk** [comment]
I'm testing this with AIDE v.3.1.3 on two devices.  0 errors. 
You may try to uninstall AIDE and/or  delete old repositories, 
and then repeat the process again starting from cloning AndStatus repository into new folder...

Make sure you have Internet connection during app building: AIDE downloads dependencies from Maven repository.

**Comment by moshpirit** [comment]
Mm that's weird, I downloaded the last version on Play Store using APK downloader (it's a website), (I'm on the phone, sorry for not putting the link) and the last version it's 3.0.3.

I cloned the repository before creating the issue :(

**Comment by yvolk** [comment]
Which version of Android does your device have?
Mine are 4.4.4 and 5.0

I see in the Browser: https://play.google.com/store/apps/details?id=com.aide.ui
3.1.3
Fixed: False compiler errors
...
3.0.3
Fixed: Debugging in Java projects

**Comment by moshpirit** [comment]
Android 4.3, I'll try to install this version by another way

**Comment by moshpirit** [comment]
Using the last version of AIDE (3.1.3) now, looks like it's fixed!! thanks! ;)

**Comment by yvolk** [comment]
FYI: [Current bug in AIDE](https://plus.google.com/u/0/103352957740632748919/posts/WzDqSYMTb8K)
AIDE doesn't recognize "com.android.support:appcompat-v7:22.2.1" compile dependency in build.gradle.  Only the older one: "com.android.support:appcompat-v7:22.2.0" :-(

Any other artifacts are ok, but this (admittedly special) dependency is somehow hardcoded in AIDE?!
Please make that latest (about three months old already...) dependency available in AIDE, otherwise I always have to manually change the version of dependency after pulling from a repo...

**Comment by marek22k** [comment]
> Just follow [the instruction](https://github.com/andstatus/andstatus/wiki/Building-AndStatus-from-Source-code-on-your-Android-device-using-AIDE-application) and it will allow you to build AndStatus without any code changes.

The wiki apparently no longer exists. Are there any current instructions on how to build the app?

**Comment by yvolk** [comment]
@marek22k No special instruction is needed. Just use AndroidStudio and "Open project" - the root folder of AndStatus source code repository.
Everything else is typical for any Android app.
