### ISSUE TITLE
Conversation view - Profile pictures are in the same column, instead of being indented

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#278]
Using the beta edition.

**Comment by yvolk** [comment]
Please try the latest commit. Post a screenshot, if you still have a problem.

**Comment by moshpirit** [comment]
Still happening, I'll post a screenshot as soon as possible

**Comment by moshpirit** [comment]
![screenshot_2015-07-12-23-43-04](https://cloud.githubusercontent.com/assets/7888062/8640192/5977d8a8-28df-11e5-93f0-a5b9aa45ee9c.png)

**Comment by yvolk** [comment]
Thank you, I noticed this also.
