### ISSUE TITLE
Layout of individual messages and dividers between them in a Timeline 

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#280]
In this conversation: https://loadaverage.org/conversation/7043295 we discussed, how to improve the layout of individual messages and dividers between them in a Timeline.

Looking at the latest repository build I see these points of improvement:
1. Text of a message should be visually closer to a Username above it. This may mean to figure out, how to fit "Favorited" star (or maybe change its shape?!)
2. Divider between messages is easily visible in a Conversation view, but almost invisible in a Timeline. 
3. Some messages produce blank space below a text. Maybe we can trim it somehow...

(A bug with avatar placement is discussed in #278  )

**Comment by aroquen** [comment]
@yvolk may I add a fourth point related to 1?

4. The sender text show have the same font size as the message text (right now the former is bold but smaller than the latter!). Rationale: bold text is used is to emphasize text, while reducing font size achieves the opposite. Doing the two things at a time is contradictory.

**Comment by yvolk** [comment]
@aroquen Actually, we don't refer to exact font size for a username and a message body. 
They are defined in https://github.com/andstatus/andstatus/blob/master/app/src/main/res/values/styles.xml as:
```
<item name="messageUsernameTextAppearance">?android:attr/textAppearanceSmall</item>
<item name="messageUsernameColor">?android:attr/textColorSecondary</item>

<item name="messageBodyTextAppearance">?android:attr/textAppearanceMedium</item>
<item name="messageBodyColor">?android:attr/textColorPrimaryNoDisable</item>
```
So do you think they both should have the same "text appearance" and color?

**Comment by yvolk** [comment]
@aroquen Actually, styles for an Author's username and a message body are defined here (using above mentioned "text appearances":
``` 
<style name="messageUsernameAppearance" parent="android:Widget.TextView">
    <item name="android:textAppearance">?attr/messageUsernameTextAppearance</item>
    <item name="android:textStyle">bold</item>
    <item name="android:textColor">?attr/messageUsernameColor</item>
</style>
<style name="messageBodyAppearance" parent="android:Widget.Holo.TextView">
    <item name="android:textAppearance">?attr/messageBodyTextAppearance</item>
    <item name="android:textStyle">normal</item>
    <item name="android:textColor">?attr/messageBodyColor</item>
    <item name="android:textColorLink">?attr/textColorLink</item>
</style>
```

**Comment by yvolk** [comment]
Regarding a "Favorited star".
Today I looked at the https://mobile.twitter.com and it came to me that the star can be moved from the right top to the right bottom of the message. Thus a Username will become close to a message text and adjacent messages will get some spacing between them.
?!

**Comment by aroquen** [comment]
1. I think the author's style should be bold and the font size the same as for the message text. And I would avoid italics.
2. The star at the bottom is a good idea!

**Comment by moshpirit** [comment]
TBH, my ideal for this kind of programs is the aesthetic of Twidere.

**Comment by yvolk** [comment]
@aroquen I agree on *Italics*. Let it be in a formatted text and not for the whole text box.

@moshpirit I don't think that mimicking some application's UI is a right way. But we can always look up good design elements. What exactly may be borrowed regarding _this_ issue/topic?

On the other hand, following a style/design of an application, which has 1000 times more users will help to get new users of our application?!

**Comment by moshpirit** [comment]
Well, since Twidere is free software and is doing it similar to Twitter, I don't see any problem about it, but the main reason about why Andstatus should use a friendly design is because it's more practical and beautiful, not because of the number of the users, they'll come later because we can use GNU social and pump.io accounts.

Here you listen to us more than the main developer of Twidere. That's something I really appreciate, so the day that Andstatus will get a really beautiful design, I'll recommend it instead of Twidere as a Twitter app.

**Comment by yvolk** [comment]
@moshpirit You touched an interesting topic: the goal of application's developers. 
I personally think that number of current users  (not total since application creation) is a proper indicator of its current "quality". Meaning not visual attractiveness only  ("esthetic"...), but features, accessibility  etc.
This is why we always have to think about the best next step. E.g. which feature should we add first? Or should we better fix some old bug/limitation first and postpone implementation of new features... ?

**Comment by moshpirit** [comment]
Good point, but I think that these things come together and you can introduce slowly this visual change :-)

**Comment by yvolk** [comment]
Done:
"Favorited star" moved to the bottom. 
Username is bold. 
No italics for a bottom line with additional info on a message.

**Comment by aroquen** [comment]
Thanks. That looks very good https://gnusocial.de/attachment/2555532

**Comment by moshpirit** [comment]
@aroquen what appearance configuration do you have? My icons are gray, not white (even with blue colour)

**Comment by aroquen** [comment]
@moshpirit ask @vinzv ;)

**Comment by vinzv** [comment]
@moshpirit That's the default configuration coming with current git status. Maybe it depends on your Android version and local UI theme?

**Comment by yvolk** [comment]
@moshpirit Icons for the Application bar ("Action bar") maybe need correction.  They were from KitKat icon pack, now we need the same for "Material design", I guess.
?!

**Comment by yvolk** [comment]
As I found today, there are other ways to set that "listDivider", see http://stackoverflow.com/questions/31222125/android-custom-theme-divider-color-for-listview
```
<style name="MyAppTheme" parent="Some.Base.Theme">
    <item name="android:listDivider">@color/my_divider_color</item>
    <item name="android:dividerHeight">4dp</item>
</style>
```
and http://stackoverflow.com/questions/4573208/how-can-i-get-the-default-divider
```
<View
  android:layout_width="match_parent"
  android:layout_height="wrap_content"
  android:background="?android:attr/listDivider" />
```
