### ISSUE TITLE
Image viewing and GNU Social

### ISSUE THREAD

**Issue by bernalau** [andstatus/andstatus#282]
Hello. 

I use andstatus with a Gnu Social Website private. 
When i upload an image with andstatus : no problem. 

Andstatus download all thread, but when i have a message with image, i have a link for image... 
The option display image is on. 
When i click on the link, i have a web page with the image... 

I have test with twitter : no problem...

Can you help me ?

**Comment by yvolk** [comment]
I remember we investigated the issue: Attachments (as a separate metadata with links to images... inside a message) are lost when messages are being sent between _certain_ (but not all) GNU Social instances.
So this is an old issue of GNU Social software.  
See this conversation: https://loadaverage.org/notice/4373193

**Comment by bernalau** [comment]
Hello. 

I have make different test. And the problem appear when we make a private gnu-social...
When the site is full open : no problem.

**Comment by bernalau** [comment]
Or when we publish in "private" or not public

The application work only with public message ... 

regards.

**Comment by aroquen** [comment]
I experience the same issue on a private site (we had a conversation on gs about it but I can't find it right now). We should send more detailed logs, so that this can be fixed.
