### ISSUE TITLE
Use without twitter account

### ISSUE THREAD

**Issue by igoralmeida** [andstatus/andstatus#284]
Would it be possible to use this as a twitter client without having to sign up to twitter? I don't need to post or receive messages or anything, just follow some public accounts.

**Comment by yvolk** [comment]
Reading the latest Twitter documentation on public timelines here: https://dev.twitter.com/web/embedded-timelines
I see "We recommend creating a new widget from the account responsible for your website (not your personal account) for easy discovery by your team and customization as your site changes", which means that even in order to access public timelines via API a User (site Admin in this case) needs to create a Twitter account.
Even if there is still a way to get a timeline without authentication, I think there is a big chance that this will be closed in the near future...

So from the first look I don't think it's worth an effort to implement this feature in AndStatus?!

**Comment by igoralmeida** [comment]
I took a look at dev.twitter.com and pretty much everything requires authentication, which is really unfortunate.

What about a throwaway account? How read-only could AndStatus be made? Would it be possible to 'follow' without actually leaking the association? It seems one could use https://dev.twitter.com/rest/reference/get/statuses/user_timeline for example.

**Comment by yvolk** [comment]
Yes, you are free to create a "throwaway account" in Twitter and use it in AndStatus. Actually, I do something like this for testing purposes. 
But it's wrong to hardcode such an account in AndStatus: it may be banned by Twitter plus it simply will have one download limit for all existing AndStatus instances. 

So,  create your own throwaway account.

**Comment by igoralmeida** [comment]
Oh no, that was never intended. However, I still want to understand what limitations would AndStatus have if all twitter ever got from my throwaway account was the authentication. I'll test and report back.

**Comment by morphtown** [comment]
Am 05.08.2015 um 19:50 schrieb Igor Almeida:
>
> Oh no, that was never intended. However, I still want to understand
> what limitations would AndStatus have if all twitter ever got from my
> throwaway account was the authentication. I'll test and report back.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andstatus/andstatus/issues/284#issuecomment-128089826>.
>

FYI ... https://github.com/sebsauvage/rss-bridge
With that you can follow any public twitter account without having one
on your own. The feed might be mirrored to a StatusNet/GNUsocial stream
(e.g. via feed2omb, brdcst, rss2sn, ...) so you can read it in your
AndStatus timeline.

**Comment by igoralmeida** [comment]
@morphtown that's very interesting, especially because there are a lot of other bridge options to enable, thanks!

On topic: while I have managed to connect to twitter using a throwaway account, I miss the functionality to see a particular public account's posts (without following them) without having to search for them all the time. Twidere has an interesting way of dealing with this: it lets the user create 'tabs' with specific content; in my case, the content was a user's tweets.

Does AndStatus have something similar?

**Comment by yvolk** [comment]
@igoralmeida Yes, there is "Messages by <Username>" context menu item, which opens "User timeline". That timeline may be updated (e.g. by "Swipe to refresh") just like any other timeline.

There are some restrictions on ability to retrieve the "User's timeline", imposed by different Social networks though...

**Comment by igoralmeida** [comment]
I see that, thanks. Still, do I always have to "find" some tweet by that user to be able to see their messages?

**Comment by yvolk** [comment]
First, we are discussing "Custom timeline filters" #161 
And second, there will be new "Users" view (read here: #224 ) - it's in the works already...

**Comment by igoralmeida** [comment]
Right, thanks!
