### ISSUE TITLE
Action bar font color for Light theme

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#289]
The Action bar configuration for the white theme still uses the black font and grey icons that we used to use before Material design arrived.

**Comment by yvolk** [comment]
1. Font color: es, I noticed this also. Maybe this will help: http://stackoverflow.com/questions/26870698/change-actionbar-title-text-color-using-light-darkactionbar-theme-in-appcompat-2
2. Regarding icons, there is already a ticket on this: #283

**Comment by DoctorJellyface** [comment]
Can't a different colour be set for the action bar?

**Comment by yvolk** [comment]
@DoctorJellyface Regarding font color: there is still a question, which color should be set. Do we need a new setting "Action bar font color" ?!
Regarding Action Bar background color: we do have such setting already: "Action bar color" option, having 6 colors from [Material design color palettes](http://www.google.ru/design/spec/style/color.html).

**Comment by DoctorJellyface** [comment]
I meant the font, sorry. And I also meant if it's _possible_ to change it, so that it could automatically do it based on the theme.

**Comment by yvolk** [comment]
Yes, Action bar font color already changes based on a Theme (this is done on Android level, AndStatus doesn't do anything here...)
The font color is Black for a Light theme and White for a Dark theme, as you can see here: https://github.com/andstatus/andstatus/wiki

**Comment by DoctorJellyface** [comment]
But can't the font be set **independently** for the action bar, so that it could be white in a light theme and dark in a dark theme?

**Comment by yvolk** [comment]
Maybe, I will try to set the font color independently. Current behaviour is provided by Android core / Support library.

**Comment by DoctorJellyface** [comment]
Thanks.

**Comment by yvolk** [comment]
Here is how to change the Action bar text/background color: http://stackoverflow.com/questions/5861661/actionbar-text-color
It looks like we will be able to choose between black or white backgrounds...

This setting should be separated from existing "Action bar color".

**Comment by DoctorJellyface** [comment]
> This setting should be separated from existing "Action bar color".

Sure, it's your app.

**Comment by PanderMusubi** [comment]
Most other apps have white text on blue action bar in light theme. Please try to support this in the app of by using the Android core in another way.

**Comment by yvolk** [comment]
Implemented in v.25.00, which is published at the Beta testing channel: https://play.google.com/apps/testing/org.andstatus.app

1. Added "Action bar text and icon color" option to the "Appearance" section of AndStatus settings. It has two values: "White" (default) and "Black". This allows to have white text of Action Bar title not only for Dark theme, but for Light theme also. #289
2. Added the third, "Accent" color to the definition of each "Action bar background color".

![whitefontcolorforactionbartextlighttheme](https://cloud.githubusercontent.com/assets/207716/14404248/d959e276-fe79-11e5-866a-44f6dcd14f64.png)
