### ISSUE TITLE
Writing a new post should have its own UI

### ISSUE THREAD

**Issue by Dragnucs** [andstatus/andstatus#290]
Writing a new post, the way it is now, on the bottom of the current window is confusing and less practical.

A better way is to have a new separate window or pop-up that that has only what is necessary for new posts. I.e. a text box, a button to attach files, a mini thumb preview of attachment, a send button, an eventual post if the user is writing a reply and the send button.

**Comment by yvolk** [comment]
@Dragnucs I agree that some users may like a separate window more, but I don't think that this is better for everybody. E.g. I often lookup other posts while composing new message in a bottom of a screen...

Actually what you want differs from what is now in only one substantial thing: "a mini thumb preview of attachment". Is this what you really asks?

**Comment by Dragnucs** [comment]
@yvolk Why not a setting then to please everyone.

A usability rule imply that there should be a new window, page or popup for adding a new entry or editing an existing one. We should not have add/edit in the main window, nor in place edit. The only exception to this is tables.

**Comment by yvolk** [comment]
@Dragnucs "To please everyone" would be to add an option to show an image thumbnail?!

Regarding the "usability rule", which dictates new window... I don't agree with this rule. Even for a smartphone. Because at least some users really need, while composing an image:
1. Lookup, read other related posts, 
2. Maybe even copy text of that posts and/or author IDs (to include into the new post in order to refer to other people...).
This is _very_ useful. And I read at least one user's opinion that this feature is good...

**Comment by Dragnucs** [comment]
@yvolk I agree 100% that the user should be able to see the dent he is replying to. As I said in my initial post, if the user is writing a reply, he should have it visible in the composing window. Maybe even a tree view for better context.

The option would let the user chose if he wants a separate composition window or not.

**Comment by yvolk** [comment]
If conversation is real, seeing only _one_ post (to which you technically reply) is not enough. This means exactly that while composing a User needs to be able to see several other posts. Currently AndStatus even allows searching for other posts while preserving the draft message...

I still don't get, what is so different for you if a composition window is "separate" or not? If a device screen is small and a message is large then the "Message editor" will take the whole screen anyway?! (except an Action Bar...)

**Comment by Dragnucs** [comment]
It is messy. If you click somewhere, You may lose everything. It is 
difficult to type long dents and when there is a lot of text, 
distinguishing between your text and other dents becomes difficult. 
Having a separate window or pop up will make Andstatus prettier on one 
hand, and more userfriendly and usable on the other. Just meditate it. 
There is a reasying most of the applications operate that way.

**Comment by yvolk** [comment]
"If you click somewhere, You may lose everything" - No, you may even go to a Home screen and re-launch AndStatus. You draft message will be preserved. Try it!

But I agree that if you don't need other posts to write yours, you will prefer to hide a timeline completely. This may be implemented like switching the Message Editor to a "full screen", if necessary... with ability to restore its size to what it is now.

**Comment by moshpirit** [comment]
Related: #167

**Comment by Dragnucs** [comment]
I think I didn't express myself well.

Here are some relevant screenshots:
- [Talon](https://lh3.ggpht.com/FG5N8XihHr6XZq3WZu7iL4eBbPKxCJcnIXocs6ea2XKiVhEcHOncJaIqeglmzQ_qOg=h900) with mini thumbnails
- [Twider](https://lh3.googleusercontent.com/N9LsaQzEEdVCGXwzRG_uhAjkM7wcTIwEVE-PTZnWwBDsZHs3JPz7-2ErJ7CkOZT05A=h900) with relevant actions buttons, position info, etc..
- [Now for reddit](https://lh6.ggpht.com/aChffm2KV3sTPiBXwbkKgTZ8dZ5-YyKYCHpYZwZtavQp3fiYchlRS_jDYMNI85qEYCk=h900) with reply context.
- [AndStatus](https://lh3.googleusercontent.com/1eSfz5fApONbwSflU2W4yL-4OQxd_A6X5iZK9kxXO_3P7M3WSpTHJkmBFjJO292x8A=h900) with compose box playing hide and seek and providing neither context nor relevant actions buttons.

A stupid mock-up explaining my point of view. *The features shown are not exhaustive.*
![stupid-mockup](https://cloud.githubusercontent.com/assets/6125772/9341637/0106af14-45ef-11e5-8cf2-7c5cfab3fad7.png)

**Comment by yvolk** [comment]
What main differences from today I see:
1. Action buttons are not at a top, as usually in native Android applications, but somewhere in the middle of the screen...
2. Related message(s) (i.e. the "context" of this message...) are below, not above the Message Editor. Whether they can be scrolled (as in AndStatus now) or not (so only one message may be seen there) is not that different at this level of discussion...
3. Text box for a new message is tall even for an empty message.
4. Thumbnails of three attached images are shown (now we can attach only one image).

**Comment by Dragnucs** [comment]
I am not discussing any of these four points. Displaying related massages above, below, to the left or right is up to you. You arrange the layout however you see fit and present only the information that can be shown. I am just proposing two better conceptual ways to enhance user experience.

Today, composing a new dent is confusing. I am posting this in the light of a [message](http://oracle.skilledtests.com/notice/1172793) by [Temporary Marjolein](Temporary Marjolein) that was confused and did not see the **attach** button even though it was present.

It is a better idea to show only the relevant messages to what you are going to reply to but not your whole time line. Showing a preview of the attachment where applicable is must as it avoids us terrible mistakes. This is a screenshot of AndStatus where all I did was `long-press > reply > type a message`. It is frustrating to rectify something from what my friend said as the message I see is not the one I am replying to. I need to scroll through lots of unrelated message.
<img src="https://cloud.githubusercontent.com/assets/6125772/9342591/a797438e-45f4-11e5-82db-969048d0f1b8.png" width=40%>

This actual way does not help check if one is replying to the intended message and not something else. Even the separation between the compose area and timeline is unclear that way.

I hope now I expressed myself better.

**Comment by yvolk** [comment]
Thank, now I understand your proposal much better.

1. Regarding a case with "Attach" button - it is not relevant here, because the "Attach" button really was _not_ present on an Action Bar :-)   (see #288 )

2. I agree that for a Reply we really need to show the one message we are replying to.

3. A way to preview an attached image is also needed.

**Comment by yvolk** [comment]
@Dragnucs @moshpirit @zyqbx
See how it looks now. I only want to move "Send" button to the Action bar. For consistency. 
![screenshot_2015-09-24-06-27-35](https://cloud.githubusercontent.com/assets/207716/10064880/69edc5ea-6286-11e5-81ab-5cbde861e23f.png)

**Comment by moshpirit** [comment]
I think that this change can be very confusing. What you could do is to rewrite the drawer and doing something more similar to Twidere's one

**Comment by yvolk** [comment]
@moshpirit Please explain, what exactly part do you think can be confusing? 
Please checkout 291-Unsent-messages-and-attachments branch of this repository (AIDE can do this also...) to try these new features in action.

**Comment by moshpirit** [comment]
You know, writing in the bottom side of the screen and send it using the top. Sorry I can't use AIDE right now, my micro SD stop working a few weeks ago after I uninstall it so I have to install it again

**Comment by yvolk** [comment]
@moshpirit I understand you, but these points caused me to do this:
1. All other actions / buttons,  related to message editing, are at the top already: Attach image, Save draft, Discard. 
2. As we're following Google guidelines  (Material Design etc.) looking at how Google does this helps also:  Send button is at Action bar in GMail, next to Attach action. So I think millions of potential users expect the same from other applications.

**Comment by yvolk** [comment]
And
3. Actually, editing occurs close to the top of the screen, because soft keyboard takes the lower part of the screen.

**Comment by yvolk** [comment]
And this is how Message Editor looks now. 
![scr_message_editor-v19](https://cloud.githubusercontent.com/assets/207716/10094127/a9ec97fa-6364-11e5-8558-74da3c0dcdfd.png)

**Comment by zyqbx** [comment]
I like it (as long as the cancel message button is still on the action bar under the "..."; I find myself using that a lot). It makes the text editing area wider, which is nice on my phone.

**Comment by yvolk** [comment]
@zyqbx There are two related actions hidden under the overflow button ( "..."):
"Save draft"  (can be edited later)
"Discard" (erased forever)
Both actions hide the Message Editor.

**Comment by yvolk** [comment]
Released in v.19
