### ISSUE TITLE
Support basic facebook reading/posting

### ISSUE THREAD

**Issue by singpolyma** [andstatus/andstatus#292]
Similar to the twitter support.

**Comment by annando** [comment]
The facebook API doesn't allow this. In April of this year they restricted access. You now have to gain a permission to use these parts of the API - and they clearly stated that they won't give it to anyone.

**Comment by singpolyma** [comment]
Which parts? Reading status updates from friends?

**Comment by singpolyma** [comment]
Hmm, ok, I've found the read_stream issue. Facebook getting even worse than I thought :P

**Comment by moshpirit** [comment]
Someone already asked for Friendica support, if AS get it, would be able to read your TL.  
Anyway, you can also use a RSS app.

**Comment by annando** [comment]
AndStatus is working with Friendica. But Friendica has the same problems with Facebook, so there is no way. Concerning RSS: Facebook has shut down the RSS feeds. They want to force the users into their applications.

**Comment by moshpirit** [comment]
Lol I don't see any reason to use it then. Every corporation is getting worse. \*Sigh*

**Comment by yvolk** [comment]
So I'm closing this till the time Facebook rethinks its strategy regarding collaboration with other social networks and services.
