### ISSUE TITLE
Check media size before post

### ISSUE THREAD

**Issue by zyqbx** [andstatus/andstatus#293]
Occasionally, when I try to post to twitter with media, it fails with a 403 Forbidden response.

It turns out that the file size limit for `POST statuses/update_with_media` is 3MB. This took me months to track down, because most of the pics I take are under that limit,

Would it be possible to check the media file size before attempting to send a message? Maybe put up a toast or something if the file is too big? It was incredibly frustrating not knowing why my tweets failed, plus it wastes data.

**Comment by yvolk** [comment]
I could easily add a file size (in Kb) to a Message Editor
so you will see e.g. (with media 3000kb) ?!

**Comment by zyqbx** [comment]
That would work! It would be an easy fix, and it wouldn't matter what platform the user is sending the message to. I like it.

**Comment by yvolk** [comment]
I did this already. Will add image size in pixels also and commit to the repository. 
![screenshot_2015-09-23-09-10-31](https://cloud.githubusercontent.com/assets/207716/10038767/f1ea83de-61d2-11e5-8796-2966bdc4fea9.png)

**Comment by zyqbx** [comment]
Very nice. Thank you!

**Comment by yvolk** [comment]
Released in v.19, 
Please see an image in this comment: https://github.com/andstatus/andstatus/issues/290#issuecomment-143137844
