### ISSUE TITLE
Why I don't see new posts in a Timeline? AndStatus is not syncing anymore

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#295]
We receive many similar questions, and this is why I decided to start this thread to collect all advices on how to check, diagnose and fix this.

Some tips on what to do when your timeline is not synced:
1. Normally AndStatus should download new updates automatically, using Android built-in Syncing feature. So you wouldn't need to press Reload at all. Just open AndStatus and read the latest updates. 
   Maybe you turned that Android sync off? Go to Android system Settings -> Accounts and Sync (or something like this...) and check if sync is turned on for "AndStatus" accounts. There you will also see, when last sync was done successfully for each account you added in AndStatus.
   ![screenshot_20160710-073012](https://cloud.githubusercontent.com/assets/207716/16711682/7cfd882c-4670-11e6-8659-d9eb7a05fbed.png)
2. Does manual _Reload_ work? Please "Swipe to refresh" or press "Reload" on an Action bar. If you still don't see new messages, please check "Commands in a queue" in the menu.
3. Default period of automatic synchronisation (for all accounts) may be checked and changed in AndStatus Settings -> Syncing -> Sync frequency. See other settings, related to Syncing there also... 
   Each account may have its own syncing frequency, so if the Default syncing frequency is OK, you may go to AndStatus settings -> Manage Accounts -> select an account
4. If you don't see new posts of some account (in a timeline of that account) go to AndStatus Settings -> Manage existing accounts -> select that account from a list. Account settings window will be opened. The window shows you: \* if automatic sync is enabled, \* when last sync occurred and \* if the account has it's custom sync frequency set. Press "Reverify credentials" button to check and fix authentication-related problems. See this related issue #242.
   ![screenshot_20160710-074340](https://cloud.githubusercontent.com/assets/207716/16711702/2ce8c70a-4672-11e6-9daa-5a947923d9bf.png)
5. Messages  that you posted, but which appeared not sent,  may be found in "Outbox" and "Drafts" timelines. You can resend them! If after re-sending and syncing a message is still marked as "(unsent)", go to "Commands in a Queue" and find out error report on that exact message. That error report on one message can be Shared e.g. to email or to AndStatus itself in order to receive help from your peers... 
6. Since v.27 "Manage timelines" table is a great help in syncing problems investigation. It shows information about syncing, including: number of successful syncs and time of the last successful sync; number of failed syncs and time and an error message of the last failure, for _each_ timeline. See the example page below.
   ![screenshot_20160708-191149](https://cloud.githubusercontent.com/assets/207716/16693988/8d43cd30-4540-11e6-9b33-15f78bc56c33.png)
7. Missed syncing in the background may be caused by the Android Doze and Standby modes. Read e.g. here tip on how to tweak this: https://www.howtogeek.com/242563/how-androids-doze-improves-your-battery-life-and-how-to-tweak-it/

**Comment by keverets** [comment]
This appears to be the most relevant existing issue for the problem I'm experiencing, but if it's misplaced please let me know.

I'm seeing issues with synchronizing on a Combined timeline where it doesn't appear to update the list.

However, if I open the side menu, select the current account (eg, Quitter.is) then pick a different account (eg, Pump.io), then the list immediately updates and renumbers with often a large number of posts above the top of the currently visible list.

So, it seems as though in this particular case, there has already been background syncing of the individual timelines but there's a missing step that exposes/triggers updates to the Combined timeline.

I'm currently using 31.03 as built by F-Droid, and have noticed this pattern over the last few f-droid releases (at least since 30.00 if not farther back).

**Comment by yvolk** [comment]
@keverets I agree with your observations: sometimes AndStatus don't "refresh" a Timeline, when new messages have been downloaded to the local cache in the background.
The simplest way to make sure that you see the latest data is to select "Refresh from cache" item in the Navigation Drawer.

Usually AndStatus does update a Timeline on loading new messages, but sometimes it intentionally ignores such events: this is done in order to avoid endless refresh and low responsiveness of the application. Obviously I need to improve this Timeline refreshing logic, and another ticket should be created for that.

**Comment by yvolk** [comment]
In AndStatus v.36 Fixed (at least partially) a problem, related to [Doze mode](https://developer.android.com/training/monitoring-device-state/doze-standby.html) on some devices, when automatic background syncing doesn't occur for a long time. Despite Android specifications, I noticed that e.g. my new Lenovo tablet doesn't wake up for a "maintenance window" and Android system initiated background syncing could never occur. So additional timer introduced to check for missed sync events and initiate syncing if necessary.
