### ISSUE TITLE
The Message Editor is hidden by the keyboard when I reply to a post 

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#296]
Just happened on GNU social with this post: https://quitter.es/notice/573576

**Comment by yvolk** [comment]
I don't see this problem, see a screenshot. 
Please provide your screenshot and Android version. 
![screenshot_2015-09-29-19-55-25](https://cloud.githubusercontent.com/assets/207716/10171765/60eec9b4-66e4-11e5-9295-2c9c2542c1f5.png)

**Comment by moshpirit** [comment]
Android 4.3

![screenshot_2015-09-29-21-16-40](https://cloud.githubusercontent.com/assets/7888062/10180109/d3e96890-670a-11e5-8bf1-4495334d0baa.png)

This morning the Message editor was totally hidden by the keyboard and I couldn't see what I was writing :\

**Comment by yvolk** [comment]
Sometimes I see this effect also. I could solve the problem by changing orientation of my device: rotated  and then returned back.

Anyway, we need to search for a more reliable solution.

**Comment by moshpirit** [comment]
Oh, OK, next time it occurred I'll do it,  thanks

**Comment by yvolk** [comment]
This page has advices to try: http://stackoverflow.com/questions/3295672/android-soft-keyboard-covers-edittext-field

**Comment by yvolk** [comment]
I tried different options, and it seems that the best option is to place the Message Editor above the Timeline, not below it, as it was before.
Thus, the change is in adding ", 0" to the code...
```
layoutParent.addView(mEditorView, 0);
```

**Comment by yvolk** [comment]
...but seeing the Message editor at a top of the screen looks... unusual :-)

**Comment by yvolk** [comment]
Now I think the problem is solved, please test v.19.2 (currently available via Beta testing channel, please opt in at https://play.google.com/apps/testing/org.andstatus.app )
I switched to RelativeLayout and placed the Message Editor at a bottom of the screen, closer (by z axis) than a Timeline.
