### ISSUE TITLE
Message editor deletes what I'm writing 

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#298]
OK, I finally got to reply a note, but I can't write almost anything, the text go every time (almost at every sentence I write, the message editor erase it and make me start over.

**Comment by yvolk** [comment]
I need to reproduce this or at least understand, how this happens on your device. Please set logging to Verbose, reproduce the problem and send me logs, created during the test.
Please use different text for each attempt,  e.g. different beginning. E.g. "Test 001...", "Test 002...", so these words could be easily found in logs.

**Comment by yvolk** [comment]
I see that something is wrong with current implementation. Thinking, how to fix this...

**Comment by moshpirit** [comment]
Good, I haven't seen the bug again for now but I did with the other bug so I'll upload a screenshot on the computer

**Comment by yvolk** [comment]
@gallux89@quitter.se @fanta@gnusocial.net @deavmi@quitter.se @kaimi@status.kaimi.cc @gianf@quitter.se 
#AndStatus v.19.1 is available at the Beta testing channel, please opt in here: https://play.google.com/apps/testing/org.andstatus.app
In this release I'm fixing a bug with Message Editor, which sometimes prevents from sharing a message, sometimes causes loss of last edits to a message draft.

**Comment by yvolk** [comment]
AndStatus v.19.2 is available at the Beta testing channel, please opt in here: https://play.google.com/apps/testing/org.andstatus.app
In this release I'm fixing a bug with Message Editor, which sometimes prevents from sharing a message, sometimes causes loss of last edits to a message draft.

**Comment by yvolk** [comment]
Supposedly fixed in v.20.4
