### ISSUE TITLE
Editing of online posts

### ISSUE THREAD

**Issue by deavmi** [andstatus/andstatus#299]
If a post has already been made then surely you must not be able to edit it again?

**Comment by yvolk** [comment]
Not necessarily. E.g. request #221 "Edit message [Pump.io]" explicitly asks for this.
So this depends on a concrete Social network (both on its capability and configuration).
AFAIK Twitter and GNU Social don't support editing posts.

**Comment by deavmi** [comment]
Oh okay. :)
