### ISSUE TITLE
Colouring the navigation bar according to a theme?

### ISSUE THREAD

**Issue by DoctorJellyface** [andstatus/andstatus#302]
This would make AndStatus so much nicer. It would also make dark themes mkre usable for me since my navigation bar is white by default.

**Comment by yvolk** [comment]
We do have the setting: "Action bar color" option, having 6 colors from [Material design color palettes](http://www.google.ru/design/spec/style/color.html).
For Android v.5+ it changes both Status bar and Action Bar
So only "Navigation bar" color is not changed (see [Using Material Theme](https://developer.android.com/training/material/theme.html))

So it looks like we need to add another option to change navigationBarColor ?! (E.g. as suggested [here](http://stackoverflow.com/questions/27839105/android-lollipop-change-navigation-bar-color))?!

**Comment by DoctorJellyface** [comment]
I do have Android 5 and it doesn't change it. And we don't need to add another option, if it's supposed to do it automatically that's fine.

**Comment by yvolk** [comment]
1. Please set "Action bar color" using that option and then provide a screenshot of a timeline view. On my devices this looks like screenshots at https://github.com/andstatus/andstatus/wiki

2. How do I know, which color "Navigation bar" should have, if not from another AndStatus setting?

**Comment by DoctorJellyface** [comment]
OK, my fault regarding the status bar, I apologize. I left it set to device default and it doesn't change there. I'll change the title accordingly.

But the navigation bar is **always white**, making it a lot harder on the eyes. Could you change it to black, so everyone would have the same look as you have on your device? Or maybe have it light in a light theme, but dark in a dark theme? Thanks.

**Comment by yvolk** [comment]
As different people may have different view on a proper color of the Navigation bar, I will have to add a separate setting for this. This setting will work starting from Android Lollipop (API v.21):
Title: Navigation bar color. 
List of values: 
* Device default  (i.e. do nothing.  As it is now )
* The same as Action bar color
* White
* Black

I'm not sure how to set text color of the Navigation bar...

**Comment by DoctorJellyface** [comment]
Afaik the text (or icons) are coloured automatically. I'll gladly test though.

**Comment by yvolk** [comment]
@DoctorJellyface Text and icons color on the Action Bar is now configurable, white by default. See #289 - It's in Beta now!

**Comment by yvolk** [comment]
Done: Navigation bar color is set to the same color as the  Action Bar Background Color.
Released in v.25.02+
```
        <item name="android:navigationBarColor">?actionBarColor</item>
```
![scr-timeline-light-v25](https://cloud.githubusercontent.com/assets/207716/14408833/1890e6fe-ff0d-11e5-936a-24583f2cb7d9.png)
