### ISSUE TITLE
Enter button is not shown on my Android 5.0.2 device

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#306]
When I write a new message I can't press the Enter button, I don't know why.

AS v.19.5

**Comment by yvolk** [comment]
Please try v.20.4 
Any screenshot?

**Comment by moshpirit** [comment]
No, in v. 20.5 is not shown, instead of the Enter button I see the emojis one

**Comment by yvolk** [comment]
Please attach a screenshot

**Comment by moshpirit** [comment]
Here's one: https://my.owndrive.com/index.php/s/vDrzW5LpZX5ev3w

**Comment by yvolk** [comment]
I do see Enter button on stock keyboards on my 4.4.4 and 5.1 devices... Will look in Emulator. 
Do you think some recent changes caused this?

Could you try some other Keyboard app or tweak this Keyboard app somehow.

**Comment by moshpirit** [comment]
This is the default AOSP keyboard of my smartphone :\

**Comment by yvolk** [comment]
I searched for this and it appears that the problem is present in different applications. Please try solutions e.g. from here: http://android.stackexchange.com/questions/44443/how-to-get-the-enter-return-key-in-messaging-mms-app-jelly-bean

**Comment by vinzv** [comment]
FYI: I had the same problem with Google (not AOSP!) keyboard on 4.4.4. Pressing shift did solve it asa workaround.
