### ISSUE TITLE
"Users of message" Context menu item

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#309]
Based on this wide and conceptual discussion - #224 - we are creating the new Message context menu Item: "Users of message".

Clicking on this item opens the new View (Android activity): Users. This "Users" view shows a list of Users, related to this message, including:
1. Author
2. Sender (if not the same as an Author)
3. Replied to User (an Author of the message, to which this message is a reply). If any.
4. Mentioned users (not repeating all above)

**Comment by yvolk** [comment]
"Users of Message" feature is starting to work, although there is no context menu for Users yet.

**Comment by yvolk** [comment]
Implemented in v.21

**Comment by vinzv** [comment]
Can we have post count, follower count and following count there somehow?

**Comment by yvolk** [comment]
@vinzv I created #320 for this.
