### ISSUE TITLE
Restrict maximum number of messages,  shown in a Timeline at a time 

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#313]
I think that lack of a limit on a maximum number of messages,  shown in a Timeline at a time, is a major cause of performance degradation for users,  who receive thousands of new messages daily.
See #310 also.

As was decided many years ago, when a User opens a timeline,  the timeline opens at the same place it was viewed before. It's not bad by itself, but together with these old messages ALL newer messages are shown. A few hundreds of messages are not a problem, but showing a thousand or even more can freeze the application for a long time. 
We should make the "view page" movable, so only closest "page of messages" is shown, not all since the time of the last viewed message. 
I think that a page size of 200 messages will be good enough. 

What is not trivial: how to load new messages from a database (and drop unneeded messages) intelligently...

**Comment by annando** [comment]
I really would appreciate this feature.

**Comment by yvolk** [comment]
This feature already works. Currently AndStatus loads not more than 100 messages (a "page") at a time and keeps in its memory not more than 5 pages. When a User scrolls in any direction, farther pages are discarded.

**Comment by yvolk** [comment]
v.20.0. Published to the Open Beta testing channel, please opt in here: https://play.google.com/apps/testing/org.andstatus.app at test it!
