### ISSUE TITLE
Add User's attributes to a User List: counts of Posts, Friends, Followers, Favorites.

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#320]
Each User's item in a User List will show additional attributes (if available for the Social Network):
Counts of:
Posts
Friends
Followers
Favorites

Add also:
Location (string)
Banner URL ( GNU Social has both "profile_banner_url" and "cover_photo", we will stick to Banner URL for now...)

**Comment by vinzv** [comment]
I made a mockup for that, two different color variants:
![user-profile-1](https://cloud.githubusercontent.com/assets/74432/12092954/842dcea8-b300-11e5-8be1-9cc90ba894a8.png)
![user-profile-2](https://cloud.githubusercontent.com/assets/74432/12092953/842d336c-b300-11e5-8bea-7e8ec187064e.png)

**Comment by yvolk** [comment]
@vinzv Thank you, I thought about something like this: compact layout (with pop-up icon descriptions...)
I hope to find icons here: https://design.google.com/resources/

**Comment by vinzv** [comment]
Okay, that's possible too, but maybe that's an unnecessary additional click?

The icons I used are from icomoon.io from the Material icon set. So they should be available in the URL you gave as well.

Am 4. Januar 2016 17:36:18 MEZ, schrieb Yuri Volkov <notifications@github.com>:

**Comment by yvolk** [comment]
@vinzv No, I didn't mean additional click to see these numbers, but rather a long tap to see descriptions of icons. Otherwise it's unclear, what each icon mean.

**Comment by vinzv** [comment]
@yvolk That's definitely a good point!

**Comment by yvolk** [comment]
It works. I'm releasing v.23.00 beta 
![screenshot_2015-11-23-08-46-31](https://cloud.githubusercontent.com/assets/207716/13473606/1bb9d116-e0cb-11e5-9866-70381127eca7.png)

**Comment by yvolk** [comment]
Implemented in v.23.00
