### ISSUE TITLE
Hide messages based on keywords or exact phrases

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#321]
In #279 we created a filter "Hide messages based on keywords", so this new filter is an enhancement of the existing filter.

Description:
In order to define a phrase for a filter, put it inside double quotes.

**Comment by vinzv** [comment]
Just tried it, works fine! There is only one thing: I get notifications for filtered posts which is a bit irritating when you click on the notebook notification and don't see anything new in mentions timeline afterwards.

**Comment by yvolk** [comment]
@vinzv  I see. Thank you for noticing.
This is because these filtered messages are not completely "blocked", they are still stored...
For now I will apply the same filter before notification.

**Comment by vinzv** [comment]
I wouldn't block them either to avoid inconveniences. Hiding
notifications is fair enough.

**Comment by yvolk** [comment]
Implemented in v.22
