### ISSUE TITLE
Scrollbar edge too big

### ISSUE THREAD

**Issue by asterismo** [andstatus/andstatus#323]
Hi, just wanted to share that the scrollbar edge is quite big, many times i'm passing down posts and accidentally y trigger the scrollbar and everything goes to hell, and i loose where i was. It happens me a lot, so i ended up using my left hand to navigate through posts. Maybe the edge treshold is too big or something. Cheers!

**Comment by yvolk** [comment]
I think this is because of the "Fast Scroll Thumb" that is being turned on frequently. I want to get rid of this "thumb" and replace it with a dedicated "Go to the Top" button, see https://github.com/andstatus/andstatus/issues/255

**Comment by yvolk** [comment]
I removed the Fast Scroll Thumb - You may check the latest commit...

**Comment by yvolk** [comment]
v.20.0. Published to the Open Beta testing channel, please opt in here: https://play.google.com/apps/testing/org.andstatus.app at test it!

**Comment by asterismo** [comment]
everything is running fine now, cheers!

**Comment by yvolk** [comment]
Glad ti hear. Thank you for your help in realizing, what should be changed,
