### ISSUE TITLE
Automatically resize an image on attachment to a composed message

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#324]
Add a new option to AndStatus Settings -> Attachments section: "Resize image on attachment", which prompts a User: 
"Define a length of the longest image side or leave blank for no resizing"

**Comment by vinzv** [comment]
Good idea, but I'd prefer choosing by fire size. Maybe "small", " medium" and "original size" would be better?

**Comment by yvolk** [comment]
@vinzv I'm afraid "small" and "medium" are too vague and too few choices... We better explain to a User, what the option does and allow him to decide on exact size?!

**Comment by vinzv** [comment]
@yvolk You're right, so maybe give choices for file sizes? 1MB, 2MB, ...

**Comment by yvolk** [comment]
There is an Open Source application that allows to do this:
https://f-droid.org/repository/browse/?fdfilter=send+reduced&fdid=mobi.omegacentauri.SendReduced

**Comment by yvolk** [comment]
@colegota@quitter.es Thank you for the tip. 
 "Send Reduced" open source application. available via F-Droid, can be used to reduce size of attached images on the fly. 
Even if you attach an image to your draft message, you can select "Get Reduced Photo" from a list of sources. As I did in this post.
As I see,  the "Send Reduced" application is not that simple,  including its settings. So maybe there is no real point to implement the same feature inside AndStatus?!

**Comment by yvolk** [comment]
"Get Reduced Photo" of "Send Reduced" in the list of sources for attachment to AndStatus' post. 
@escobrice@quitter.es @colegota@quitter.es
-- 
andstatus@loadaverage.org
 URL: https://loadaverage.org/notice/

**Comment by yvolk** [comment]
So pals, you already _have_ this feature. It only happens to be packaged separately from AndStatus. 
I'm not joking. Please install ”Send Reduced" and try to use it with AndStatus.

**Comment by efelon** [comment]
I'm on LineageOS 14.1 (Android 7.1.2) with latest AndStatus (v.36v09). The method you described here doesn't work any more. If I share from the Gallery via "Send Reduced" AndStatus shows attachment 0x0, 0k. Tested with jpg images of different sizes and sources (camera/download).

Btw. i came originally from this problem I also have: #397  which led me to the idea trying to reduce the size to see if that is the problem. Also tested with different image sizes.

**Comment by yvolk** [comment]
@efelon I just tested the latest Send Reduced Free with AndStatus v.36.09 and it works, see https://loadaverage.org/notice/12027532
I installed Send Reduced Free from Google Play and shared a photo from a Gallery to it.
Android 7.1

**Comment by yvolk** [comment]
Could you check if the problem is with some specific images?!
If yes, please post such an image here.
