### ISSUE TITLE
Tags without codename

### ISSUE THREAD

**Issue by krt16s** [andstatus/andstatus#326]
Tags with codenames break (or make it harder) for automation. Would it be possible to do tags without them? Or having both tags present?

**Comment by yvolk** [comment]
Hi Boris!
Actually I thought about how to tell e.g. to f-droid that some tag means Beta version, some means Production and some tags are just for memory...
Interesting thing here is that "Production" tag may appear on some old Beta tag...
?!

**Comment by krt16s** [comment]
We can use regex on tags -- either to whitelist (e.g. versionname-release or versionname-fdroid) or to ignore (like versionname-beta), that shouldn't be hard. As long as the recognized tag has a versioncode that is higher than the last realease, it should pick that up so we are aware of a new release.

The tricky part is automated updates. Since our update logic is rather dumb, we have to re-construct the tag name from a version: If we catch a tag, it stores the versionname and versioncode. This two bits of information are used to generate the tagname. There is no way for us to generate things like codenames :/

**Comment by yvolk** [comment]
1.In terms of Android, our tags contain "version name" only. "Version code" is in a manifest only... Or you mean some other "version code"?

2. I don't get,  why do you need to reconstruct tagname from a version? I would do this one way only: extract version from each  (filtered, as you described...) tag and compare versions in order to determine, if update is needed?!

**Comment by krt16s** [comment]
1. I mean the versioncode in the manifest, but my wording was weird. The versioncode is what is used to check if its an update or not. I just wanted to say "Even tags that meet the regex will be ignored, if the checkout does not contain an updated versioncode".

2. The updatecheck is cumbersome, indeed. The re-construction is necessary, because checking for new versions and applying updates is done in different stages and the information which tag was used is thrown away. I agree, this is not a good solution, but that is what our system is right now.

**Comment by yvolk** [comment]
So far I thought that f-droid understands _every_ tag as a release mark, and so:
1. Avoided to create tags for beta releases (inconvenient...)
2. Didn't care much about tags format (as _any_ tag was accepted)

As I hope now we can get some mutual understanding thanks to this discussion, I would like from now on to create versioned tags as:
\<MAJOR>.\<MINOR>[ -release || \<other suffixes>]

So please treat as release only tags with "-release" suffix, e.g.:

This is a release tag:
22.4-release

These are some other tags, please ignore them and don't create automated releases:
22.4
22.4-beta

?!

**Comment by krt16s** [comment]
Looks good, thanks for the quick response and working around fdroids limitations for now:

````
INFO: Processing org.andstatus.app...
INFO: ...updating to version 22.5 (145)
INFO: ...auto-generating build for 22.5
INFO: Finished.
````

**Comment by yvolk** [comment]
@krt16s FYI I created the latest "27.05-release" tag in a separate release branch ("release/27" i.e. not in "master"). 
Hope f-droid will automatically pick it up for its release.

**Comment by krt16s** [comment]
Should build tonight.
