### ISSUE TITLE
What is the GNU social protocol specification?

### ISSUE THREAD

**Issue by dejj** [andstatus/andstatus#327]
Hello,

In AndStatus' description I read:

> It supports multiple protocols, including GNU social

So I wanted to implement the GNU social protocol on my own.
However, the GNU social homepage says:

> It is social communication software

I haven't found any links to a protocol specification either. My question is:
Is there a specification for the GNU social protocol, or is the interface undocumented, reverse-engineered by you, and possibly subject to change often?

**Comment by yvolk** [comment]
Hi @dejj This is the only live link to GNU Social API,  which I know:
http://www.skilledtests.com/wiki/Twitter-compatible_API
Unfortunately, it refers to the Twitter Rest API v.10, which is not available now. 

As AndStatus supported Twitter earlier, I had to add the "StatusNet" specific. See https://github.com/andstatus/andstatus/blob/master/app/src/main/java/org/andstatus/app/net/social/ConnectionTwitterGnuSocial.java

If you will find Twitter Rest API 1.0 docs, please post here.
