### ISSUE TITLE
Add support for Conversation API

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#328]
Using a dedicated "Conversation" API (if it is supported by a Social network) could allow us to download  to AndStatus and show to a User more messages of a conversation than we can now.
Currently we discover a conversation tree, retrieving related messages one-by-one using "in reply to" field of a message.
1. GNU Social has conversation API: https://server.tld/api/statusnet/conversation/(Conversation-id).json
   The conversation id is sent in every regular post.
   E.g. conversation on this topic: https://loadaverage.org/api/statusnet/conversation/7507140.json
2. Twitter, apparently, has no such API available to public (private URL, available for Twitter's own app only, is https://api.twitter.com/1.1/conversation/show.json ). See this long discussion: https://twittercommunity.com/t/view-conversations-api-support/11090/41
3. Pump.io has all replies ("Comments") embedded in the main "Note", when we request that note only. Plus it has a separate API for "replies", which can be used to find replies of replies recursively (see #276 ).

**Comment by yvolk** [comment]
I just noticed that we already had the same ticket created by @annando #270 
Quoting @annando below:

Friendica and Statusnet support commands for fetching all posts of a thread. Friendica and Statusnet are using different commands for that.

For Friendica it is "conversation/show". For parameters see the documentation: https://github.com/friendica/friendica/wiki/Friendica-API

This command is used in Twitter as well - but can only be used with the application keys for the original Twitter app.

Statusnet has a slightly different approach. The API call is "statusnet/conversation/4711.as" (where "4711" is the conversation id). The extension ".as" is important.

Using these commands would speed up the showing of threads very much.

**Comment by annando** [comment]
Friendica now supports the GNU Social command as well. So supporting "statusnet/conversation/" would help a lot.

**Comment by yvolk** [comment]
Implemented in v.31.01. Now in the Open beta testing https://play.google.com/apps/testing/org.andstatus.app
