### ISSUE TITLE
In app media preview

### ISSUE THREAD

**Issue by Dragnucs** [andstatus/andstatus#329]
Currently, AndStatus redirects to the browser where we need to click an additional link to view media. A better approach is to have a pop-up to view images, gifs, WebM/MP4 and embeded video players like YouTube if possible.

This can be take a step even further and have a basic in-app web viewer to view linked pages.

**Comment by yvolk** [comment]
@Dragnucs Do you know if any Open Source app has such a feature so we could reuse it?

**Comment by Dragnucs** [comment]
Yes, many. The ones I can recall right now are Redreader for reddit and 
Twidere. On twidere's repo are cited the libraries and projects the 
application is based on. You may find what you want there. RedReader 
has an advanced webviwer that migh interest you.

**Comment by yvolk** [comment]
In app viewers and browsers are actually crippled ones. Full - featured image viewers and browsers give you lots of options. And you can select a viewer/browser that You think is the best. Moreover, this is one of differentiating architectural features of Android.

In app viewer/browser means additional burden for the application's development team. Constant reinvention of a wheel... 
This is all about priorities. We have tens of requests and ideas to be implemented in AndStatus, which cannot be covered by any external application...

**Comment by Dragnucs** [comment]
There are already Android libraries and ways to open images and media either in-app or delegate the task to a specialized application. For example, NewPipe proposes to open audio/videos in an external audio/video player. having to open the web browser to see a not properly scaled media is annoying.

**Comment by yvolk** [comment]
I see that your problem is actually not specific to AndStatus: some time ago you set "the web browser" as a Default image viewer. And now this not very good "image viewer" is opened from AndStatus without any prompt?!
You have to remove that "Default" from that application, and next time you will be prompted for an image viewer! Please search for "How to remove default application in Android" or see e.g. http://www.makeuseof.com/tag/remove-change-set-default-apps-android/

?!

**Comment by rodneyrod** [comment]
As a user, I would rather not have to save every image / media file to local storage in order to view it.

**Comment by yvolk** [comment]
@rodneyrod This is exactly how AndStatus works now: it provides an image to any app as a "stream" to be shown to a User without any intermediate file needed.
For a developer reference: see org.andstatus.app.msg.MessageListContextMenuItem#VIEW_IMAGE

**Comment by rodneyrod** [comment]
Thanks for that, I realised that shortly after posting this, realised this is for feature rich media, although that would be a nice addition. Also, does this project have some sort of bountysource presence or something similar to donate to?

**Comment by yvolk** [comment]
@rodneyrod Thanks for asking about bountysource, I created the separate topic to discuss that: #401
