### ISSUE TITLE
Unrolling URLs in tweets

### ISSUE THREAD

**Issue by DanielHeath** [andstatus/andstatus#335]
Twitter uses a link shortener `t.co`. 

It would be nice to know where a link was actually going to take me (e.g. by making a request and following the redirect). 

Would a pull request be welcome for this? I'm not familiar with java so I might need some design guidance.

**Comment by yvolk** [comment]
We have this request for years :-)  #4 Add an option to expand shortened URLs 
Yes,  it would be good to implement this.

**Comment by yvolk** [comment]
@DanielHeath Let's continue discussion and work out implementation in #4.

Closing this ticket as a duplicate.
