### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page; 22.14.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [andstatus/andstatus#338]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not present, as of: 22.14.

**Comment by yvolk** [comment]
Which "Info" page are you referring to? Please explain!
We do have e.g. in AndStatus settings -> Information -> Change Log   - which opens the Change Log....

**Comment by locutis-of-borg-1999** [comment]
Within the F-Droid app', the info' page for the app's it might install.

https://f-droid.org/manual/html_node/Changelog.html#Changelog

**Comment by yvolk** [comment]
I don't have any account in F-Droid system to add a link to the Change log of AndStatus:
http://andstatus.org/changelog.html

@krt16s Could you add the Change Log link of AndStatus to f-droid application ?

**Comment by krt16s** [comment]
Added. Will show up tomorrow.

**Comment by locutis-of-borg-1999** [comment]
B-) 8-)

**Comment by yvolk** [comment]
@krt16s Thank you!
