### ISSUE TITLE
New Feature: Save Image

### ISSUE THREAD

**Issue by Yowlen** [andstatus/andstatus#345]
I often save images that I like so that I can repost them later without having to search through a thousand tweets. It'd be nice if AndStatus had a "Save Image" option in the context menu.

It should be relatively easy to implement, since AndStatus already saves the images to a bulk folder for offline viewing. It's just a matter of copying it to the target destination. For example, "/sdcard/Pictures/AndStatus". An option could be added to the settings to customize this location, too.

**Comment by yvolk** [comment]
We already have "View image" context menu  option.
The application that can View an image, can usually save it. I just test on CM firmware...

**Comment by Yowlen** [comment]
Ah, I use QuickPic*, which doesn't have the ability to do so, at least for local files. Since they're stored on the SD card already, I can understand why that feature isn't usually necessary.

Warning: Unrelated rant below. Feel free to ignore. And my apologies in advance. XD

* The last version before Cheetah Mobile took it over & inflated the apk to double the size just by adding their proprietary cloud service to it, that is. QuickPic already had support for GDrive, Dropbox & a few others btw, so the idea that a single cloud service added 2-3MB to the apk when the existing ones didn't even add 1MB is preposterous. They likely added other stuff that wasn't mentioned, & I don't trust devs with shady crap like that.

**Comment by yvolk** [comment]
I see why QuickPic doesn't have "Save" option: exactly because they are promoting their cloud storage.
So if you want to save to SD, you better switch to some other viewer...

PS: Regarding 3Mb added with only one feature: this doesn't seem unusual to me...

**Comment by Yowlen** [comment]
The thing is, though, they didn't add a new feature. The 2MB apk I use from before Cheetah Mobile took over _does_ have support for GDrive, Dropbox, & a few others. There's no reason adding an additional server to the support list should double that size. That's why it's suspicious to me.

btw, I've been hunting for a new photo viewer, but so far, none that I've tried have an explorer-like file browser. They all just list every folder with a picture, no matter where it's embedded in the filesystem. If you know of one offhand, I'd love any recommendations.

Anyway, I digress. I understand your reasoning for this, & it makes sense to me regardless of my personal feelings. I'll keep hunting for a new picture viewer app, & I thank you for your time.

**Comment by yvolk** [comment]
@Yowlen Actually QuickPic was my favorite image viewer for many years. I don't know any better alternative yet... but it appears that most of the time I don't need much, and almost any viewer suffices... plus universal Total Commander.
