### ISSUE TITLE
Change textual links to "Get it on ..." buttons in README

### ISSUE THREAD

**Issue by PanderMusubi** [andstatus/andstatus#347]
Please add buttons for "Get it on Google Play" and "Get it on F-Droid" in the README file with the links to the appropriate pages.

**Comment by yvolk** [comment]
We already have both links in README.mediawiki file, you see that file here, below a list of top level folders: https://github.com/andstatus/andstatus

**Comment by yvolk** [comment]
We also have both links at http://andstatus.org

**Comment by PanderMusubi** [comment]
Many projects have also those images (as you already have on you site) also in the README file so they get shown on in GitHub when viewing the repository in a web browser.

**Comment by yvolk** [comment]
Yes, its here: https://github.com/andstatus/andstatus - visible in Web Browser
?!

**Comment by PanderMusubi** [comment]
Nope. You need something as 

[![Get it on F-Droid](get_it_on_f-droid.png?raw=true)](https://f-droid.org/repository/browse/?fdid=org.andstatus.app)

in the README and add a PNG with that name to the root.

**Comment by yvolk** [comment]
I got you at last, you mean that textual links are not enough, and we need image links :-)

**Comment by PanderMusubi** [comment]
Yes :)

**Comment by yvolk** [comment]
Done, at last!
What a pain is wikimedia/markdown at Github...

**Comment by yvolk** [comment]
@PanderMusubi Thank you for the link to the example page:  https://github.com/martykan/webTube
Without it I would figure out correct syntax for hours..

**Comment by PanderMusubi** [comment]
Looks good! Thanks
