### ISSUE TITLE
Show line breaks for messages without HTML content

### ISSUE THREAD

**Issue by Yowlen** [andstatus/andstatus#350]
Not sure if it's just the Twitter API, or if it affects pump.io/GNU Social, too, but I've noticed line breaks are just shown as spaces in AndStatus.

**Comment by yvolk** [comment]
Line breaks are shown as spaces for those "Social networks" that have "Allow HTML content" set to "on". 
You can change this for any particular Social Network in AndStatus settings -> Account -> Manage Social Networks -> select a Social network to change...

**Comment by Yowlen** [comment]
Oh, wow. So, I could use HTML tags in my tweets & AndStatus would parse them? Interesting.

Anyway, given the limited characters for Twitter, I think it'd be better to have that off by default for that social network. The lack of space makes it extremely unlikely that anyone would use them. Besides, does Twitter's website/apps even parse them?

**Comment by yvolk** [comment]
I changed default value, don't remember, why I thought that this is better...
Please test and report if the setting is not correct for Twitter.

**Comment by Yowlen** [comment]
Hmm, I don't see line breaks registering even after disabling the HTML parsing. Do I have to clear the data to get older tweets to change?

**Comment by yvolk** [comment]
Interesting, maybe I forgot, how this should be shown...

**Comment by yvolk** [comment]
I implemented this change without dependency on Social network settings:
Line breaks are shown for every message that doesn't have HTML markup already. This works even for drafts of messages.
