### ISSUE TITLE
OutOfMemoryError on loading bitmap to cache with large amount of free memory

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#351]
This happens on some devices, where there is enough memory but it looks like it becomes fragmented and there is no single continuous free space to accommodate another bitmap. In the below report about 50% of attached image cache (i.e. about 25Mb) is free, 230Mb of device memory is free, yet no room for 235 Kb  allocation was found:
```
USER_COMMENT=
ANDROID_VERSION=5.1.1
APP_VERSION_NAME=23.01
BRAND=Samsung
PHONE_MODEL=GT-I9100
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:304)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalStateException: ImageCaches:
Avatars size:6732256 of 9047246 bytes, hits:869, misses:735, hitRate:54%
Attached images size:24165036 of 45236224 bytes, hits:17, misses:183, hitRate:8%
Styled drawables: 0
Memory: available 293781504 of 824356864

Tasks:
Total launched: 653; queued: 3; running: 3. Skipped: 491
R 1. HeartBeat 44; org.andstatus.app.service.MyService$HeartBeat on SYNC; age 488sec; RUNNING 488sec; instanceId=2; org.andstatus.app.service.MyService$HeartBeat@6d19fe6c
R 2. QueueExecutor:{currentlyExecuting: CommandData:{command:fetch-attachment,created:5 hours ago,"Canon 85mm f1.2l ii usm #Barcelona…",itemId:7433,hashCode:307051340,CommandResult:{}}, since: just now, org.andstatus.app.service.MyService$QueueExecutor on SYNC; age 58sec; RUNNING 58sec; instanceId=3760; org.andstatus.app.service.MyService$QueueExecutor@c2d3c654}
R 3. AttachedImageFile5147 on QUICK_UI; age 0sec; RUNNING 0sec; instanceId=4206; org.andstatus.app.data.AttachedImageFile$1@acf57cb2
Q 1. AttachedImageFile5148 on QUICK_UI; age 0sec; QUEUED 0sec ago; instanceId=4207; org.andstatus.app.data.AttachedImageFile$1@acf57cb3
Q 2. ShowSyncing ShowSyncing3487 on QUICK_UI; age 0sec; QUEUED 0sec ago; instanceId=4210; org.andstatus.app.msg.TimelineActivity$5@f4e055aa
Q 3. AttachedImageFile5151 on QUICK_UI; age 0sec; QUEUED 0sec ago; instanceId=4213; org.andstatus.app.data.AttachedImageFile$1@acf57ccb

Thread pools:
SYNC: java.util.concurrent.ThreadPoolExecutor@24c79194[Running, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 7]
FILE_DOWNLOAD: java.util.concurrent.ThreadPoolExecutor@23cc443d[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
QUICK_UI: java.util.concurrent.ThreadPoolExecutor@3ef1d432[Running, pool size = 1, active threads = 1, queued tasks = 3, completed tasks = 628]
LONG_UI: java.util.concurrent.ThreadPoolExecutor@c4ac583[Running, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 12]
DEFAULT: java.util.concurrent.ThreadPoolExecutor@a563300[Running, pool size = 3, active threads = 0, queued tasks = 0, completed tasks = 20]
at org.andstatus.app.os.MyAsyncTask.doInBackground(MyAsyncTask.java:84)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 235236 byte allocation with 148848 free bytes and 145KB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:634)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:610)
at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:392)
at org.andstatus.app.data.MyDrawableCache.loadBitmap(MyDrawableCache.java:97)
at org.andstatus.app.data.MyDrawableCache.getDrawable(MyDrawableCache.java:83)
at org.andstatus.app.data.MyDrawableCache.getDrawable(MyDrawableCache.java:69)
at org.andstatus.app.data.MyImageCache.getAttachedImageDrawable(MyImageCache.java:117)
at org.andstatus.app.data.AttachedImageFile$1.doInBackground2(AttachedImageFile.java:128)
at org.andstatus.app.data.AttachedImageFile$1.doInBackground2(AttachedImageFile.java:125)
at org.andstatus.app.os.MyAsyncTask.doInBackground(MyAsyncTask.java:78)
... 5 more
java.lang.IllegalStateException: ImageCaches:
Avatars size:6732256 of 9047246 bytes, hits:869, misses:735, hitRate:54%
Attached images size:24165036 of 45236224 bytes, hits:17, misses:183, hitRate:8%
Styled drawables: 0
Memory: available 293781504 of 824356864
```

**Comment by yvolk** [comment]
I got another report.
The crash is similar to https://github.com/andstatus/andstatus/issues/351 but in this case image cache is almost full:
"Attached images size: 171MB of 186MB, hits:10, misses:388, hitRate:2%"
I will make an app a bit smarter and turn cache off on this error...

**Comment by yvolk** [comment]
What I did to prevent such crashes:
When  OutOfMemory error on an image loading occurs:
1. The OutOfMemory error is caugth and a User simply gets no image instead of the crash.
2. The whole cache is being cleared on this error and maximum size of the cache is made 2 times smaller than it was before.
3. System continues working as if nothing happened, images are being loaded into a smaller cache.
4. Next time the same error occurs, cache is being shrinker again, and so on.

For debugging purposes we can still see these OutOfMemory errors, when in Settings-> Logging and Debugging -> Debugging information in a User interface" is turned on.

**Comment by alanz** [comment]
Looks good. Cutting the cache in half seems quite drastic, maybe some other constant could also be used, worst case it takes a few rounds to get to the appropriate size. With network traffic.

**Comment by yvolk** [comment]
@alanz This is a deficiency of some Android devices or may of a platform... Initial cache size is set to one-tenth of free memory. And yet this is too much for some devices...

**Comment by yvolk** [comment]
Reading discussions like http://stackoverflow.com/questions/10682049/android-gc-memory-fragmentation-fail-workaround I see that the same problem is common for Android, and it is not specific to bitmap allocation. 
The solution that I want to try now is to allocate image cache once and then reuse cached bitmaps memory. I will have to allocate bitmaps of maximum size in order to be reusable...
Actually, we will have two caches: one for avatars of the same size. And another - for attachments.

**Comment by yvolk** [comment]
This is implemented as a bitmap cache, initialized only once - during application start. All other bitmaps are allocated for a short time only.
Testing of initial implementation in v.25.02 showed that cache size for Android v.4 devices should be at least 2 times smaller than for Android 5 devices. Otherwise we are getting OutOfMemoryError right after application start.
This special fix for Android v.4 devices is included in AndStatus v.25.03. The fix works, as I see so far. More testing is needed

**Comment by yvolk** [comment]
After the fixes I don't receive reports on this issue anymore.
So closing the issue.
