### ISSUE TITLE
problematic switching back from "mentions" to Timeline & combined feature

### ISSUE THREAD

**Issue by bulletbites** [andstatus/andstatus#356]
Each time I click on push notifications AndStatus brings you into the "mentions" timeline and the menu shows your location as being in the timeline "mentions". To get back to your previous timeline setting you have to click on timeline and you can choose to switch back to "everything" in my case which becomes a hassle. It would be better if Andstatus would change this somehow. To get back to TL "everything" from "mentions" there should be a proper back-option to jump you back instantly to your preset TL choice, something like a "home" button.

Also I don't get why the "combined" option is in that menu. Why not move it away to "settings". 

Am I simply overlooking something or is this a known issue with AndStatus (using GNU social)

![screenshot_2016-03-27-20-41-07](https://cloud.githubusercontent.com/assets/17816155/14067095/bed800e4-f45c-11e5-9ecd-b0ca581f5d46.png)
![screenshot_2016-03-27-20-41-14](https://cloud.githubusercontent.com/assets/17816155/14067096/bed93900-f45c-11e5-997f-a33285c17199.png)

**Comment by yvolk** [comment]
The panel, which appears from the left, is Android "Navigation drawer", see https://www.google.com/design/spec/patterns/navigation-drawer.html#
So I guess that we use it properly now by placing on it controls to switch between different views... "Combined" is just one of these switches, not a Setting. I personally often use it while searching posts in one or all instances...
Maybe we should simply use a tap on a Timeline Title to switch back to the Default Timeline and default "Combined" setting (to be added!) and Default account?!

**Comment by bulletbites** [comment]
once you are in the "mentions TL" (if you followed a notification) you are kinda forced to go: 
 > bring up navigation drawer, its TL shows "mentions" click somewhere on Timeline, this brings up another window with all the views listed, > select "everything" and then it jumps you back into the default timeline sort to speak. A button somewhere at the top to go "home/back/out of the mentions" would be best imo. I would consider mimicking twitter's app which has those buttons at the top.

**Comment by yvolk** [comment]
Could you attach Twitter screenshot with this "Home" button(s)?

**Comment by bulletbites** [comment]
from left to right:
- bird: home or timeline button
- bell: notifications. this would bring you into mentions, fav, etc.
- envelope: make new tweet
- face: find a person
- glass: search feature
- 3 dots: settings
 
![screenshot_2016-03-29-00-49-55](https://cloud.githubusercontent.com/assets/17816155/14092603/73e77136-f548-11e5-8d62-1e72e01ca6b2.png)

**Comment by yvolk** [comment]
AndStatus has a button to open Navigation Drawer at a place, where Twitter app has a "Home" button. 
Moreover, Twitter app has far less Navigation options, tan AndStatus, so they all could fit in Twitter's custom substitute of an Android Action Bar.

In order not to reinvent the wheel and not to puzzle a User with unusual design, I think we should:
1. Add a one step Navigation to the "Default Timeline". This Navigation may be accomplished by two ways:
1.1. Tapping on an Action Bar title (not obvious for a Novice, but quick for experienced User.
1.2. Using dedicated "Default Timeline" item on the Navigation Drawer, located at the top of the drawer and having "Home” icon. Using this way of navigation requires one more step, but is easily discoverable by a Novice User.

2. Pressing Back button on a device  from other Timeline (plus other Combined setting or other selected account) than a Default Timeline ,should also return to Default Timeline. 

3. Icon to open...

**Comment by bulletbites** [comment]
AndStatus v25.02 (169) fixed this issue.
