### ISSUE TITLE
Add option to have rounded avatars

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#357]
I just found a solution for this http://evel.io/2013/07/21/rounded-avatars-in-android/

**Comment by vinzv** [comment]
That would be nice! Furthermore a big view of the profile image when tapping the small one in timeline would be good. But that depends on higher resolutions which are not available in GNUSocial.

**Comment by yvolk** [comment]
Implemented, will be included in AndStatus v.26+
![scr-rounded-avatars](https://cloud.githubusercontent.com/assets/207716/14579968/9cc8bd4e-03c6-11e6-8550-4a711060f255.png)

**Comment by yvolk** [comment]
@vinzv regarding User's profile on a separate view - another story / ticket...
