### ISSUE TITLE
Add an indicator for reblogged posts

### ISSUE THREAD

**Issue by HeikoAdams** [andstatus/andstatus#358]
Currently there is no way to see that a post was reblogged and for that you sometimes ask yourself "why the f**k is this post in my timeline?".

So it would be nice to have an indicator for reblogged posts. Something like an icon or an "reblogged by .." below the post.

**Comment by yvolk** [comment]
Currently this is shown in a Conversation view only. Will try to move it to Timeline also.

**Comment by yvolk** [comment]
This is a duplicate of #168. Please follow up there.
I will turn to this soon...
