### ISSUE TITLE
Migrate to the modern OAuth library

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#359]
Currently for OAuth AndStatus relies on Signpost library, which is not in active development and which is not designed to work with ApacheHttpClient on Android API 23. 
See e.g. https://github.com/wuman/android-oauth-client that is an an Android extension to the Google OAuth Client Library for Java.

Maybe we should start with migration from ApacheHttpClient to Android native java.net classes ... currently we have both libraries used in AndStatus code, so it shouldn't be that hard...

**Comment by yvolk** [comment]
I successfully migrated AndStatus application to Android port of Apache HttpClient for Android https://github.com/smarek/httpclient-android , which works with Android API up to 23. The port has modified Java package names in order to avoid conflicts with outdated version of Apache HttpClient, included into Android core.
In order to make OAuth work I had to customize signpost-commonshttp4 module of Signpost https://github.com/mttkay/signpost and tested that it works successfully (released two weeks ago already). In order to contribute these changes to community I will contact with @mttkay and possibly create another module for the Signpost:
signpost-commonshttp4-android

**Comment by mttkay** [comment]
I haven't been a maintainer of Signpost for years. Looking at the recent activity, I'm not sure anyone is maintaining it, but https://github.com/thorikawa has been shepherding the project as of lately.

OAuth 1 is generally considered dead and most major service providers either discourage the use of OAuth 1 or have completely removed support (Facebook, Twitter, and more recently Google to name a few.) The same is true for Android's Apache HttpClient implementation (see http://android-developers.blogspot.de/2011/09/androids-http-clients.html), which in fact has been removed entirely from the Android framework library as of M.

That said, you shouldn't be using either. I'd reconsider how much effort you want to spend on this.

**Comment by yvolk** [comment]
@mttkay Thank you for the reference, I will contact with @thorikawa on this contribution.

Regarding actual usage, the fact is that this application, AndStatus, still successfully uses Signpost to connect to Twitter. And it took me a couple of hours to adapt it for the new Apache HttpClient Android port. And there are other systems, like GNU Social that still cannot properly implement even OAuth 1. So I have use Basic Authentication with it :-)

Of course this is a temporary solution but it saved my time now.
So Signpost is not dead yet, and this proposed change could help some other developers also?!

**Comment by thorikawa** [comment]
Thank you for your update. Seems like there are a couple of alternatives for android e.g. https://github.com/pakerfeldt/okhttp-signpost and I am afraid I don't have much time to decide which is the best choice for android (I have not been working on android dev for a long time.). Meanwhile, you can create a new repository for your module so I can add a link to it. Thanks!

**Comment by yvolk** [comment]
@thorikawa Thank you, I will publish that module and let you know.

**Comment by yvolk** [comment]
@thorikawa I forked Signpost repo and added signpost-httpclient-android module to it: https://github.com/yvolk/signpost/tree/master/signpost-httpclient-android
This is actually a small modification of existing signpost-commonshttp4, so I don't think it deserves  separate repository and separate maintenance.
Maybe we better pull this new module into the main Signpost repo
?!

**Comment by thorikawa** [comment]
I understand many applications still rely on apache HttpClient library, but I personally think it's kinda temporary solution to use android port of that, probably it's better to Volley or OkHttp which is currently dominant in android dev. So I still want to keep your repository separate. It does not matter whether it's small modification or not. I will add a link later. Thanks,

**Comment by yvolk** [comment]
@thorikawa Do you think it's ok to leave my fork of Signpost repo as is?!
I mean don't create new repo,  maybe even change group id to my own... in order to be able to distribute artifacts to maven centrsl etc.

**Comment by thorikawa** [comment]
@yvolk it's ok.

**Comment by yvolk** [comment]
@thorikawa I updated README.md to mention signpost-httpclient-android extension to be used with Android API 23 and newer, and added all necessary links there.
Please see "Google Android" section in the readme file at https://github.com/yvolk/signpost

**Comment by yvolk** [comment]
As problem with migration to Android API 23 is solved, I don't see much value now in migration to some "Modern" OAUTH library. So closing for now.
