### ISSUE TITLE
Can't reply to the long messages

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#362]
As you can see, there's no space for me to send the message (couldn't even with "send pressing INTRO" option)
![](https://quitter.es/attachment/245929/thumbnail?w=338&h=600)

**Comment by yvolk** [comment]
Ad-hoc solution to this problem is to turn your device into landscape orientation. Then large Send button should be visible.
I will find better solution to this...

**Comment by yvolk** [comment]
Maybe we could Auto hide snd show Action bar somehow.
See e.g. http://www.devexchanges.info/2015/09/android-showhide-actionbar-when.html?m=1

**Comment by yvolk** [comment]
Implemented in v.26.01
