### ISSUE TITLE
coloured Reply, Retweet & Favorite icons? 

### ISSUE THREAD

**Issue by bulletbites** [andstatus/andstatus#363]
In the example screenshot I both Retweeted & Fav'd the message/tweet but atm my actions on the message appear at:
a the top: [retweet icon] bulletbites/Sealion.
b right bottom: [white coloured fav icon]
c bottom: [bolded hollow fav icon], retweet icon NOT bolded.
(see below)
![coloured1](https://cloud.githubusercontent.com/assets/17816155/14630879/bb85a07a-0610-11e6-85a0-4adc3ec114ef.png)

Suggestion: Keeping track of when I "fav'd" (or retweeted) the message doesn't necessarily be showed as extra information, it can be inferred by the timestamp from the TL. I Would suggest coloured signifiers for the Reply, Retweet & Favorite icons at the bottom of the message (similar to how twitter shows it).

You'll free up screenspace at the top (a) and right bottom (b) per message too.
(see below)
![coloured1b](https://cloud.githubusercontent.com/assets/17816155/14630878/bb83442e-0610-11e6-899a-9f9e67959272.png)

In general as I understand it AndStatus now throws each action back into the "Everything Timeline" which is a bit redundant in my opinion. So if I fav'd & retweeted a message it will show up with a total of 3 times the original message (original message, bulletbites fav'd message & bulletbites retweeted message). To free up the TL simply icons could highlight your actions without the need to show me again the stuff I fav'd & retweeted in the timeline.

**Comment by bulletbites** [comment]
Also keep in mind to keep the icons used similar in form and colour as the webclient version. The webclient for example still uses the vastly superior star icon to the heart icon for "favs" in yellow.
![similar1](https://cloud.githubusercontent.com/assets/17816155/14631444/b79cb5ea-0613-11e6-8215-3dcbb490111e.PNG)

**Comment by yvolk** [comment]
So we have these requests in your posts above:
1. Colored icons
2. Remove duplicated Favorited icon on the right side, when row with buttons is shown.
3. Add an option to replace Heart with Star icon.
4. Bold Reposted icon if I reposted the message.
?!

**Comment by bulletbites** [comment]
hope this shows what I mean:

![liketwitterdoes1](https://cloud.githubusercontent.com/assets/17816155/14648398/5a9f200e-0662-11e6-866e-c0705e6f5a3b.png)

**Comment by yvolk** [comment]
In order to colorify icons, we can use this solution: https://snow.dog/blog/how-to-dynamicaly-change-android-toolbar-icons-color/

**Comment by yvolk** [comment]
1. Reblog and Favorite icons-buttons below a message are shown tinted if our account reblogged / favorited this message
2. No duplicated Favorited" icon to the right.
![screenshot_2016-04-23-07-31-06](https://cloud.githubusercontent.com/assets/207716/14759284/a974079c-0925-11e6-9afb-e81ae3328bfe.png)

released in v.26.02

**Comment by bulletbites** [comment]
Looks promising. I wonder if those icons when activated shouldn't be more visible then adding a blue coloration to it with the Tinted Drawables feature. I could provide actioned .png if you like? I'll wait on AndStatus 26.02 and give you input.

**Comment by bulletbites** [comment]
Pretty neat implementation, the blue colored actions do stick out enough.

**Comment by yvolk** [comment]
@bulletbites Thanks, 
What's pleasant here is that in order to have colored icons we didn't have to actually create them: both black and white icons can be "tinted" (colored) on demand by simply changing a value of an XML attribute... And this "tint" is consistent with how Android system itself does this e.g. in Settings, in Navigation drawer...
