### ISSUE TITLE
Design: Action bar + Write button

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#364]
A more intuitive, attractive action bar with 6 buttons:
- Lateral panel: with all that the current menu has.
- Timelines: with a drop-down menu which highlight the current TL. Personally, I see too much TLs here, I would hide some of them (eg: including an user view and let Favorites as a special TL to show there)
- Accounts: the same menu that TL but showing the accounts and a "combined" selector. The icon is the default account icon.
- Go to the top button
- Another button:  to be honest, I don't know what button should be there but I think it's more attractive with 5 buttons. Anyway, 4 buttons works cool as well.

I also added a floating writer button.

![screenshot_2016-04-19-11-20-30](https://cloud.githubusercontent.com/assets/7888062/14637471/bcc20d18-0631-11e6-8b23-c9e3a511586d.png)

**Comment by bulletbites** [comment]
awesome work!

**Comment by yvolk** [comment]
@moshpirit Interesting... My reflection on these suggestions:
1. Actually, we do have Timeline selector already (click on a Timeline title). 
2. As your proposal with "buttons only" means loss of some features, it could be an option only, not a complete replacement of what we have now?!
Anyway, "Overflow" button with additional menu items is needed...
3. Do you mean that Navigation Drawer, which appears from a left side, is not needed in this design? If yes, what "&" icon should do?

**Comment by moshpirit** [comment]
Thank you!!

OK, let's see:

1. I know, but it's in the Navigation Drawer.
2. Oh, does it? What features?
3. No, I think it's a good thing having it for now, that's the function of the "&s" icon: showing the drawer :)

**Comment by Yowlen** [comment]
It's worth noting that Twidere has a scrolling top bar, so the three-dot extra menu button isn't 100% necessary depending on how the UX is set up.

Also, I second this option for a redesign. The top bar is pretty crowded as it is, imo.

**Comment by yvolk** [comment]
2.1. Action bar Title and Subtitle hold additional information on current context: search term, current user...
2.2. Current menu has many menu items, some of them are hidden under "overflow button", others appear only when editor is open.

**Comment by moshpirit** [comment]
>Action bar Title and Subtitle hold additional information on current context: search term, current user...

For searches, I agree it should be shown the term instead of the bar (just like AS currently does). About current user: it would be shown as an avatar and if we touch it, another list of users to select would appear. 

>Current menu has many menu items, some of them are hidden under "overflow button", others appear only when editor is open.

Oh, sure, I forgot about it! maybe it the text to reply should be shown only if we tap the first line showed so AS could use this space for adding an attachment button.

Another excellent writer I've seen is the one used on [Slide](https://f-droid.org/repository/browse/?fdid=me.ccrama.redditslide). Also, the tree branched conversations are shown in a very cool way. The idea of showing also the first X messages of every conversation is another nice feature to make it clean, so if you want to see the entire conversation, you must click on a button.

**Comment by yvolk** [comment]
1. Showing Avatar instead of a User name cannot be called "more intuitive"
2. We already have Timeline selection on Clicking Timeline title (it may be configured as "Go to the top" if you wish)
So it looks like nothing changes dramatically, but becomes less "Android-like" i.e. less intuitive.

**Comment by moshpirit** [comment]
I've been using a Reddit app called [Slide](https://www.reddit.com/r/slideforreddit) for a while and I love the design and all of its functionalities. Maybe you'd like to check it out :)

[Slide on F-droid](https://f-droid.org/repository/browse/?fdid=me.ccrama.redditslide)
