### ISSUE TITLE
Slashes in network names

### ISSUE THREAD

**Issue by HectorAE** [andstatus/andstatus#371]
When I attempted to add the gs.smuglo.li GNU social instance with the official name "GNU/Smug", I was unable to add any accounts to it. The "Add new account" screen for it showed this text:
```
Social network
, type: ?
```
and when I tapped "Add this account" anyway, it appends:
```
Authentication Failed: ConnectionEmpty: The API is not supported: 'REGISTER_CLIENT'
```

Names without slashes do not have this issue.

**Comment by yvolk** [comment]
This is by design. You have to replace forward slash with some other symbol.
