### ISSUE TITLE
Adding account to a duplicated network

### ISSUE THREAD

**Issue by HectorAE** [andstatus/andstatus#372]
While investigating #371 I also found that adding two networks with different names but the same host is allowed, and apparently the one that comes last alphanumerically is used when you try and add an account for either of them.

**Comment by yvolk** [comment]
The fact, that two networks with the same host are allowed, is by design. This could allow you to separate messages, received by different accounts...
I will test a problem with account addition.

**Comment by yvolk** [comment]
I just tested this case using AndStatus v.27.04 - no problems found.
I created additional "Quitter.se2" network, which duplicates hostname of  "Quitter.se" and was able to create accounts in any of them. Moreover, I could create account of the same user in these two networks ("yvolk"), see the screenshot.
![accountsindifferentnetworks](https://cloud.githubusercontent.com/assets/207716/17455263/f93584b2-5bba-11e6-9f87-bc24b9034cb6.png)
