### ISSUE TITLE
[pump.io] Create proper HTML links

### ISSUE THREAD

**Issue by jankusanagi** [andstatus/andstatus#375]
Pump.io uses HTML for posts and comments.
AndStatus does not generate HTML in the posts it creates. This is fine when people are just writing words, but it becomes a problem when someone posts a http link, because that's posted as just text, and does not generate a real, clickable link.

I'm not asking for AS to let the user create pretty links, where any word in the message can be a link to something, just that when a user enters a "http://something" address, that should be converted to a proper <A HREF... tag.

It would be really useful.

Related to this are the line breaks. Pump.io supports long posts, with embedded images, tables, lists... etc. Well, you know, HTML content, as I said.

It would be great that at least line breaks get correctly converted to <br> tags ;)

Thanks!

**Comment by yvolk** [comment]
I hink line breaks are already converted to "br" HTML elements?! You may see my posts at identi.ca: they do have line breaks (I just checked...)

**Comment by jankusanagi** [comment]
Well, it's true for your posts, certainly.

But every post I see posted "via AndStatus" has no newlines. Maybe the problem is not in the editing part, but in the "auto-create a post when using the share option from the browser" part, or something.

**Comment by yvolk** [comment]
I just implemented in AndStatus HTMLifying of a content. Actual transformation was done in literary 3 lines of code using Android system libraries. This gives an advantage of using better algorithm at each subsequent version of Android libraries.

```
private static String htmlifyPlain(String textIn) {
        SpannableString spannable = SpannableString.valueOf(textIn);
        Linkify.addLinks(spannable, Linkify.WEB_URLS);
        return Html.toHtml(spannable);
    }
```
