### ISSUE TITLE
[pump.io] Real 'share' activities

### ISSUE THREAD

**Issue by jankusanagi** [andstatus/andstatus#376]
Currently, sharing a Pump.io post with AndStatus does not create a 'share' activity. Instead, it creates a new post, without a title if there was one (which then is **lost**), with a total loss of formatting, and with a weird reference to the original user (in the post text itself), and a non-clickable-link to the original post.

I think creating a real 'share' activity would be much, much better, and also, really easier, code-wise. Creating a 'share' activity is really simple:
`"verb": "share",
  "object": {"id": "whateverID" }`

I understand that AndStatus supports several networks, and the current way is necessary to share something from Pump to the other networks, but it would be great if that new "cross-post-share" was posted only to the other networks, and to Pump, a real 'share' activity was created instead.

Cheers! o/

**Comment by yvolk** [comment]
1. Existing "Share" feature doesn't make any assumptions about a target, this is why it is in a pure text format. See https://github.com/andstatus/andstatus/issues/112
2. Regarding Titles (Subject) support we have this ticket #150

So this ticket is for a specific case, when a source and a target are in the same Social Network of the "Pump.io" type.

And you know, we _do_ have this feature implemented already :-)
It is called "Repost" ("Retweet" for Twitter). It was implemented long time ago.
Please check, I just "Shared" your post in terms of "Pump.io": https://identi.ca/jankusanagi/comment/cJdi4cGWQT-Z9Rn3mjr5Bw

Regarding terminology, Android has system wide meaning of "Share" action already, and AndStatus implements it in way, expected for an Android User. So using "Repost" term for Pump.io "Share" action is good enough?!

BTW, I remember complaining about "Share" action implementation in Pump.io: my followers don't see Shared message by default (by do see Favorited message...). Now I understand that maybe I have to put some recipients to the Share action in order for it to work as expected by GNU Social and Twitter users?!

**Comment by jankusanagi** [comment]
> So using "Repost" term for Pump.io "Share" action is good enough?!

Not really. Any user familiar with Pump.io will be used to "Share" in all other clients, so this is very misleading.

I'd call your "Share" somethink like "Copy post", "Clone post" or "Forward post", and call the other thing "Share". BTW that other "repost" option is sharing things to "public", but that's a different issue: https://github.com/andstatus/andstatus/issues/271

Note that the Pump.io "Share" action is not posting again (so, **no RE-post at all**), it means passing along a reference to the original post (therefore, **Share**).


> BTW, I remember complaining about "Share" action implementation in Pump.io: my followers don't see Shared message by default (but do see Favorited message...). Now I understand that maybe I have to put some recipients to the Share action in order for it to work as expected by GNU Social and Twitter users?

Your followers see the post you share, that's worked perfectly fine all the time. Addressing for the share is not **public** however, but that's different. I don't think you should specify **any** addressing when sharing (I mean when creating a real share activity, not those repost things).

**Comment by yvolk** [comment]
"Your followers see the post you share, that's worked perfectly fine all the time” 
@jankusanagi Please read https://github.com/e14n/pump.io/issues/848 and explain, how it works, where followers can see it...
 I wrote that ticket three years ago and still think that "Share” doesn't work in Pump.io as nobody replied to me.

**Comment by jankusanagi** [comment]
C/P from there:

You explained a lot of technical data that I don't think is necessary here ;)

The simple test: share someone else's note, go to your feed, see the shared note.

I've done this a million times, and it works. By default, sharing is done Cc: Followers, so looking at someone's feed via the webUI while logged out will NOT show those shares, but they're there for logged in followers to see.

**Comment by yvolk** [comment]
Now I inspected, how pump.io and AndStatus _really_ work:
1. Pump.io doesn't add "by default"/automatically my Followers to a list of recipients of the shared object. I have to do this explicitly. Id of a Users's Followers group is: https://<user's host>/api/user/<user's nickname>/followers
e.g. for andstatus@identi.ca: https://identi.ca/api/user/andstatus/followers

2. AndStatus creates "real 'share' activities" of Pump.io for years. 

What is left to be done now to be more accustomed Pump.io User's friendly:
1. Rename "Reblog" action to "Share via Pump.io" ("Share" already has another meaning in AndStatus and in Android in general for millions of users...)
2. Add a User's Followers "collection" to "cc" field (before AndStatus didn't use that field at all)

**Comment by jankusanagi** [comment]
Hey, thanks for working on this =)

However...
> Pump.io doesn't add "by default"/automatically my Followers to a list of recipients of the shared object. I have to do this explicitly. 

That's not the case. If you do **NOT** specify anything in the To and Cc fields, the server **will** take care of it, defaulting to "Cc: Followers".

Cheers!

**Comment by yvolk** [comment]
@jankusanagi AndStatus puts "public" collection into "to" property ( https://www.w3.org/TR/activitystreams-vocabulary/#dfn-to ) meaning that a Note is publicly shared. As I understand this is not enough for my followers to see this publicly shared Note in their streams... (I think _this_ is Pump.io bug), so, as a workaround, I have to add followers explicitly to "cc".

PS: Now I'm looking at ActivityStreams 2.0 specs and trying to use never terminology in our implementation (taking into account that pump.io is not compliant to that spec yet... https://identi.ca/cwebber/note/dqzGLzjRQdGw7TNutig4qw )

**Comment by yvolk** [comment]
Similarly, when I create public ”Note”, I put Public collection into "to" property.
Do I have to add Followers as another recipient in order for my followers to see this ”Note”?

**Comment by jankusanagi** [comment]
> As I understand this is not enough for my followers to see this publicly shared Note in their streams/timelines... (I think this is Pump.io bug), so, as a workaround, I have to add followers explicitly to "cc".

No, that's not correct. Just adding "Public" to either "To" or "Cc" fields is more than enough for your followers to receive the activity. Any activity. This certainly works perfectly in Dianara. There is no Pump.io bug here.

But if you specifically add **anything** to either of those fields, then the server **will not** take care of adding anything else, it will all be up to you.

It's generally better to just leave the server do its thing, really. The only exception being when creating new content (mostly, activities with "post" verb, to create "note", "image", "video", etc. objects).

**Comment by yvolk** [comment]
@jankusanagi "No, that's not correct. Just adding "Public" to either "To" or "Cc" fields is more than enough for your followers to receive the activity."
This means that this whole discussion is about changing a name of the Context menu item. Everything else is already OK.
Could you check now this with current released version? (v.28.01) Please use "Repost" context menu item to "Share" it.

**Comment by jankusanagi** [comment]
Well, there is **also** the issue of "share" activities being posted "To: Public" instead of leaving the server decide (current server default is sharing "Cc: Followers"). It's not a bug *per se*, but I'd say it's better to leave the server do the addressing.

I'll give it a try when I can ;)

Thanks!

**Comment by yvolk** [comment]
@jankusanagi I relied on your experience and made this change also:
"share" activity now doesn't have any recipients

**Comment by strugee** [comment]
@yvolk thanks for looking into this! :)

**Comment by yvolk** [comment]
The fix is available since v.29.00. Currently in the Open Beta Testing Channel: https://play.google.com/apps/testing/org.andstatus.app
