### ISSUE TITLE
Error verifying letsencrypt certificate

### ISSUE THREAD

**Issue by strk** [andstatus/andstatus#379]
The certificate for  https://brusio.pallamondo.net is not recognized as "verified" by AndStatus.
Web browsers accept it just fine.
It was obtained via letsencrypt. What's the matter ?

NOTE: setting the Social network entry in the client as using "Insecure SSL" allows me to use it, but I'd rather get proper verification, given it's supposedly available.

**Comment by yvolk** [comment]
@strk Could you make this test:
1. Change setting for this Social Network to ”Secure SSL”
2. In a Timeline switch to: Home, NOT combined, account in this Social Network
3. Tap ”Sync with Internet” and wait for completion.
4. Go to "Commands in a queue ” and find a row with an error syncing this timeline.
5. " Share" that error to clipboard / mail and paste here.

**Comment by strk** [comment]
Will try to do that, meanwhile as I've had a verification problem with another domain and another client and figured it was related to SNI, does andStatus support SNI ? (used to get a different certificate based on a client-provided hostname). See https://en.wikipedia.org/wiki/Server_Name_Indication

**Comment by yvolk** [comment]
SNI should work, see https://github.com/andstatus/andstatus/issues/136

**Comment by strk** [comment]
Here's the error:

```
E; Home for strk
Created two minutes ago
executed:1, last:two minutes ago, error:Soft,  
Load Timeline, 
Status code=UNKNOWN; soft; 
; url:'https://brusio.pallamondo.net/api/statuses/home_timeline.json?since_id=2558&count=200&user_id=1'; authenticated; 
Caused by javax.net.ssl.SSLPeerUnverifiedException: Cannot verify hostname: brusio.pallamondo.net, 
strk/brusio, timeline:home, userId:1,
```

I noticed that the default browser on this Android 4.4.2 device (Samsung "Internet") also complains about "The site's security certificate is not trusted!" and adds that the server "presented a certificate issued by an entity that is not trusted by your computer's operating system". But firefox doesn't complain, so maybe it is using its own chain of trust ?

**Comment by yvolk** [comment]
Yes, I think you need to install root certificate ( of Let's encrypt authority or this one... ) manually to Android device.

**Comment by annando** [comment]
Have a look at this result: https://www.ssllabs.com/ssltest/analyze.html?d=brusio.pallamondo.net

The SSL configuration on your server isn't correct. It is no fault from "Let's encrypt" as you can see that my site is working fine: https://www.ssllabs.com/ssltest/analyze.html?d=pirati.ca

**Comment by strk** [comment]
Thanks! It's A- now, and it looks like AndStatus is happy :)
