### ISSUE TITLE
Easily turn Syncing on/off for accounts

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#380]
On *Settings→Accounts→Manage existing accounts* it would be great a button to enable and diable them.

This kind of button fits perfectly, IMO: 
![material-design-lite](https://cloud.githubusercontent.com/assets/7888062/14997532/6ca10808-117f-11e6-8de4-7aa59f9d9c7a.jpg)

**Comment by yvolk** [comment]
What do you think should "Disable account" mean? What is a difference between deleting and disabling an account?

**Comment by moshpirit** [comment]
When you disable an account, its configuration still remains in the phone and it just doesn't get synchronized. It's much easier and comfortable than deleting and adding an account.

**Comment by yvolk** [comment]
Ok, and what's difference between disabled account and an account, for which sync is turned off (in Android Settings -> Accounts and Sync...)?

**Comment by moshpirit** [comment]
You're right, I didn't think about it. A difference could be hiding the account from the list to choose when posting and reading, but that's an extra, what I was asking for was a button that made exactly what you have said.

**Comment by yvolk** [comment]
Turning Account sync on/off directly from AndStatus implemented in v.27.00 (180), available at the Open Beta testing channel https://play.google.com/apps/testing/org.andstatus.app
