### ISSUE TITLE
Cannot Login to GNU Social - Self Hosted GNU Social

### ISSUE THREAD

**Issue by nedson** [andstatus/andstatus#383]
I'm running GNU Status 1.2.0-beta4 with a Let's Encrypt cert (already saw the post about the cert issues). I'm using version 26.05 of AndStatus downloaded from F-Droid.

Suggestions?

Here is the response when trying to login:

A connection error occurred
Status code=NOT_FOUND; hard;
statusLine:'HTTP/1.1 404 Not Found';
statusLine:'HTTP/1.1 404 Not Found';
statusCode:NOT_FOUND (404); rul:'https://nedson.net/api/statusnet/config.json';
authenticated; response:'<!DOCTYPE HTML PUBLIC "-//IETF//DTD...'; error'?';
Caused by org.json.JSONException: Value
<!DOCTYPE of type java.lang.String cannot be converted to JSONObject

**Comment by yvolk** [comment]
Maybe your GNU Social instance is located not in the Root of the site and this is why you are getting 404 error?
If yes you could append root folder to the Social Network "Host" property in AndStatus settings -> Accounts -> Manage Social Networks
?!

**Comment by nedson** [comment]
GNU Social is in the root folder:  https://nedson.net

Not sure what could be wrong.

**Comment by yvolk** [comment]
This looks like GNU Social configuration task. I don't have experience here... 
You could ask, why the URL returns 404 error, in GNU Social itself :-)
E.g. https://loadaverage.org/api/statusnet/config.json works...

**Comment by nedson** [comment]
Got it. Thanks for pointing me to a working example of what should be seen. I know where to look now!

Many thanks! Once I have a solution, I'll post back.

**Comment by nedson** [comment]
Solution:  Enable fancy url's within GNU Social. 

You probably just need to copy htaccess.sample to .htaccess in your root directory...
