### ISSUE TITLE
Way to share images

### ISSUE THREAD

**Issue by kuba-orlik** [andstatus/andstatus#387]
After pressing "View Image", there's no way to share the image url or the image itself - so I'm forced to contribute to the reality presented in [xkcd #1683](http://xkcd.com/1683/) :)

**Comment by yvolk** [comment]
After pressing "View image" you see that image in an application that _you_ configured to open such images. Whether or not that image viewer has "share" feature, depends on that application, not on AndStatus.
Nevertheless I think that adding ability to share at attached image, not a message text only, will be helpful.

**Comment by kuba-orlik** [comment]
I agree. 

BTW, I'm using my system's default gallery application for viewing images from AndStatus. This app always shows the "share" button - viewing images from AndStatus is the only exception... Perhaps AndStatus calls the gallery app in a different way?

**Comment by yvolk** [comment]
I think the problem for a Gallery application lays in a way an image is presented to it: via a "Content provider" (contrary to direct access to a file system). 
This is a recommended way of providing access to an application's internal data. Unfortunately, not many applications fully support this way of getting "content" yet...

**Comment by yvolk** [comment]
I just figured out that ”Photo Editor” can be used to save attachments from AndStatus.
It looks like any Image editor should do this...
![screenshot_20161001-190221](https://cloud.githubusercontent.com/assets/207716/19015293/2400f110-880a-11e6-96b2-80f1570b2994.png)

**Comment by yvolk** [comment]
"Share" message context menu item shares not only textual part of the message, as before, but the attached image also. This way a message with an attachment can be shared from one Social Network to another within AndStatus, or to some note taking application, e.g. to  <a href="https://github.com/federicoiosue/Omni-Notes">Omni Notes</a>, where it will be stored with the attachment.
Some file managers, e.g. <a href="http://www.ghisler.com/android.htm">Total Commander</a>, allow to save shared attachment to a file.. 

Implemented in v.30.00, please test: the Open Beta testing channel https://play.google.com/apps/testing/org.andstatus.app
