### ISSUE TITLE
GNU Social: downloading image when authentication required

### ISSUE THREAD

**Issue by SmartHoneybee** [andstatus/andstatus#390]
##### Context
- On GNU Social `a` instance where access to anything is restricted to accounts registered on `a`.
- A post that contains a link to an image hosted on `a`.
- (The image is visible when using the web interface.)
##### Expected behavior
- The image is loaded from the server `a` and then displayed in the Andstatus timeline.
##### Observed behavior
- The image is not displayed in the timeline.
- Not sure if the image is actually downloaded.
##### Suspicion & Suggested fix
- Image download requires authentication (to ensure that only registered account are able to access them) but Andstatus does not authenticate the user.
- Check HTTP status code of image download.
  - A test without authentication (e.g. with `curl`) resulted in a `HTTP/1.1 307 Temporary Redirect` to the login page.
  - Thus if download (from the server where the user has his/her account) fails with `307` retry authenticated.
## 

I like this project a lot. Thank you for your work!

**Comment by yvolk** [comment]
@SmartHoneybee As I remember, AndStatus tries to download an image both ways: authenticated and not. And it follows redirects in the image pursue.
I think that 307 response from a server is misleading for AndStatus. It's semantically incorrect. 
Actual reason for rejection should be returned with 403 Forbidden code. That 403 page can have a link to a  login page (for a human User) or it could itself act as a login page.
?!

**Comment by SmartHoneybee** [comment]
You are right, the `307` response doesn't really fit in this situation.

I changed the HTTP status code returned to `401` / `403` but in both cases the image did not appear in AndStatus. (In `Commands in queue` it reported that both requests (authorized and unauthorized) failed - with the status is used on the server side (`401` / `403`).)

I was able to download the image from an URL of the form `https://example.org/getfile/ ... .jpg` (with `cURL`) once I supplied the `PHPSESSID` currently used by my browser session (with `--cookie 'PHPSESSID=...'`).

Do you have another idea what might be wrong here?

--
Thank you for looking into this!

**Comment by yvolk** [comment]
@SmartHoneybee Of cause there could be a bug somewhere... 
The code to do the download starts here: https://github.com/andstatus/andstatus/blob/master/app/src/main/java/org/andstatus/app/service/FileDownloader.java
You may see that it has 
```
MyLog.v(this, "About to download " + data.toString() + "; account:" + ma.getAccountName());
```
Which means that if you set logging to verbose, turn logging to file, then you you will be able to see some more information on the download process. On logs please read here: https://github.com/andstatus/andstatus/issues/225

I also highly recommend you to install the latest beta from https://play.google.com/apps/testing/org.andstatus.app 
or build it from sources (I will post latest updates to Github shortly...)
?!

**Comment by SmartHoneybee** [comment]
Working in current version. Thanks!
