### ISSUE TITLE
ContextMenu UX Transparency Defect - Android N with Dark theme

### ISSUE THREAD

**Issue by ladams00** [andstatus/andstatus#393]
How to duplicate error: With dark theme on Android N (Nexus 6), long pressing on a post brings up a backgroundless context menu. See screenshot.

How to not duplicate: Single press a post and a normal everyday menu pops and appears as expected.  See other screenshot.

![tmp_1765-screenshot_20160712-111710615109390](https://cloud.githubusercontent.com/assets/20260564/16778470/002c0b20-4823-11e6-94e5-b4c9d20b27b2.png)
![tmp_1765-screenshot_20160712-111726919853941](https://cloud.githubusercontent.com/assets/20260564/16778475/08cccf30-4823-11e6-9ced-f486fea54339.png)

**Comment by yvolk** [comment]
ContextMenu in Android N is defective, see my bug report on Android: https://code.google.com/p/android/issues/detail?id=215525
I hope that Android Team will fix it and don't force developers reinvent their own ContextMenus...

**Comment by ladams00** [comment]
Thank you for checking it, Yuri.  I didn't think this bug was the same to the previous UX related crash.  At least there is a documented visual reference for now :-) I will switch back to the Device Default per your previous recommendation.  Shall we close this bug or leave it open until Google fixes your bug report?

**Comment by yvolk** [comment]
Let it be open, so we will not duplicate the same report.
BTW reading about Android N I've got that it really is not finished yet in terms of bug fixing. So similar bugs are expected. 
AndStatus is quite sophisticated application, this is why it allows to catch bugs, which went unnoticed at earlier stages of Android N platform development.

**Comment by yvolk** [comment]
As a **workaround** for people having similar compatibility problem, which results in such UX defect or in a crash:
It appears that if you switch in AndStatus Settings -> Appearance -> Theme  to "**Device Default**" - there is no such error in Android N.
