### ISSUE TITLE
Cannot reblog Friendica posts

### ISSUE THREAD

**Issue by dejIO** [andstatus/andstatus#394]
I use AndStatus with my Friendica account. On my Friendica account, I import the remote Twitter timeline. Reblogging a post on Friendica triggers a Retweet also on Twitter, but when I selecct Reblog on AndStatus, nothing happens at all.

Please help me debug this as I'm inexperienced.

**Comment by annando** [comment]
I guess that there is an incompatibility in the API. I experienced something similar with Twidere and Friendica as well. I have to have a look at Friendica's API, but hadn't got time by now.

Could you open an issue at Friendica for that so that we don't forget about it?

**Comment by dejIO** [comment]
I think you could phrase it better than I did :)

**Comment by annando** [comment]
Since I'm having some problems with AndStatus on my device (I'm not sure, if my phone isn't powerful enough or my Friendica account makes too much traffic for Andstatus) so it would be good if you would create the issue since you then should make the final test.
