### ISSUE TITLE
Timeline Mess

### ISSUE THREAD

**Issue by Rbagman** [andstatus/andstatus#395]
I really don't understand the mess you've made of the timeline(s).

**Comment by yvolk** [comment]
In AndStatus v.27 a new way to see / create / manage timelines is created. Please read the ChangeLog on v.27 http://andstatus.org/changelog.html and play with "Manage timelines" view/table.

**Comment by bulletbites** [comment]
@yvolk I think from my own experience with the "manage timelines" you might resolve this by using a default TL setting where users can

[easy mode]
Choose which timeline to set as a default with 3 options only namely: 
- Timeline ("Home")
- Public Timeline
- The Whole Known Network
without any of the syncing options, viewing options stuff available to novice users.

I would make the "manage timelines" feature in its current state a [advanced mode] thingy: for those that want more control in how AndStatus shows their TL with all the bells and whistles (incl the combined stuff). Maybe in the settings menu you can make a option for users to activate/tick [advanced timeline options] if they want to play around with it.

**Comment by yvolk** [comment]
@bulletbites "Manage Timelines" view serves several purposes:
1. Check if timelines are synced, are they downloading messages and what errors were encountered. Separately for each timeline.
2. Set which Timelines to sync automatically.
3. Set which Timelines to show for selection
4. Set Default Timeline.
This is why I think users even without "advanced" expectations will have to use it.

**Comment by rodneyrod** [comment]
@yvolk I don't know if this is the same issue but my Home Combined timeline isn't displaying posts in the right order.

I expect the application to always display the newest tweets at the top and then go backwards as you scroll down, now the top tweet seems to be arbitrarily set and I'm getting posts from all sorts of times in an out of order list, with no way of sorting the timelines out by date.

Is there any way to fix this?

**Comment by yvolk** [comment]
@rodneyrod Could you check if the wrong order is specific to Combined timeline or , maybe, to some Social network (please turn Combined off and switch between accounts)?

**Comment by rodneyrod** [comment]
Yeah the issue persists with individual non-combined timelines, even when combined timelines is disabled. When I did test, it was more in order, but there were still random entries a couple of days to weeks older.

**Comment by yvolk** [comment]
@rodneyrod AndStatus shows a date of creation, not a date of update or reblog/retweet. But orders tweets by dates of updates/retweets.
This is why old tweets, which were retweeted recently, appear above tweets, which were created earlier than creation, but later than retweet.
Please check, maybe this is your case?

**Comment by rodneyrod** [comment]
Thanks @yvolk, that was exactly the case. Sorry about the confusion.

Just out of curiosity, would it be possible to add a setting to toggle whether or not to show the original post or retweet date? Or even somehow display both.

**Comment by yvolk** [comment]
@rodneyrod We need to discuss, what to do and how exactly a User should see this in a separate thread. Please continue this discussion in: #417
