### ISSUE TITLE
Add support for Twister

### ISSUE THREAD

**Issue by rodneyrod** [andstatus/andstatus#396]
It would be great if we could use this as a client pointed at a remote Twister service.

**Comment by yvolk** [comment]
According to http://twister.net.co/ "twister is the fully decentralized P2P microblogging platform"
It has documented API and python implementation example at http://twister.net.co/?page_id=21

**Comment by rodneyrod** [comment]
That's the one, you need to have a sever instance or daemon to connect to first, but And status could act as a client to that.

**Comment by yvolk** [comment]
@rodneyrod Would you like to help with implementation and testing of this?
I didn't use Twister yet...

**Comment by rodneyrod** [comment]
I'll definitely help out where I can, my programming skills aren't so sharp and my Python skills are about as good as my Greek (I don't know Greek) but I'll certainly help out where I can.
