### ISSUE TITLE
GNU social account doesn't work - no timelines

### ISSUE THREAD

**Issue by kai11** [andstatus/andstatus#399]
After phone reset I had to reinstall AndStatus
and I have troubles setting up same account I've been using for a while.

1) install AndStatus from scratch
2) add GNU social account, verified credentials
3) run initial sync

Expected result
1) previous entries in timeline

Actual result
1) Timeline is empty and it says (Unknown timeline)
2) No timelines in timeline list. Refresh also don't help
3) Settings > Accounts > AndStatus force sync shows correct sync date, but actual sync is VERY quick
4) credentials are correct and verified, nothing in logs even on debug verbosity
5) new messages I'm writing were sent to GNU social but again not visible in timeline

**Comment by krischik** [comment]
I have the same problem, just did not find the time for a bug report.

It did kind of went away after adding my twitter account. So it might be a problem with having added one one account or only GNU social account are added or both.

**Comment by asterismo** [comment]
same here as kai11, added a single gs account and have empty timeline, after sending status remains empty

**Comment by yvolk** [comment]
So far I see that the problem is in seeing "Unknown timeline". No wonder that the "Unknown timeline" is empty.
1. Try to switch to "Home" timeline or "Everything"...
2. Select "Manage timelines" in a menu and set Home timeline of your account as the Default timeline (in a context menu of a timeline)

?!

**Comment by archaeme** [comment]
"Manage timelines" shows up nothing and trying to switch via the sidebar doesn't work either.

**Comment by yvolk** [comment]
I see, AndStatus doesn't create default set of timelines after adding the first account, if this is a GNU Social account. Works OK for Twitter account.

**Workaround: Open your account again (Manage accounts...), change sync frequency to any value, and press back button - default timelines will be created.** 

Weird bug. Will fix it ASAP.

**Comment by kai11** [comment]
Thanks @yvolk . Workaround helped

**Comment by yvolk** [comment]
The fixed v.27.04 published to the Open Beta testing channel https://play.google.com/apps/testing/org.andstatus.app
Please test.
