### ISSUE TITLE
Add "Interactions" Timeline

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#403]
As I see, Twidere has a timeline called "Interactions": it contains mentions of / replies to my account(s). "Interactions" timeline in Twidere is the same or close to existing "Mentions" timeline in AndStatus.
Actually "Mentions of me" and "Replies to me" are not the only types of messages, which comprise "Interactions". 

In AndStatus we are creating the "Interactions" timeline, which shows:
- Mentions of "me" (my accounts, registered in AndStatus) and my mentions of other users.
- Replies to me and my replies to other users.
- Direct messages to and from me.

Maybe also (to be decided...):
- Favoriting of my messages and my favoriting of other users' messages
- Reposting/Retweeting/"Sharing" of my messages and my "reposting/sharing actions"

**Comment by vinzv** [comment]
On the "maybe" part:
I wouldn't add that as it's no interaction by other users. I would keep such things separated.

**Comment by yvolk** [comment]
In v.37.01 I implemented this:

"Mentions timeline is replaced by Interactions, which shows not only "mentions" and replies, but also likes, reposts and followers. Basically "Interactions" timeline shows all interactions of other users with us (our actors) whereas "Notifications" timeline shows us only those interactions, which we preferred to be notified about in Settings > Notifications, plus unsent notes."
