### ISSUE TITLE
Add apk signature to a Crash report

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#407]
As the ACRA team didn't do this yet for all its users, we are implementing this first for AndStatus app.
See related ticket in ACRA project: https://github.com/ACRA/acra/issues/493

This is very handy to identify problems in Open Source projects and identify a source of the package. E.g. AndStatus application is distributed both by Development team and by f-droid, with different signatures. And users can also build the application themselves and then send their crash reports...

And this feature is very easy to implement, please see https://www.airpair.com/android/posts/adding-tampering-detection-to-your-android-app

Reporting if the signature is valid is necessary also, but not enough.

More details:
First of all, for the case of most of applications, available in f-droid repository (see https://f-droid.org/ ) more than one "valid" signature exists, because f-droid builds and signes apks itself. Plus development team, naturally, signs its build of apk with the dev team's signature. So we have large number of users with these two "valid" signatures.
It also happens that a user decides to build apk himself (real cases!).

Now imagine that I receive a crash report saying that it occurred in AndStatus application v.27.04 and I cannot reproduce the bug reported or I cannot believe that the crash could happen. Having an apk signature in the report will immediately give me an answer about the origin of the apk: f-droid, me (Google Play store mostly) or unknown user's signature.

This simplest way of doing this is by adding the signature as a custom property
https://github.com/ACRA/acra/wiki/AdvancedUsage#adding-your-own-custom-variables-or-traces-in-crash-reports-breadcrumbs

**Comment by yvolk** [comment]
Implemented. Currently my debug and release keys are identified.
After f-droid release of this version (which logs APK signature) I will add F-Droid keys also.
If keys (signature) are known / unknown keys is shown after a version number, and in ACRA crash report also.
![signature-check](https://cloud.githubusercontent.com/assets/207716/18329338/9fd86cbc-755b-11e6-8c39-f9f0b329161f.png)

**Comment by william-ferguson-au** [comment]
Nice :-)
