### ISSUE TITLE
Onboard AndStatus to Travis CI and SonarQube

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#408]
AndStatus in **Travis CI**: https://travis-ci.org/andstatus/andstatus , [![Build status](https://api.travis-ci.org/andstatus/andstatus.svg?branch=master)](https://travis-ci.org/andstatus/andstatus)
On configuring Android applications to be buit and tested by Travis CI: https://docs.travis-ci.com/user/languages/android

Travis CI will trigger Static Analysis by SonarQube.

AndStatus in **SonarQube**: https://sonarcloud.io/dashboard?id=andstatus , [![Code quality status](https://sonarqube.com/api/badges/gate?key=andstatus)](https://sonarcloud.io/dashboard?id=andstatus)
Short introduction: https://about.sonarqube.com/news/2016/05/02/continuous-analysis-for-oss-projects.html
Gradle build configuration:
http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+Gradle

As you may see, both places are empty yet. We need to make them work together and automatically with each other and the GitHub repository. And provide us information on the application state and quality.

**Comment by yvolk** [comment]
As of now the Travis build, installation and tests launching are done, but the test process itself crashes on the first test case. Maybe some setting in emulator and / or its launch should be changed...

**Comment by yvolk** [comment]
Unfortunately in this case we got:
```
emulator -avd test -netdelay none -netspeed full &
emulator: WARNING: Increasing RAM size to 1GB
SDL init failure, reason is: No available video device
```
So we have to skip UI tests somehow...

**Comment by yvolk** [comment]
At last Travis build works as expected. Currently I marked 6 test classes with "@Travis" annotation, and they are being executed. Will add others (which doesn't use UI) later.

**Comment by yvolk** [comment]
At last I defined actual value of $SONAR_TOKEN in Travis repository settings, see https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings.
I generated the token at SonarQube -> My Account -> Security -> Tokens section

**Comment by yvolk** [comment]
AndStatus onboarded to Travis CI, but this doesn't mean that everything works like a clockwork.
Travis CI explicitly states that Android support is in Beta stage yet, so no wonder it works only sometimes. In particular, emulator works OK one in three times. Usially it ends with the error message: "Skipping device 'test(AVD)' for 'app:debugAndroidTest': Unknown API Level”, but sometimes the same configuration works...
The newest problem: "failed to find Build Tools revision 24.0.2"

**Comment by yvolk** [comment]
SonarQube support team helped me to solve all known problems (See Pull request #414 ). The latest 3 builds are green.

**Comment by yvolk** [comment]
As I see problem with starting Android emulator may be due too wrong emulator configuration. In the Travis log I see:
```
6.47s$ echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
Android 7.0 is a basic Android platform.
Do you wish to create a custom hardware profile [no]Created AVD 'test' based on Android 7.0, ARM (armeabi-v7a) processor,
with the following hardware config:
hw.cpu.model=cortex-a8
hw.lcd.density=240
hw.ramSize=512
vm.heapSize=48
```
"512" MB RAM size is definitely not enough to run Android 7.0

**Comment by yvolk** [comment]
After switching emulator from API-24 to API-23 Travis CI started to work, mostly.

**Comment by yvolk** [comment]
Travis CI builds are unreliable due to problems with emulator, including its too long startup.
Need to check latest solution at https://github.com/travis-ci/travis-ci/issues/6122

**Comment by yvolk** [comment]
I created an issue for Travis.ci team on the problem "Android emulator doesn't fully start since June 18": https://github.com/travis-ci/travis-ci/issues/7981

**Comment by yvolk** [comment]
Yesterday and today I did a lot of attempts to revive the Travis build, but unfortunately I couldn't: Android emulator doesn't start whatever configuration I set.
I tried different emulator APIs and different ABIs...
I ended practically where I started: getting the message: "Timeout (30 minutes) reached. Terminating "android-wait-for-emulator""

**Comment by andigor** [comment]
Hi.

I am facing with the same problem you've described above. I am running few android tests using emulator 
`
echo no | avdmanager.bat create avd --force --name test -k "system-images;android-24;default;armeabi-v7a"
`
I am waiting for booting using `adb -s emulator-5554 shell getprop sys.boot_completed` and then 5 minutes more with simple sleep. But that does't help. From time to time tests run 
`
./gradlew testAppAndroid:connectedAndroidTest
`
fails:

`
11:04:52.027 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':testAppAndroid:connectedReleaseAndroidTest'.

11:04:56.667 [INFO] [org.gradle.api.Task] Skipping device 'automatedtestvd(AVD)' for 'testAppAndroid:': Unknown API Level

11:04:56.672 [WARN] [org.gradle.api.Task]
 
 : No compatible devices connected.[TestRunner] FAILED
`

Have you found a fix for your issue ?

**Comment by yvolk** [comment]
@andigor No solution yet, hope this problem will be noticed at https://github.com/travis-ci/travis-ci/issues/7981

**Comment by yvolk** [comment]
Currently Bulds in Travis CI work, although on some outdated API... , so I'm closing this issue.
