### ISSUE TITLE
some avatars not syncing

### ISSUE THREAD

**Issue by bulletbites** [andstatus/andstatus#409]
Some avatars not updating their thumbs:
![avatars1](https://cloud.githubusercontent.com/assets/17816155/17647152/39797d2c-61e6-11e6-9d4d-e47247cd447b.png)
Not just in the mentionTL btw.

**Comment by bulletbites** [comment]
Still have the WHITE avatars bug going on. Any progress getting a avatar thumbs refresh or reload fix?

**Comment by yvolk** [comment]
In order to find out, why some avatars are not loaded, I need to know exact URLs of them. 
Please do this: 
1. Open context menu of a message, having white avatar, and select "Users of Message" menu item.
2. In the list of users select again that user without an avatar and open its context menu. Select "Get User Information" from the menu and wait till sync completes.
Q1. Did this help?
If not, go to "Commands in a Queue” and find a row with an error loading the avatar. Open context menu of that error and select Share in it. Share the error text to a clipboard or email... and post here.

**Comment by bulletbites** [comment]
After 1. & 2. the refreshing is stuck in limbo: 
![screenshot_2016-09-18-17-36-49](https://cloud.githubusercontent.com/assets/17816155/18616996/f2f6bcbe-7dc6-11e6-8675-7271b7ca2ebf.png)
```

error data:

T; empty
Created 33 seconds ago

org.andstatus.app v.29.01 (191) release-keys started 8 hours ago
ImageCaches: Avatars: 64x64, 66 of 410, free: 346, hits:1679, misses:66, hitRate:96%
Attached images: 640x640, 16 of 16, free: 2, hits:86, misses:55, hitRate:60%
Styled drawables: 1
Memory. App total: 128MB; Device: available 220MB of 961MB

Tasks:
Total launched: 1057; running: 2; just finished: 1. Skipped: 202
R 1. HeartBeat 7; org.andstatus.app.service.MyService$HeartBeat on SYNC; age 102sec; RUNNING 102sec; instanceId=2587; org.andstatus.app.service.MyService$HeartBeat@6d19fe6c
R 2. QueueExecutor:{currentlyExecuting: CommandData:{command:fetch-timeline,created:two minutes ago,Timeline{sealion.club, type:public, id:12},hashCode:-494962093,CommandResult:{downloaded:7, messages:4}}, since: 12 seconds ago, org.andstatus.app.service.MyService$QueueExecutor on SYNC; age 12sec; RUNNING 12sec; instanceId=2593; org.andstatus.app.service.MyService$QueueExecutor@c2d3c654}

Thread pools:
SYNC: java.util.concurrent.ThreadPoolExecutor@38e6d24a[Running, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 1]
FILE_DOWNLOAD: java.util.concurrent.ThreadPoolExecutor@1f8c3205[Running, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 119]
QUICK_UI: java.util.concurrent.ThreadPoolExecutor@1acd025a[Running, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 108]
LONG_UI: java.util.concurrent.ThreadPoolExecutor@b9d9c8b[Running, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 80]
DEFAULT: java.util.concurrent.ThreadPoolExecutor@16503168[Running, pool size = 5, active threads = 0, queued tasks = 0, completed tasks = 18]
```

**Comment by yvolk** [comment]
@bulletbites The Stack Trace of an error that you encountered , is not complete, unfortunately. Could you send me the full Crash Report, if that was a crash?!

**Comment by bulletbites** [comment]
it's not crashing it simply isn't updating those avatars and after following step 1 and 2 then I try to refresh by pulling down the loading wheel spins for a while and nothing changed.

**Comment by yvolk** [comment]
Please read my post with an instruction: after point 2 it suggests to lookup "Commands in a Queue ”...

**Comment by bulletbites** [comment]
read that. did send the most recent blurp of code which I thought fitted with my last action (updating the avatar stuff). I will check it out later and will send you a longer batch of the code then.

**Comment by yvolk** [comment]
@bulletbites I suspect that you looked for error log in the wrong place. The ”Command in a Queue” menu item is in the top Action bar, it's hidden under the "overflow button”, which looks like three vertically arranged dots.
This is an example of an error downloading an avatar. I Shared it from the " Commands in a Queue” list to Clipboard and then copied here:
```
E; Avatar for quanto@quitter.is at LoadAverage
Created 6 days ago
executed:1, last:6 days ago, retriesLeft:9, error:Hard,  
Status code=NOT_FOUND; hard; 
statusLine:'HTTP/1.1 404 Not Found'; retrying without authentication; statusLine:'HTTP/1.1 404 Not Found'; statusLine:'HTTP/1.1 404 Not Found'; statusCode:NOT_FOUND (404); url:'https://loadaverage.org/avatar/348061-48-20160702215656.png'; response:'<html>
<head><title>404 Not…'; saved to file; error='?'; 
Caused by org.json.JSONException: Value <html> of type java.lang.String cannot be converted to JSONObject, downloadFile; userId=14915; uri=https://loadaverage.org/avatar/348061-48-20160702215656.png; 
```

**Comment by bulletbites** [comment]
@yvolk I've recorded my actions:
https://youtu.be/Lx6ws1akOxY

This is what I get:

```
T; empty
Created 3 minutes ago

org.andstatus.app v.29.01 (191) release-keys started two hours ago
ImageCaches: Avatars: 64x64, 26 of 410, free: 386, hits:1931, misses:26, hitRate:98%
Attached images: 640x640, 9 of 16, free: 9, hits:53, misses:18, hitRate:74%
Styled drawables: 1
Memory. App total: 128MB; Device: available 205MB of 961MB

Tasks:
Total launched: 186; running: 0. Skipped: 3

Thread pools:
SYNC: java.util.concurrent.ThreadPoolExecutor@204c1efa[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
FILE_DOWNLOAD: java.util.concurrent.ThreadPoolExecutor@c4eecdc[Running, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 62]
QUICK_UI: java.util.concurrent.ThreadPoolExecutor@17ee11e5[Running, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 14]
LONG_UI: java.util.concurrent.ThreadPoolExecutor@35ef94ba[Running, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 21]
DEFAULT: java.util.concurrent.ThreadPoolExecutor@382f2f6b[Running, pool size = 2, active threads = 0, queued tasks = 0, completed tasks = 2]
```

**Comment by yvolk** [comment]
@bulletbites From what I saw in your video, it looks like AndStatus thinks that these users don't have avatars at all. This is why you don't see any error messages regarding avatars of these users in the "Commands in a Queue".

Maybe this is caused by unusual file extension?!

Or maybe the avatar was downloaded successfully, but for some reason it could not be shown in AndStatus?!

We could figure out the cause of the misbehaviour if you send me a .json file, which is returned by the sealion.club server for your "Get User Information" request. To get this file, you need to turn on "Log network level messages". See https://github.com/andstatus/andstatus/issues/225

**Comment by bulletbites** [comment]
@yvolk I set the parameters to start logging stuff and did some syncing, updating character information fetching, etc and my log dir shows up totally empty still?

**Comment by yvolk** [comment]
@bulletbites Do you see database files in ”databases” folder at the same level as the ”logs” folder (see #225 )
?
If no, try to search on another ”storage”. BTW, what version of Android has your device?

**Comment by bulletbites** [comment]
@yvolk https://youtu.be/bYozaz8RHik

**Comment by bulletbites** [comment]
@yvolk so I re-installed Andstatus and blitzed through it with all the logging parameters set and it gave me a error. I then re-installed again and left the logging stuff untouched and so far both avatar thumbs and repost/fav action simply WORK! Still testing it and will give you logging/debugging info once I have tingered with this fresh install a bit.

**Comment by yvolk** [comment]
You need to search in some other storage/SD card...
I will add information on current path of log files to AndStatus Settings...

**Comment by bulletbites** [comment]
got it sorted: it actually stores it on the local sd (not external): all the logs created since fresh install:
[Bestanden_gedownload_door_AirDroid.zip](https://github.com/andstatus/andstatus/files/504481/Bestanden_gedownload_door_AirDroid.zip)

**Comment by yvolk** [comment]
As I see, you didn't include logs taken at "17:40 - 17:41" when you recorded your video, so I cannot tell anything about "Craig"... Please look it up!

**Comment by yvolk** [comment]
@bulletbites Thank you for your video. You showed me, what it not as well as it could be :-)

**Comment by bulletbites** [comment]
@yvolk at this point the "old logs" are redundant. The solution to my problems was delete/re-install AndStatus. It's a shitty bugfix but for now you can file the issue solved by: reinstall clearing all the bugs on avatars not syncing / retweets & favs not working. They both work now and I'll report back if any issues arise.

**Comment by yvolk** [comment]
@bulletbites Anyway I fixed endless swipe refresh indicator on a "Users of Message" list...
