### ISSUE TITLE
Addidional Font sizes

### ISSUE THREAD

**Issue by vinzv** [andstatus/andstatus#411]
Can we get two more font sizes:
* smaller
* bigger

For me small is too small and medium is too big.

**Comment by yvolk** [comment]
Currently we have three font sizes, defined in standard Android styles. See e.g. http://stackoverflow.com/questions/11590538/dpi-value-of-default-large-medium-and-small-text-views-android
Adding more options means potential incompatibility on some devices... but why not? I may add ”(experimental)" note to such additional sizes.

**Comment by vinzv** [comment]
Yeah, we could try. As long as no one complains it's a small improvement.
