### ISSUE TITLE
Andstatus defaults to an arbitrary or strange timeline

### ISSUE THREAD

**Issue by EricxDu** [andstatus/andstatus#413]
Whenever I open AndStatus from the icon, or return from a conversation view by pressing the button in the upper left corner of the app, AndStatus loads an odd "default" timeline. For a while it was "Friends Combined", but for a long time now it's been "Search 'hishgraphics'".

I think I've done nothing in Settings to cause this behavior; it just started on it's own, and changed itself arbitrarily after I performed a search for "hishgraphics". When I look in Settings->Timeline, there is an option called Manage Timelines that says "Timeline that will be opened by a Launcher: "Search 'hishgraphics' combined" that I never specified, and under it is a list of timelines with checkboxes --some checked, some not-- which don't give me a clue how this behavior started or how to fix it for good.

**Comment by yvolk** [comment]
@EricxDu I also noticed that in v.27 there is no concrete default Timeline until you set one explicitly in the Manage timelines view. 
See https://github.com/andstatus/andstatus/issues/395

In v.28 this is fixed: If not set explicitly in the "Manage Timelines" view, Home Timeline of the Default Account is now the Default Timeline - it opens on the Application launch. This is natural for new users and simplifies initial configuration. 
See http://andstatus.org/changelog.html

v.28 is in the Open Beta testing channel https://play.google.com/apps/testing/org.andstatus.app

**Comment by EricxDu** [comment]
This is good news, thanks. I'll be awaiting .28
--
Eric Duhamel
http://noxbanners.net/

**Comment by EricxDu** [comment]
Seems to be fixed at least by AndStatus v.29
