### ISSUE TITLE
Show both a message creation date and a date of its latest update

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#417]
In a Timeline AndStatus shows a date of creation, not a date of update or reblog/retweet. But it sorts tweets by dates of updates/retweets.
This is why old tweet, which was retweeted or updated recently, appears above tweets, which were created earlier than creation, but later than retweet of this tweet.

This confuses sometimes: you don't understand, if you are looking at old part of a timeline, or at a new but with old messages updated...

We need an option to show both dates. Presumably, showing both dates is not needed, when they are the same / close to each other.

Another aspect of this problem: if we need / can SHOW the same message in two places of a Timeline: when it was created, and when it was last updated/retweeted etc...

So, we need to discuss, what to do and how exactly a User should see this.

**Comment by yvolk** [comment]
The problem was mostly solved, when AndStatus started showing Activities, and not "Notes/Tweets" only. so e.g. for Reblog activities we see both dates: the date of the reblog and the date of the reblogged note.

**Comment by vaschw** [comment]
Is it possible to (optionally) change the sort order, so that the posts are sorted by post date rather than the date on which they got "liked" (or otherwise updated)?

**Comment by yvolk** [comment]
Hi @vaschw! This thread ("issue") is many years old. Since that time AndStatus changed its internal data model largely. Mostly following ideas of Activity Streams and appeared later ActivityPub protocol.
Now "likes" or "retweets" DON'T UPDATE original message (called a "Note" in the modern terminology, see https://www.w3.org/TR/activitypub/ ).
Now most of timelines show Activities (actions), not "Notes". Thus sorting by a date of an Activity.

In this context your wish means an option to "Show Notes instead of Activities" in current timeline. With natural sorting by a date of a Note.
?!

**Comment by vaschw** [comment]
Yes, I think you have described the option I am asking for.  In some cases it may be nice to view things in the order that the Activities happened (as the AndStatus Home Timeline currently does).  In other cases, I may want the option to see the order that Notes were written in -- so that the date of a "like" does not change the ordering.

Is this a feature that already exists?  I cannot find it.

**Comment by yvolk** [comment]
No such a feature yet. I will need to add it. I created a separate issue for that.
