### ISSUE TITLE
Add driver for Mastodon

### ISSUE THREAD

**Issue by Gargron** [andstatus/andstatus#419]
I might do this one myself later. An API wrapper for the [Mastodon](https://github.com/Gargron/mastodon) networks needs to be added.

This depends on https://github.com/Gargron/mastodon/issues/45

[API documentation](https://github.com/Gargron/mastodon/wiki/API)

**Comment by yvolk** [comment]
Glad to hear .:-)
Ask me if you need any help

**Comment by Gargron** [comment]
So I implemented an API like this:

POST /api/apps with form data "name" and "redirect_uri", returns "id" (of app), "client_id" and "client_secret" (for OAuth). Do you think that's enough to get started?

**Comment by yvolk** [comment]
@Gargron You wrote than you are planning to implement authentication similar to Pump.io?!
If yes you can use AndStatus as a testing tool of your implementation. You should be able to add an account in AndStatus at your Social Network.
AndStatus can log all network-level messages as separate JSON file plus it can save all logs to .log files. See https://github.com/andstatus/andstatus/issues/225

1. Please create new Social network called ”Mastodon” of Pump.io ”type” (later we will add a separate type for it...)
2. Turn on all logging, make it Verbose.
3. Try to add new account to your network. 
You will immediately see, what is OK and what is needed to be done. I would suggest to adapt your OAuth user/client registration API to the one of Pump.io - this would be simpler for the start...
You can use debugger in Android Studio to understand a process better...

**Comment by Gargron** [comment]
@yvolk Where would I create the new network?

**Comment by yvolk** [comment]
I mean in AndStatus -> Settings -> Accounts -> Manage Social Networks -> Plus icon on the top right

**Comment by Gargron** [comment]
"No client keys for the host yet; registerClient; for https://mastodon.social; URL='https://mastodon.social/api/client/register'" - a predictable error given that the path for client reg should be /api/v1/apps

I think the type needs to be added before anything else can be done because as far as I've read through your code that's where API paths are specified. I just haven't figured out how it interacts with the UI...

**Comment by yvolk** [comment]
For testing purposes you can change pump.io setting in https://github.com/andstatus/andstatus/blob/master/app/src/main/java/org/andstatus/app/origin/OriginType.java

**Comment by yvolk** [comment]
..or maybe even better here: https://github.com/andstatus/andstatus/blob/master/app/src/main/java/org/andstatus/app/net/social/pumpio/ConnectionPumpio.java
See getApiPath1 method

**Comment by Gargron** [comment]
Thanks! So if I started implementing the driver I would add a new enum (and another case for constructor) to OriginType.java and a new class that extends Connection. Anything else?

**Comment by yvolk** [comment]
Actually these two places are the only places, were specifics of a Social network are hardcoded.

**Comment by yvolk** [comment]
Or, and some strings in resources...

**Comment by yvolk** [comment]
And you may also notice a class extending Origin, e.g. OriginPumpio

**Comment by yvolk** [comment]
@gargron And another note on current implementation. It's not carved in a stone and sometimes I redactor it dramatically. So maybe after you have completed integration of Mastodon, I will clean this up another time...

**Comment by Gargron** [comment]
@yvolk I tried compiling the app in Android Studio, but got the following error. Help?

```
$ adb shell am start -n "org.andstatus.app/org.andstatus.app.msg.TimelineActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Connected to process 2620 on device Nexus_5_API_24 [emulator-5554]
I/art: Not late-enabling -Xcheck:jni (already on)
W/art: Unexpected CPU variant for X86 using defaults: x86
W/System: ClassLoader referenced unknown path: /data/app/org.andstatus.app-1/lib/x86
I/InstantRun: Instant Run Runtime started. Android package is org.andstatus.app, real application class is org.andstatus.app.context.MyApplication.
W/System: ClassLoader referenced unknown path: /data/app/org.andstatus.app-1/lib/x86
V/MyApplication: attachBaseContext started
I/ACRA: Migrating unsent ACRA reports to new file locations
I/ACRA: Migrated 0 unsent reports
I/ACRA: ACRA is enabled for org.andstatus.app, initializing...
I/TamperingDetector: Unknown APK signature:'o7s4dDfhSd13YxB+jag61rQhJk8='
W/MyContextImpl: Incompatible context: com.android.tools.fd.runtime.BootstrapApplication
V/MyContextImpl: newCreator by MyProvider
D/AndroidRuntime: Shutting down VM
E/ACRA: ACRA caught a RuntimeException for org.andstatus.app
        java.lang.RuntimeException: Unable to get provider org.andstatus.app.data.MyProvider: java.lang.IllegalStateException: MyContextHolder: no compatible context, called by MyProvider
            at android.app.ActivityThread.installProvider(ActivityThread.java:5814)
            at android.app.ActivityThread.installContentProviders(ActivityThread.java:5403)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5342)
            at android.app.ActivityThread.-wrap2(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:154)
            at android.app.ActivityThread.main(ActivityThread.java:6077)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
         Caused by: java.lang.IllegalStateException: MyContextHolder: no compatible context, called by MyProvider
            at org.andstatus.app.context.MyContextHolder.storeContextIfNotPresent(MyContextHolder.java:235)
            at org.andstatus.app.data.MyProvider.onCreate(MyProvider.java:55)
            at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
            at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
            at android.app.ActivityThread.installProvider(ActivityThread.java:5811)
            at android.app.ActivityThread.installContentProviders(ActivityThread.java:5403) 
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5342) 
            at android.app.ActivityThread.-wrap2(ActivityThread.java) 
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528) 
            at android.os.Handler.dispatchMessage(Handler.java:102) 
            at android.os.Looper.loop(Looper.java:154) 
            at android.app.ActivityThread.main(ActivityThread.java:6077) 
            at java.lang.reflect.Method.invoke(Native Method) 
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
I/Process: Sending signal. PID: 2620 SIG: 9
Application terminated.
```

**Comment by yvolk** [comment]
Please turn off "Instant Run" in Android Studio settings

**Comment by Gargron** [comment]
That worked. However, I've tried adding the class stubs hoping that it would at least work up to the client registration step, however, when trying to "Add this account" from the UI I get an exception.

Commit: https://github.com/Gargron/andstatus/commit/55681d0cc24fdd482f29b8d8fcdd01d3754f6b8d

Exception: 

```
V/Builder: Get Origin config failed
V/MyAccount.Builder: Registering client application for 
V/OAuthClientKeysDynamic: OriginUrl is null; HttpConnectionData {/mastodon.social, isSsl:true, sslMode:SSL mode:SECURE, basicPath:api/v1, oauthPath:oauth, originUrl:null, hostForUserToken:null, dataReader:org.andstatus.app.account.AccountData@bf696bc5, oauthClientKeys:null}
D/OAuthClientKeys: Loaded OAuthClientKeysDynamic-; No keys
V/ConnectionMastodon: API 'REGISTER_CLIENT' Path=api/v1/apps
D/UrlUtils: pathToUrlString, originUrl:'null', path:'api/v1/apps'
            java.net.MalformedURLException: no protocol: api/v1/apps
                at java.net.URL.<init>(URL.java:589)
                at java.net.URL.<init>(URL.java:486)
                at org.andstatus.app.util.UrlUtils.pathToUrlString(UrlUtils.java:114)
                at org.andstatus.app.net.http.HttpConnection.pathToUrlString(HttpConnection.java:54)
                at org.andstatus.app.net.http.HttpConnectionOAuthJavaNet.registerClient(HttpConnectionOAuthJavaNet.java:60)
                at org.andstatus.app.net.social.Connection.registerClientForAccount(Connection.java:408)
                at org.andstatus.app.account.MyAccount$Builder.registerClient(MyAccount.java:474)
                at org.andstatus.app.account.AccountSettingsActivity$OAuthRegisterClientTask.doInBackground2(AccountSettingsActivity.java:787)
                at org.andstatus.app.account.AccountSettingsActivity$OAuthRegisterClientTask.doInBackground2(AccountSettingsActivity.java:758)
                at org.andstatus.app.os.MyAsyncTask.doInBackground(MyAsyncTask.java:89)
                at android.os.AsyncTask$2.call(AsyncTask.java:304)
                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                at java.lang.Thread.run(Thread.java:761)
E/OAuthRegisterClientTask: Status code=OK; hard; 
                           URL is unknown. System URL:'null', path:'api/v1/apps'
                               at org.andstatus.app.util.UrlUtils.pathToUrlString(UrlUtils.java:121)
                               at org.andstatus.app.net.http.HttpConnection.pathToUrlString(HttpConnection.java:54)
                               at org.andstatus.app.net.http.HttpConnectionOAuthJavaNet.registerClient(HttpConnectionOAuthJavaNet.java:60)
                               at org.andstatus.app.net.social.Connection.registerClientForAccount(Connection.java:408)
                               at org.andstatus.app.account.MyAccount$Builder.registerClient(MyAccount.java:474)
                               at org.andstatus.app.account.AccountSettingsActivity$OAuthRegisterClientTask.doInBackground2(AccountSettingsActivity.java:787)
                               at org.andstatus.app.account.AccountSettingsActivity$OAuthRegisterClientTask.doInBackground2(AccountSettingsActivity.java:758)
                               at org.andstatus.app.os.MyAsyncTask.doInBackground(MyAsyncTask.java:89)
                               at android.os.AsyncTask$2.call(AsyncTask.java:304)
                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                               at java.lang.Thread.run(Thread.java:761)
D/AccountSettingsActivity: Authentication Failed: URL is unknown. System URL:'null', path:'api/v1/apps'
```

I've added the server type from "Manage accounts" -> "Add account" -> "+" -> type "Mastodon", host: "mastodon.social", SSL enabled, other options are probably irrelevant, finally back to "Manage accounts" -> "Add account" -> "mastodon.social" -> "Add this account"

**Comment by Gargron** [comment]
Interestingly, when I edit the entry from "manage social networks", the host field is empty. Does it not get saved for some reason?

**Comment by yvolk** [comment]
For pump.io only there is no single host. This is why the host field is empty for this type of Social network.
Host is derived from user's/account's WebFinger Id. See org.andstatus.app.net.social.pumpio.ConnectionPumpio#enrichConnectionData

**Comment by yvolk** [comment]
This is why _one_ "Pump.io" entry is enough for _all_ pump.io sites.

**Comment by yvolk** [comment]
Regarding ability to save host URL:
canSetUrlOfOrigin = true; in OriginType

**Comment by yvolk** [comment]
@Gargron I would recommend you to set two pump.io accounts in two different hosts and play with them in And?Status, seeing that this is _really_ one federated network with unique URIs for Users and messages... Maybe you will do something like this for GNU Social?!

**Comment by Gargron** [comment]
Okay, client registration works (in that an app is definitely created on the server, not sure if AndStatus saves the keys properly given that the next step fails): https://github.com/Gargron/andstatus/commit/ad1e401d1dcf20412c1356b4c91350ca97b67f17

Now the next thing it was trying to do is /oauth/request_token. However, I'm not sure what that is supposed to be exactly? [Doorkeeper](https://github.com/doorkeeper-gem/doorkeeper/wiki/API-endpoint-descriptions-and-examples) does not have a URL like that, it has an /oauth/token though, so I tried subclassing the HttpConnection and changing the path to that, however that also does not work. In my understanding, what *should* happen as next step after client registration, the user should be redirected to /oauth/authorize on the website to login via a webview or something like that and click "authorize application", which will create an access token. What am I doing wrong here?

**Comment by yvolk** [comment]
OAuth is a misty part and AFAIK it could be implemented differently. AndStatus implements OAuth for Twitter and for Pump.io. As I remember, in both cases I used working examples to do this in AndStatus.
So I can only suggest for you:
1. To study code of AndStatus + 
2. Debug OAuth procedures step-by-step
3. Turn all logging on, including logging network level messages to file...

**Comment by Gargron** [comment]
It seems like signpost, the library you are using for OAuth, is an OAuth 1.0 library, whereas my API is covered by OAuth 2.

**Comment by yvolk** [comment]
Recently I was told that Twitter doesn't support OAuth 1, but AndStatus still works with it...
Anyway, you are free to add OAuth 2.0 library for your system, we will think later, how to optimize this in one application... 
In order for authentication to work, I would suggest for you to borrow any working Java example for that "Doorkeeper"...

**Comment by yvolk** [comment]
@Gargron As you may have noticed already, currently two existing OAuth implementations use different Java libraries (different HttpConnection subclasses in AndStatus). You can try to switch them?!
If this doesn't help, you will have to create the third subclass...

**Comment by Gargron** [comment]
@yvolk Can you help me out? I'm afraid I can't do this - I think I would be able to make a from-scratch app that connects to the API, but the integrations with the existing code are the hard part

**Comment by yvolk** [comment]
Ok, just write an Android application (with one empty activity, e.g. from an Android template...), using any libraries, that can, using hard-coded username and password, connect to your server and request Home timeline for the User.
So we will know:
1. Client registration works
2. Authentication works.
I then integrate this into AndStatus, so next steps will be easier.
?!

**Comment by yvolk** [comment]
It looks like this is the easiest start to OAuth2: https://github.com/scribejava/scribejava

**Comment by mike-burns** [comment]
Would it be easier to make Mastodon support the GNU Social API? (Or is that fundamentally impossible?)

**Comment by Gargron** [comment]
The GNU social API is an outdated/incomplete Twitter API. I don't want to go that route. My issue with this is less with the API itself and more with that I've never done web/json stuff with Java.

**Comment by yvolk** [comment]
@mike-burns Actually currently we are blocked by implementation of Authentication/authorization via the [Doorkeeper](https://github.com/doorkeeper-gem/doorkeeper), "awesome oauth provider", selected for Mastodon.
It appears that there is _no_ any implementation of an Android client for that OAuth provider...

@Gargron Maybe we better consider some alternative OAuth implementation at the server-side?! E.g. one of tens that are listed among supported systems here: https://github.com/scribejava/scribejava
?!

**Comment by Gargron** [comment]
Doorkeeper is just OAuth 2.0, nothing special. /authorize and /token are pretty much the only end-points we need to care about (first is authorization URL aka where user clicks "allow this application access" and second is where the access code from authorization callback redirect can be turned into access token). But honestly I'm writing this "example Android app" and where I'm stuck is HTTP requests and JSON parsing? I tried Unirest but it's incompatible with Android, turns out.

**Comment by Gargron** [comment]
@yvolk Done: https://github.com/Gargron/mastodon-java-api-example

**Comment by yvolk** [comment]
@Gargron Thank you. I tried it and it works :-)
Now the ball is in my court.

**Comment by yvolk** [comment]
@Gargron Now "Verify credentials" request works but fails to parse the User object returned:
```
{
  "id": 5962,
  "username": "AndStatus",
  "acct": "AndStatus",
  "display_name": "",
  "note": "",
  "url": "https:\/\/mastodon.social\/users\/AndStatus",
  "avatar": "https:\/\/mastodon.social\/avatars\/large\/missing.png",
  "header": "https:\/\/mastodon.social\/headers\/medium\/missing.png",
  "followers_count": 0,
  "following_count": 0,
  "statuses_count": 0
}
```
It's not a problem for me to "parse" this, but I see that this is _not_ what supposed to be an "Activity streams" format for a federated API ?!
From the first look I see these problems:
1. "id" is a local id, like in Old Twitter API, but should be URI, e.g. "acct:andstatus@mastodon.social"
2. no "objectType":"person" ... (like I see in Pump.io ...) to know, what "object" you got in the response...

?!

**Comment by yvolk** [comment]
Please look here for ActivityStreams responses: https://github.com/andstatus/andstatus/tree/master/app/src/androidTest/res/raw
They are not ideal and of course don't conform to ActivityStreams 2.0, but at least proved to be working API

**Comment by Gargron** [comment]
You're right, it's not activity streams. Since this is the client-to-server API and not server-to-server? The `id` field always represents the local copy of the object, the `url` links to either local or remote profile, and `acct` is username@domain (@domain is omitted for local users). On the other hand you always know what object you get from the response based on the API URL, e.g. `/api/v1/accounts/verify_credentials` always returns a user, as does `/api/v1/accounts/:id`, while `/api/v1/statuses/:id` always returns a status, etc. You will find that I always mention the kind of object returned in the API docs, and at the bottom of the docs is a table of all fields of the entities the API returns (there are only two, Account and Status)

**Comment by yvolk** [comment]
@Gargron You are describing to me an API, invented 10+ years ago, for a centralized system.
(4 years ago Pump.io was created, as I understand, exactly to overcome shortcomings of this approach...)
This is why I think we should implement the new API so that client would no longer be a crippled view of one single GNU Social instance but a peer, aware of the whole network, being able to see it as one federation, not as a bunch of not related systems, as today's Twitter API allows.
So please provide ActivityStreams as a client API also.
Ok?

**Comment by yvolk** [comment]
Regarding local IDs: I think that local IDs should not be used in API in any case. Even if you would refuse to implement ActivityStreams  as a Client API (for some reason...)

**Comment by yvolk** [comment]
Regarding explicit declaration of the objectType inside an object:
Although objectType can be figured out based on a context/API used, I think that as in a general case the object does have its objectType as a required part of its metadata, it should have the same format and the same minimal amount of metadata in any context. This allows to have simpler interface / parsing logic with stronger data validation.

**Comment by Gargron** [comment]
Let me explain my position.

There is no trade-off in having and using a local ID to refer to entities. To interact with anything in the fediverse, your server needs to know it first. If the server knows it (aka it's in the DB) then it already has a local ID. The only times you don't have a local ID is when you're introducing something to your server for the first time, like a user to follow or a remote status to load - those are explicit steps that take a remote identifier like username@domain or a URL to the status page or Atom feed and return the local representation of that object. Why does a client app need to bother with URIs when IDs serve the very same purposes but are much simpler to handle? Besides, the statuses do have a `uri` attribute along with `id`, and accounts have `acct`.

**Comment by yvolk** [comment]
And another case of AndStatus usage, when having URIs is a must: 
"Global search". I use this quite often to monitor talks about AndStatus in different GNU Social instances.
Without URIs I had to implement its dirty substitute: "fuzzy matching logic", which searches for "duplicates" and collapses them. See https://github.com/andstatus/andstatus/issues/337

**Comment by Gargron** [comment]
As I said `uri`s are returned alongside `id`s

**Comment by yvolk** [comment]
If I can ignore local IDs completely, then this is ok. I will just use "uri" instead of "id".
Please ensure that we can query a server with such URIs also. I.e. "Get message"/Conversation/User by their URIs.

**Comment by yvolk** [comment]
@Gargron I just checked the Verify Credentials operation again: still no "uri" in the "person" object :-( (see its JSON above - it's still the same!)
Please fix.

**Comment by Gargron** [comment]
So statuses have a literal `uri` field, but accounts have an `acct` field. This could be the URI you're looking for, depending on the format you're expecting... Some Atom feeds list the profile URL as URI, in that case perhaps you would use the `url` field of the account. But if you prefer `username@domain` format (which I do!) then `acct` is it. Except it omits `@domain` for local accounts, but you can simply add that to the string on your end. Does that help?

**Comment by yvolk** [comment]
I thought that you want to implement good API where all things have have their proper names and content. But currently we are figuring out how to adapt what we have for a better usage :-(
Why are you sticking to the existing client API? Don't you want to make it better?

**Comment by yvolk** [comment]
@Gargron BTW, what URI should I use for e.g "GET /api/v1/accounts" request?
- this should be EXACTLY the same URI that client receives in the "Verify Credentials" request.

**Comment by yvolk** [comment]
@Gargron If you are a "Coder" and not an Architect - I can understand this: take a good client API from Pump.io and implement it
?!

**Comment by yvolk** [comment]
@Gargron While waiting for your feedback I cleaned OAuth2 implementation and even added (temporary) a hack for misbehaved mastodon.social authorization flow (without it "Authorize" page doesn't appear automatically after "Log in" page. The same in your Android example).

**Comment by Gargron** [comment]
I fixed the login/authorization page redirect and added scopes to the API: "read", "write" and "follow". AndStatus will need all 3. So the authorization URL must receive another query string param like this `scope=read+write+follow`

Can't answer about the other stuff yet

**Comment by yvolk** [comment]
I added explicit scopes.
But still no redirect from sign_in page to authorization. Instead, after successful sign_in a client is redirected to the root page of the host:
```
10-22 20:04:16.341 26750-26750/org.andstatus.app V/WebViewListener: onPageStarted: https://mastodon.social/auth/sign_in
10-22 20:04:16.642 26750-26750/org.andstatus.app V/WebViewListener: onPageStarted: https://mastodon.social/
10-22 20:04:16.643 26750-26750/org.andstatus.app D/WebViewListener: A hack for misbehaving Mastodon.social
# And here I redirect manually:
10-22 20:04:16.851 26750-26750/org.andstatus.app V/WebViewListener: onPageStarted: https://mastodon.social/oauth/authorize?scope=read%20write%20follow&response_type=code&client_id=111111122223333&redirect_uri=http%3A%2F%2Foauth-redirect.andstatus.org
```

**Comment by Gargron** [comment]
Alright, I'll keep debugging

**Comment by Gargron** [comment]
Okay, finally did fix it, and tested it as well.

**Comment by hsoc** [comment]
any updates on this? :-)

**Comment by yvolk** [comment]
@hsoc Waiting for @Gargron to decide on a way to improve existing API...

**Comment by Gargron** [comment]
Question: Doesn't GNU social API, which is actually the legacy Twitter API, not also deal with local IDs? In that case, don't you have deduplication/normalization logic in the code? I haven't gotten around to doing anything to the API recently, focusing more on internals and UI, except for these improvements:

/api/v1/statuses/home is now /api/v1/timelines/home (same for mentions, public, and tag/:tag (that one's for hashtags)). All collections now return a `Link` header that contains next/previous links to traverse the collection.

**Comment by yvolk** [comment]
Every "Social network" in terms of AndStatus has a separate "namespace" of IDs. 
Every User / Message MUST have unique ID inside one "Social network".
Deduplication of Users/Messages is done by their IDs only inside a "Social network".

As currently each GNU Social instance provides to a client User/Message objects with local IDs only, we need to have a separate "Social Network" for each GNU Social instance in AndStatus. In this sence in AndStatus "One GNU Social instance" is the same as "the whole Twitter" (because Twitter _is_ one instance from a client's point of view).
Whereas each Pump.io instance provides to a client User/Message objects with GUIDs (URIs) allowing to have ONE "Social Network" in AndStatus for ALL Pump.io instances hence "deduplication" is done in the scope of the whole "pumpiverse".

Is this what you wanted to know?

**Comment by Gargron** [comment]
Yes. In that case could we please do it the "old way" first? I can see too many complications arising from changing the API in this way.

**Comment by yvolk** [comment]
OK, so "Mastodon" "Social network type" in AndStatus will be similar to GNU Social, but:
1. Have mandatoty OAuth authentication.
2. Doesn't implement something from GNU Social API.
3. Have different URLs for methods that exist in GNU Social's "Twitters compatible" API.
4. Maybe have some additional methods, which don't exist in GNU Social.
5. Maybe have different structure/names of input/output values for methods, which exist in GNU Social

As at this step we are not doing any major improvements except OAuth, please let's minimize differences to points 1+ 2 or maximum to points 1 + 2 + 3 ?!
This will greatly help in maintenance of the new API.

**Comment by yvolk** [comment]
@Gargron I'm waiting for your confirmation / your choice on my previous comment. Do you have any updates on this?

**Comment by rodneyrod** [comment]
Has there been any progress on this?

**Comment by yvolk** [comment]
@Gargron On the weekend I tested account authentication part that we did last year: it stopped working. What's strange is that the only OAuth "scope" that finally worked, was "read" meaning that I cannot post from AndStatus...

**Comment by yvolk** [comment]
I implemented basic support of the "Mastodon" type Social network. Currently user can create an account and read Home and Public timelines.
Unfortunately, posting doesn't work due to a problem with authorization. for some reason, authorization works for OAUTH "read" scope only.
@Gargron or maybe somebody else, Could you look, why e.g. uncommenting the line 61 with OAUTH_SCOPES in https://github.com/andstatus/andstatus/blob/master/app/src/main/java/org/andstatus/app/net/http/HttpConnectionOAuthMastodon.java leads to authorization error.
`additionalParams.put(OAuthConstants.SCOPE, OAUTH_SCOPES);`
?!
With this line commented out read-only authorization is provided.
Please note that during client application registration I do use the three OAUTH_SCOPES "read write follow" (in https://github.com/andstatus/andstatus/blob/master/app/src/main/java/org/andstatus/app/net/http/HttpConnectionOAuth2JavaNet.java )

**Comment by anarcat** [comment]
is there a release planned for this? i'd love to see mastodon support land in andstatus! :)

**Comment by yvolk** [comment]
@anarcat I hope so,  please opt- in for beta testing here: https://play.google.com/apps/testing/org.andstatus.app

**Comment by anarcat** [comment]
unfortunately I do not use Google's services... I'd love to test a beta on fdroid though. :)

-- 
Sent with a touch screen device. Please excuse my brievety.

**Comment by yvolk** [comment]
@anarcat AndStatus for Beta testing is available here: https://github.com/andstatus/andstatus/issues/456

**Comment by yvolk** [comment]
Support of #Mastodon client API is mostly implemented and released in v.33 of AndStatus. We will create separate focused "issues"-requests for additional improvements.

**Comment by yvolk** [comment]
I see that several months later Mastodon project started to go the way of ActivityPub,  Activity Streams and Globally unique identifiers. At least for server to server communications.
Unfortunately, I don't see similar changes in the server to client protocol yet...
https://github.com/tootsuite/mastodon/issues/1557
