### ISSUE TITLE
pump.io, first message: AndStatus crashes on "Users of message"

### ISSUE THREAD

**Issue by clacke** [andstatus/andstatus#426]
Steps to reproduce:

1. Create a fresh user account (or use an existing one if you don't mind scrolling to its birth).
2. Connect using AndStatus.
3. Choose "Users of message" on the very first message, "Welcome to pump.io".
4. Get a crash dialog.

I guess the message doesn't have a proper sender.

**Comment by yvolk** [comment]
@clacke Could you send me that crash report?

**Comment by clacke** [comment]
Sent.

**Comment by yvolk** [comment]
Thank you, I found the problem easily and fixed it using the crash report.
Will be available in v.31.0+
