### ISSUE TITLE
Cant attach photo to hubzilla instance (statusnet api)

### ISSUE THREAD

**Issue by bastlwasti** [andstatus/andstatus#429]
Hello there,

I can post to my hubzilla which supports also the statusnet api, but I can't attach any photo :-(

I get the following error:

executed:3, last:vor 2 Minuten, retriesLeft:9, error:Hard,  
updateStatus; text:'Test mit anhang'; mediaUri:'content://org.andstatus.app.data.FileProvider/downloadfile/1478936605152_1087',
Status code=INTERNAL_SERVER_ERROR; hard;
; statusLine:'HTTP/1.1 500 Internal Server Error'; statusCode:INTERNAL_SERVER_ERROR (500); url:'https://hub.digitalesecho.de/api/statuses/update.json'; authenticated; posted:'{"media_part_name":"media","source":"AndStatus","status":"Test mit anhang","media_part_uri":"content:\/\/org.andstatus.app.data.FileProvider\/downloadfile\/1478936605152_1087"}'; response:'<!DOCTYPE HTML PUBLIC "-//IETF//DTD…'; error='?';
Caused by org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject,
CommandExecutionContext:{MyAccount:{accountName:joe/digitalesecho,id:1,oid:227,credentialsPresent,syncable,syncauto}, CommandData:{command:update-status,foreground,created:Vor 8 Minuten,"Test mit anhang",Timeline{joe/digitalesecho, type:home, userId:1, id:13},itemId:205,hashCode:-1881574113,CommandResult:{executed:2, last:vor 18 Sekunden, retriesLeft:10, error:Hard}}}

**Comment by annando** [comment]
The Hubzilla servers answers with an internal error. This indicates that it can't handle the data that was send by andstatus. For me it seems as if this is a Hubzilla problem. You should ask there if others are experiencing the same problem or if your instance has a problem.

**Comment by bastlwasti** [comment]
thank you for your answer.
I was not sure, what this has to mean.
