### ISSUE TITLE
Adding identi.ca account does not work

### ISSUE THREAD

**Issue by n8willis** [andstatus/andstatus#430]
Trying to add an (existing, fully functional) identi.ca pump.io account fails, with the error message ```Authentication Failed: No client keys for the host yet; registerCLient; for https://identi.ca; URL='https://identi.ca/api/client/register' ```

The account works perfectly in other pump.io clients, obviously, and no, I have not mistyped my username or hostname. This fail occurs immediately after entering the account name@server information and tapping the "Add this account" button.  

The app never attempts to open the authorization URL in the device's browser, as the 2014 wiki page suggests that it will. Screenshot attached.

![screenshot_20161113-133722](https://cloud.githubusercontent.com/assets/2192132/20246093/58148cf0-a9a7-11e6-91bf-850c1b1f1ae8.png)

**Comment by yvolk** [comment]
@n8willis I tried this on v.30.02 two times - no problem. I added my account at identi.ca and at another server also...
Could you try, maybe that was just transient server error?!

**Comment by n8willis** [comment]
If it was a server error, how would that be distinguishable in the client?

**Comment by yvolk** [comment]
Yuo never know for sure, which error is caused by communication channel and/or by a server, and which is caused by the client application...
