### ISSUE TITLE
Exclude drafts from sent messages timeline

### ISSUE THREAD

**Issue by simon-v** [andstatus/andstatus#434]
Seeing drafts there feels counter-intuitive; one would expect seeing there only messages that were actually sent.

**Comment by yvolk** [comment]
Now "my actor's" "Sent" timeline has "Notes by ..." title that quite logically can include drafts made by the Actor. And actually "sent", but failed to be posted activities.

"Sent" timeline name still exists though... and we have separate "Drafts" and "Outbox" timelines also
...but I feel that having one place for all my actor's activities (actually sent, failed and drafts) is convenient.
So let it be so for now.
