### ISSUE TITLE
[Pump.io] Add "delete" action support

### ISSUE THREAD

**Issue by simon-v** [andstatus/andstatus#435]
At least in pump.io, deleted messages leave a blank post in the timeline, which gets folded into the next one, if "collapse duplicates" is set. It would be better to hide those from view altogether.

**Comment by yvolk** [comment]
I don't use old messages pruning at all (for performance testing purposes also... have 195000 messages locally...) and sometimes I also do see such 'almost empty' messages:
Such a message is created as a placeholder, when AndStatus stores a message, which is a reply to another message, not downloaded yet. 

So in your case I think that "blank posts" are just not loaded yet messages, not improperly pruned.
?!

**Comment by simon-v** [comment]
In pump.io, deleted messages leave a blank message on the server, which is then propagated onto the client. In AndStatus those are never removed or hidden, which results in a permanent, blank message in the timeline.

Messages never updating on the client despite being updated on the server is a separate issue, only partially related to this one.

**Comment by yvolk** [comment]
In order to find a solution to ignore/delete such messages, I need your help: JSON file, received from a server, with such messages.
AndStatus creates such files (for each received data), when you set the option: Settings -> Logging and debugging -> Log network level messages.
On logging and log locations please read #225

**Comment by simon-v** [comment]
Attached. First file is a deleted message, second is a normal one.
Notably, the deleted message has a "deleted" field under "object". A normal message doesn't.
[json.zip](https://github.com/andstatus/andstatus/files/634642/json.zip)

**Comment by yvolk** [comment]
Thank you, I got it:
this about correct handling of Pump.io "delete" action.
I see this:
`"verb": "delete",`
I will add this and let you know.

**Comment by simon-v** [comment]
Thank you.

Will this also affect messages already stored in the database, or only new ones?

**Comment by yvolk** [comment]
Only new.
Do you mean that such defective messages are not deleted during periodic data pruning by AndStatus (when they become old enough)?

**Comment by simon-v** [comment]
I have a few from 5 months ago. How old is "old enough"?

**Comment by yvolk** [comment]
In Settings -> Storage -> History time you can set how long messages are kept in a local cache.
But "message age" is calculated since the message was loaded into the cache, not since the message's creation, that you may see...Moreover, Your messages AND messages, favorites by you, are never deleted.

**Comment by simon-v** [comment]
This means i would have to drop the local database to have my timeline refreshed and the messages updated and deleted. Is there any other way to do this? Perhaps, the app could check which messages are out-of-date with the state on the server and update the local cache to reflect the changes?

**Comment by yvolk** [comment]
Recently I added the new feature to AndStatus: "Check and fix data". It was created exactly to fix something without reinstallation.
If you/we could figure out, how to find that trash of deleted messages automatically, we could add this check/fix to that code...
Want to write code? :-)

**Comment by yvolk** [comment]
![Screenshot_20200531-163830](https://user-images.githubusercontent.com/207716/83353821-b1e3be00-a35d-11ea-8e5c-15d16c828fe2.png)
![Screenshot_20200531-163915](https://user-images.githubusercontent.com/207716/83353831-bf994380-a35d-11ea-9f06-3360be7bb3a3.png)
