### ISSUE TITLE
Discard draft: Selecting "remove message" on a draft should discard the draft

### ISSUE THREAD

**Issue by simon-v** [andstatus/andstatus#436]
Currently, this has no effect, and the only way to remove a draft is to select "edit" and then "discard", two steps in the place of one.

**Comment by yvolk** [comment]
I agree. And I should better in a case of a Draft add "Discard draft" context menu item instead of "Remove message" for consistency.

**Comment by yvolk** [comment]
For unsent message or a draft context menu has "Discard" menu item, which allows to delete this message.
![context-menu-draft](https://cloud.githubusercontent.com/assets/207716/23585378/7914cf16-018e-11e7-9115-6633fad0e5c7.png)

**Comment by yvolk** [comment]
Available since v.32.01
