### ISSUE TITLE
How to see a Public Timeline

### ISSUE THREAD

**Issue by mama21mama** [andstatus/andstatus#439]
I want to see the public network but I can not make it appear. I mean the public network to timeline of users that I do not follow.

**Comment by yvolk** [comment]
I wrote you the short instruction yesterday. Did you follow it, what went wrong?

First of all: Public timeline is supported by GNU Social only.

In AndStatus initially only "Public combined" timeline is created, so you should switch to the Public Timeline of your server from that "Public combined" timeline.

So, if you want to see and sync Public timeline of a concrete server:
1. Turn "Combined" on in the Navigation Drawer 
2. Switch to "Public combined" timeline, selecting that timeline e.g. in the Navigation Drawer.
3. Switch to account on that server/instance, which Public timeline you want to see.
4. Turn "Combined" off. Now you see the Public Timeline of that instance (not synced yet).
5. Tap "Sync with Internet" in the Action bar to sync the Public timeline (or simply "Pull to refresh"):
![screenshot_20170207-210030](https://cloud.githubusercontent.com/assets/207716/22704778/f160d3a8-ed79-11e6-8c7c-b6ed9d39ab85.png)
6. AndStatus requests 200 latest messages from the Public timeline. Scroll up (or Go to the Top) to see them.
![screenshot_20170207-210559](https://cloud.githubusercontent.com/assets/207716/22704782/fabcba2a-ed79-11e6-99a3-e010ecca4e7f.png)
