### ISSUE TITLE
Timeline is not always refreshed to show new messages, downloaded in a background

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#440]
As @keverets noticed in https://github.com/andstatus/andstatus/issues/295#issuecomment-278391741 for a Combined timeline, sometimes AndStatus doesn't "refresh" a Timeline, when new messages have been downloaded to the local cache in the background.
The simplest way to make sure that you see the latest data is to select "Refresh from cache" item in the Navigation Drawer.

Usually AndStatus does update a Timeline on loading new messages, but sometimes it intentionally ignores such events: this is done deliberately in order to avoid endless refresh and low responsiveness of the application, when active background updates occur. Obviously I need to improve this Timeline refreshing logic.

**Comment by skoria** [comment]
Um no it doesn't refresh however many times you refresh from cache..

**Comment by yvolk** [comment]
@skoria If after "refresh" some information is not shown, this means that some data is not loaded from the Internet and you actually need to "Sync with Internet".

**Comment by stormwatch** [comment]
I don't know if this is related but combined timelines usually don't update other accounts besides the one selected. Specifically, sometimes it won't update new tweets.

**Comment by yvolk** [comment]
@stormwatch This ticket is about redrawing of currently shown timeline after background syncing / downloads of new messages (tweets/toots...) and images (avatars and attachments).
Background syncing is _not_ necessary syncing _this_ timeline - it can do any work, including syncing of not related timelines...
As I understand, you are telling not about redrawing but about that background syncing?!
