### ISSUE TITLE
twitter: messages truncated

### ISSUE THREAD

**Issue by tokudan** [andstatus/andstatus#441]
Some messages are truncated when displayed in AndStatus:

Update: Streckensperrung zw. Berliner Tor <> Bergedorf.

Turns into:
Update: Streckensperrung zw. Berliner Tor

Example tweet:
https://mobile.twitter.com/SBahnHamburg/status/834306097003581440

**Comment by yvolk** [comment]
@tokudan Thank you for the report! I fixed the bug with this exact case, these two symbols are typed without any spaces: "<>"
The fix actually inserts one space between them - and such messages are not truncated anymore.

Please note that previously loaded messages are not fixed: they are still shown truncated.
![twitter-message-is-not-truncated](https://cloud.githubusercontent.com/assets/207716/23341282/61c5ad8c-fc55-11e6-936d-d92afc0540d2.png)

The fix will be available in v.32.0
