### ISSUE TITLE
html/csv export

### ISSUE THREAD

**Issue by sowas** [andstatus/andstatus#445]
the main strength of andstatus is offline
storing/searching of 10000s of posts..
in pure text..with low bandwidth...but
after a while i may want to clean up..without
losing all those..
so some simple form of csv export maybe?

just an idea    ;-)

**Comment by yvolk** [comment]
1. I'm using the same AndStatus database for several years. Currently it holds about 205,000 messages and performance is quite acceptable for such size. So I personally didn't have an acute need to clean something yet.
2. AndStatus has AndStatus Settings -> Storage -> Backup feature (and Restore also, of course), so you can get the full SQLite database file, which you can browse and use as you with on any computer...

**Comment by yvolk** [comment]
Please note that once a Backup is created, you can open  the database file database_andstatus.sqlite_data.sqlite with any available database tool and export any part of textual data into any supported format... or decide that having them in SQLite format is even more convenient, as I decided :-)

See e.g. the DB Browser for SQLite http://sqlitebrowser.org/ that can export data to plain text or CSV...
