### ISSUE TITLE
Don't use URL shortener

### ISSUE THREAD

**Issue by schiessle** [andstatus/andstatus#446]
I use Andstatus together with my GNU Social instance. On the server I have disabled all kind of URL Shortener, still if I post a link with Andstatus the URL will always be shortened by the build in URL Shortener of GNU Social. I'm not completely sure if this is a server or a client bug so I thought I will start to ask here because I observe the problem only in combination with Andstatus.

**Comment by yvolk** [comment]
AndStatus doesn't have any URL shortener. I currently there are no plans to add it. On this topic please see https://github.com/andstatus/andstatus/issues/32
