### ISSUE TITLE
Indicator to show if you're following a specific user

### ISSUE THREAD

**Issue by thelovebug** [andstatus/andstatus#447]
I received a notice on my GS timeline earlier, from someone whom I wasn't following at the time.

Can you please put an indicator - perhaps a head-and-shoulders silhouette - to show whether I'm currently following the user from which the notice was sent?

**Comment by yvolk** [comment]
Actually, now you can select "Users of message" context menu item and see a list of Users, including the Author and the Sender (if the tweet/message was reposted...). Each User in this list does have "followed by <my account name>" note at the bottom of the User's info.

E.g. on the below screenshot I looked up a message, reposted by McScx, whom I'm following.
![screenshot_20170314-205219](https://cloud.githubusercontent.com/assets/207716/23914875/54390240-08f8-11e7-99cf-2a800a293021.png)

**Comment by thelovebug** [comment]
Actually, this is something I hadn't spotted before.  My original request was to have something within the timeline to indicate follow status, but this is certainly good enough (and pretty much the same as Twitter does it).

Thanks!!
