### ISSUE TITLE
Combined timeline for a fresh account loads in oldest first order

### ISSUE THREAD

**Issue by akater** [andstatus/andstatus#453]
I created a Twitter account, synced and cached its Home for a month or so;
registered a LoadAverage account;
entered its “Home combined” Timeline.

Messages are cached but AndStatus displays older messages first, and I have to scroll up through a month worth of archived messages, 200 per scroll.

**Comment by yvolk** [comment]
AndStatus has "Go to the top" Menu item, which is in the left "Navigation Drawer".
It allows you to avoid long scrolling. 
See https://github.com/andstatus/andstatus/issues/255
![screenshot_20170421-190118](https://cloud.githubusercontent.com/assets/207716/25286023/f2e9a52c-26c4-11e7-81ce-49fba12bf1c6.png)
