### ISSUE TITLE
How to see Federated timeline (combined)

### ISSUE THREAD

**Issue by stormwatch** [andstatus/andstatus#457]
Hello. I subscribed recently for beta testing as suggested in #456

Unless I am mistaken, right now the “Everything combined" timeline shows only the local Mastodon feed combined with other accounts whereas I'd like to be able to read "the whole network” combined with other accounts.

Thanks @yvolk and every one involved.

Using v.33.00 (208)

**Comment by yvolk** [comment]
@stormwatch As I understand, "Federated timeline" in Mastodon is the same as "Public timeline" / "The whole (known) network" in GNU Social instances. I.e. that timeline shows all public posts/messages, which were stored at (downloaded to) this Social network instance.
This is called "Public timeline" in AndStatus. See https://github.com/andstatus/andstatus/issues/439 on how to switch and sync it.

"Everything" timeline in AndStatus shows _all_ messages, both public and private, stored in the local cache of AndStatus application on your device.

**Comment by stormwatch** [comment]
I'm afraid that currently, if I select Public Timeline, it shows public posts by local users only, whereas I'd like to include non-local (known) users whether I follow them or not.

**Comment by yvolk** [comment]
Yes, I checked now: Mastodon.social shows only local posts in its Public timeline. It looks like a restriction of the Mastodon implementation or configuration. Anyway, no special "Federated" timeline is currently available in Mastodon, according to its documentation: https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#timelines

**Comment by stormwatch** [comment]
I don't know about mastodon.social but the web client at mastodonar.club and Twidere do show the federated timeline.

**Comment by yvolk** [comment]
@stormwatch Thank you for information. I will lookup Twidere code to see, how it retrieves the Federated timeline.

**Comment by yvolk** [comment]
@stormwatch I fixed this: now "Public" timeline in Mastodon shows all posts, as I wrote above.
The fix was to delete one line of code: "local" parameter set to "false" was interpreted as "true" by the server. Omitting this parameter fixed the problem.

The fix will be available since v.33.01

**Comment by stormwatch** [comment]
So, can we close this one?
