### ISSUE TITLE
Occasionally replying to a tweet doesn't work and makes avatars change

### ISSUE THREAD

**Issue by schumaml** [andstatus/andstatus#458]
I'm using Andstatus from the f-droid repository and occasionally get the following behaviour:

- find a tweet I want to reply to 
- choose "reply to mentioned users"  from the long press menu
- wait for the text entry to show up

But this doesn't happen. Instead, the avatars of all tweets start to change, to arbitrary other ones. And they keep changing every few seconds. 

I haven't found a reliable way to reproduce this. Is there anything I can provide or do to investigate this issue further?

**Comment by yvolk** [comment]
@schumaml Thank you for the report. Sometimes I'm also noticing that my click on a context menu doesn't have any effect, and I have to repeat the same command again. My observation is that such "lost taps" occur for different commands. I didn't find time yet to investigate this deeper, but seeing your will to help :-) I will definitely start this investigation.
And I think that during this investigation we will find a cause of the unexpected avatar changes.

It would be extremely helpful if you could install some Beta versions of the application. Unfortunately, I cannot create a beta version signed by F-Droid. Please see on Beta testing options: https://github.com/andstatus/andstatus/issues/456

**Comment by yvolk** [comment]
@schumaml I think that I found a cause of the bug that you described: sometimes unexpected avatar changes occur.
This happens, when AndStatus's internal in memory avatar cache gets overloaded and older avatars are being replaced with newer ones while that "older avatars" may still be shown in a timeline. This avatar memory reuse results in showing wrong avatars.
I need to figure out how to solve this problem intelligently at the face of limited memory...

**Comment by yvolk** [comment]
Fixed in v.35, please check

**Comment by schumaml** [comment]
I haven't seen this happen with v.35, so it seems like it is fixed. Thanks!
