### ISSUE TITLE
[Twitter] Cannot always display full tweet

### ISSUE THREAD

**Issue by cdelmas** [andstatus/andstatus#462]
There is no way to display the full content of a tweet when it is long, an ellipsis is displayed with a link to the full message (looks like it is the default behavior of the Twitter API). This forces to open a web browser and lose time switching.

The official Twitter app can display long messages.

**Comment by yvolk** [comment]
I found the post that describes changes that need to done to avoid incoming messages' truncation in Twitter: https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

**Comment by yvolk** [comment]
@cdelmas Released in v.34 https://github.com/andstatus/andstatus/issues/456 (currently in Beta)
