### ISSUE TITLE
User @x@foo.bar gets notifications intended for @x@baz.bat

### ISSUE THREAD

**Issue by celesteh** [andstatus/andstatus#463]
I use andstatus for my GNU Social account, but not my mastodon account. All of my accounts have the same user name at different servers and there is some overlap of who I'm following.  When someone I follow with my GS account replies to my mastodon account, I get a notification from andstatus, as if it were a reply to the account it's set up for.

**Comment by yvolk** [comment]
Unfortunately, both #GnuSocial and Mastodon's client API have weak support for globally unique identifiers for Users and messages. I tried to convince @Gargron from Mastodon that this approach is wrong (see from here https://github.com/andstatus/andstatus/issues/419#issuecomment-254060882 ) but we still have what we have:
It is not always 100% clear if a user is the same or not.
