### ISSUE TITLE
Notifications on my own replies

### ISSUE THREAD

**Issue by celesteh** [andstatus/andstatus#464]
When I reply to my own posts, andstatus sends me a notification that someone has replied to me. It would be nice if this were disabled by default.

**Comment by yvolk** [comment]
@celesteh Please give more details: which Social network you use, do you reply to the same account or another account in the same Social network?!
Anyway, I will take your observation into account while improving Notifications (what I'm doing now, see the milestone)

**Comment by celesteh** [comment]
It's on gnusocial. When I post as @celesteh@algonoise.social and reply to myself from the same account to make a thread, it notifies me of a reply.

**Comment by yvolk** [comment]
This issue should be fixed since v.45.03 ("Fix: Blue mark in a timeline is for replies to me only, not to friends also.")
