### ISSUE TITLE
Show amount of likes/replies/comments

### ISSUE THREAD

**Issue by m1ga** [andstatus/andstatus#465]
Would it be possible to add the number of likes/replies/comments below a post (overview page). Like Twitter:

![screenshot_20170622_140827](https://user-images.githubusercontent.com/4334997/27433266-542b31b0-5754-11e7-891c-9889c965062b.png)

**Comment by yvolk** [comment]
It's not hard to get that numbers from received timelines. But that numbers, once received, will remain the same for a message until explicit request for update. AndStatus has "Get message info" for this.

**Comment by m1ga** [comment]
I've clicked on "Get message info" but there aren't any numbers visible (and none of the two replies):

![numbers](https://user-images.githubusercontent.com/4334997/27448705-055f68d0-5786-11e7-9d47-c0ecb4b37763.png)

**Comment by yvolk** [comment]
I need to implement that numbers' reading yet...

**Comment by yvolk** [comment]
Implemented in v.56.09. See #456
