### ISSUE TITLE
The same conversation has different number of messages, when looking from different instances

### ISSUE THREAD

**Issue by r4mp** [andstatus/andstatus#466]
It seems as if you open a message from the timelime written from a gnusocia account in the conversation view, with an mastodon user mentioned in the message, you can't see the whole conversation (only the gnusocial message).

If you open a message which was written from a mastodon account with an gnusocial account mentioned in it everything works fine.

Tested with 34.04-release and a gnusocial account

**Comment by yvolk** [comment]
This is a known problem/feature of GNU Social and of Mastodon also. Actually this is I personally prefer to use several accounts at different instances of these Social Networks.
I know these causes of such differences:
1. Messages of a remote User are delivered to an instance (and hence can be retrieved as a part of a conversation) only if this User is followed by at least one User of _this_ instance.
2. Mastodon adds another restriction: a message can have an "instance scope" I.e. it cannot be sent to any other instance.
3. And of course, there are sync problems between different instances. I.e. some days ago I've heard that there were problems in message communication between Mastodon and GNU Social instances...
