### ISSUE TITLE
Battery drain when a gnu social node it's down

### ISSUE THREAD

**Issue by colegota** [andstatus/andstatus#467]
Hi!

some months ago I've reported at gnu social that have a lot of data waste when my node was down.
Now, there is no data waste no more, but I have a battery drain issue and my phone shows that AndStatus it's using a lot.

The node it's quitter.no and user cayentana. Also managed in Andstatus with my main account colegota at quitter.es.

I've uploaded some logs from today at
http://www.fotolibre.org/albums/colegota/borrar/battery-drain-logs.zip

Also an screenshot of batery comsuption:
http://www.fotolibre.org/albums/colegota/borrar/260b053e-9468-42fd-8711-9ed5679f7dd9.jpg

Tell me if you need any more.

Regards!
Colegota

**Comment by yvolk** [comment]
From the log I see that for some reason syncing continued for 10 minutes after AndStatus's internal service stopped:

> 2017-08-22-18-05-49 5/CommandData: Bundle has UNKNOWN command: Bundle[{org.andstatus.app.SERVICE_EVENT=ON_STOP, org.andstatus.app.SERVICE_STATE=STOPPED}]
2017-08-22-18-05-49 V/MyServiceManager: Created, instanceId=642
2017-08-22-18-05-49 D/MyServiceManager: Notification received: Service state=STOPPED
2017-08-22-18-15-47 V/MyServiceCommandsRunner: syncAccount cayentana/Quitter.no ended, has error

I think this ten minutes waiting causes unneeded battery drain.

I will search in my logs for similar cases (as I also use Quitter.no )

**Comment by yvolk** [comment]
If we encounter this issue now, we will open a new issue...
