### ISSUE TITLE
How to configure Social Network, if the service is installed in a subfolder

### ISSUE THREAD

**Issue by thieltec** [andstatus/andstatus#469]
I try to use AndStatus within a subfolder. This is not configurable in the host property if the service is added.

**Comment by yvolk** [comment]
If your Social networking servicer is installed in a subfolder, you should type full url to the service in the "Host" field. See an example here:
https://github.com/andstatus/andstatus/issues/116#issuecomment-54778645

So AndStatus supports instances of Microblogging systems, which are located in a folder of the host (i.e. not in the root of the host). To configure such a system in AndStatus type full address (i.e. URL, including http...) of the system into the "Host" field of the Microblogging system's editor. See Issue #116 with an example of connecting to SDF GNU Social site.
Actually the URL of microblogging system may be like https://username:password@host.org:8080/directory/
