### ISSUE TITLE
when typing in the passwort first letter doesn't show up

### ISSUE THREAD

**Issue by PaulFree14** [andstatus/andstatus#470]
when I try to add a new account and type then the passwort in, the first letter I press on the keyboard is never shown up.

**Comment by yvolk** [comment]
Do you mean that you type your password at a Mastodon site during addition of a new account?
![enteringpassword](https://user-images.githubusercontent.com/207716/30036754-b3b7704a-91be-11e7-8be9-3eee5aa9d5db.png)

**Comment by PaulFree14** [comment]
no, within andstatus. Was while adding a gnusocial account. It happend a view times and then it worked at one point.

**Comment by yvolk** [comment]
Strange device incompatibility problem...
