### ISSUE TITLE
can't add mastodon account

### ISSUE THREAD

**Issue by PaulFree14** [andstatus/andstatus#471]
when I try to add a mastodon account I click on 'add new account' and then 'mastodon'
then for less then a secound the field pops up where I can add a new acount, but then directly getting redirected to the windows of 'add new account'

**Comment by yvolk** [comment]
This is by design :-)
Just press that "Add new account" button. 
Then Login page of a Mastodon Web site will open. Type your login and password there.
On the next Web page you will be prompted to allow AndStatus to read and write "toots" on your behalf...

**Comment by PaulFree14** [comment]
ah, I see what should happen.
The issue then is that it doesn't open or send a link to the browser

**Comment by yvolk** [comment]
AndStatus uses "WebView" as the Internet Browser. It's an embedded Android component and should be present on all devices.
What Android version do you have, what device model?

**Comment by PaulFree14** [comment]
device: H60-L02
android version 6.0
EMUI version 4.0.1

**Comment by yvolk** [comment]
@PaulFree14 I cannot tell about that device.
Maybe some wrong Android "defaults" were set that prevent WebView launch.
Or you could accidentally disable related Android component that provides that view...

**Comment by PaulFree14** [comment]
hmmm, but if I view my streamline and click on a link it works. 
A window pops up asking which browser I want to view it with and then opens the browser.

**Comment by yvolk** [comment]
These are different things. Clicking on web links is not related to a WebView in this case. 
Maybe this discussion would help you:
https://forums.androidcentral.com/nexus-6p/718833-android-system-webview-disabled.html

**Comment by graham-ocsi** [comment]
I get the same issue, Fairphone 2 running Android 6.0.1 Not quite sure what the solution is, even after looking at the thread suggested above - I have WebView installed according to Play Store, but not sure how to enable it.

**Comment by yvolk** [comment]
@PaulFree14 @graham-ocsi It came to me that maybe the problem is in concrete Mastodon instances? Could you try mastodon.social or mstdn.io (which I use and know that they work ok with AndStatus)?!

**Comment by graham-ocsi** [comment]
Unfortunately I can't even choose a different host - the "Type of Social Network" menu popup is the furthest I get, but choosing "Mastodon" at that point just closes the menu and goes back to the settings.

**Comment by yvolk** [comment]
@graham-ocsi This means some serious incompatibility of AndStatus with your device...

**Comment by graham-ocsi** [comment]
For reference, the other social network types connect fine, so there's
something different about the Mastodon approach. Havew tried looking
through the logs, but couldn't see anything specific - happy to post them
if it helps though.
