### ISSUE TITLE
Action buttons under messages don't work

### ISSUE THREAD

**Issue by PaulFree14** [andstatus/andstatus#472]
the bottons for sharing, reply and 'heart' don't work. 
when I press one nothing happends. 
Only the botton to open the menu works. 

The problem acured somewhen after I selected in the settings the gesture function. 
I can't tell if it's related

**Comment by colegota** [comment]
Same issue too.
But I didn't made any changes at gesture options.

I'm using 35.05 version from Fdroid in a CM11 (Android 4.4). Maybe the problem it's there since I've upgraded to 35.05.

**Comment by yvolk** [comment]
These action buttons are fixed in AndStatus v.36, please try https://github.com/andstatus/andstatus/issues/456

**Comment by yvolk** [comment]
Strange, I just tried Reply button on the latest v. 38.02, and it works...
Which version are you using now and which button doesn't work?
