### ISSUE TITLE
android.text.format.Time has been deprecated since API 22

### ISSUE THREAD

**Issue by frankFic** [andstatus/andstatus#473]
Hi,

Class has been deprecated since API level 22 according to the [document](https://developer.android.com/reference/android/text/format/Time.html) due to multiple problems.

I noticed the class is still used in MyRemoteViewData.java. As suggested by the document, replace this class with [GregorianCalendar](https://developer.android.com/reference/java/util/GregorianCalendar.html) is safer implementation to avoid potential issues.

Hope the information could help.

**Comment by yvolk** [comment]
@frankFic Thank you for noticing. By the way, source code of AndStatus is analysed periodically by the Sonar service:
https://sonarcloud.io/dashboard?id=andstatus
So I usually know about deprecated APIs.

**Comment by yvolk** [comment]
GregorianCalendar is outdated already.
I will migrate this to java.time after switching to minimum API 26. Current API 24 doesn't have even constructor from UNIX milliseconds...
