### ISSUE TITLE
How to update maximum number of characters in a message for a Social Network

### ISSUE THREAD

**Issue by mama21mama** [andstatus/andstatus#474]
Andstatus 1000 image > http://legadolibre.com.ar/file/ff145f2a517d8b810c8efa302a4348fdbd90850a2633d0aa217be96c807518f8.png

Server web 2000 > http://legadolibre.com.ar/file/e6020a13ed78eb03afada26b3a46dc01393b80554fea6d1ea5f9146fb3563494.png

**Comment by yvolk** [comment]
@mama21mama Please go to Settings -> Accounts -> Manage Accounts, select the account, for which the  inconsistency is, and press "Reverify credentials" button.
AndStatus should re-read the character limit from the server.
?!

**Comment by mama21mama** [comment]
Work. Gracias
