### ISSUE TITLE
Clicks on @user or #TAG shouldn't open websites

### ISSUE THREAD

**Issue by Mannshoch** [andstatus/andstatus#479]
I reflected my self about why i do not use Andstatus and the Fediverse more often. Now I got a result. I do not like it that a cklick on something open a Website. To be able to like it using Andstatus, it have to be possible to do all importand and common activities inside the same app. 

The most thing I do not like is the change of layout and style. Also the situation that some website are not optimized for mobile using. 
The change from a dark them app to a light colored theme from a Website and back is also not that enjoying.

**Comment by yvolk** [comment]
Currently, when you tap (click) a note (tweet), either some web site opens (if you tapped a link) or the note's context menu opens.
@Mannshoch Do you mean that links in a note/tweet should not be "clickable"? If yes then tapping any part of a note will open its context menu.
?!

**Comment by Mannshoch** [comment]
Sorry. I'm not sur if i understood what you meant wit note and tweet.

What i meant was @USER and #TAG. If i click on them this links should not open in Webbrowser.

**Comment by yvolk** [comment]
So you are telling not about _all_ links, but only about links, which look like:
1. @user - user mentioned
2. #TAG - hash tag
AndStatus doesn't create these links: they are automatically created by a server.

As I understand, you propose to add an option to change AndStatus behaviour on clicking these links. What AndStatus should do: 
1. Nothing (i.e. remove these links)
or
2. Open some view (i.e. "User timeline" for mentioned user and "Search #TAG" timeline for a tag)
?!

**Comment by Mannshoch** [comment]
I would vote for the second solution.
Andstatus should Open these Links on a new view where I could find posts about #TAG or could find posts from @USER.

OPTIONAL:
- For @USER The first Top Post (maybe in a folded status) could be some Profile Information.
- Maybe also Interesting if the first Tab of #TAG contain some Information (maybe in a Folded status) about the found posts (how many found, on which servers, possibility to save as favorite, etc)

**Comment by yvolk** [comment]
@Mannshoch Interesting, thank you for the insight.
I will create two separate tickets to implement these features.

**Comment by yvolk** [comment]
Implemented in v.43
