### ISSUE TITLE
And status version 37.01 completely frozen

### ISSUE THREAD

**Issue by gil-andre** [andstatus/andstatus#480]
After upgrading to And status 37.01, all timelines are stuck.

Clicking on "Sync" button displays a normal synchronization process, but all timelines (Twitter, Mastodon, GNU social) still displays messages from 9 days ago.

Sync button displays "Synced XX minutes ago".

I have tried multiple sync, disabling combined timelines, go to top, verifying credentials, etc... And nothing works.

Running on LG v20 under Android 7.0.

**Comment by annando** [comment]
I read today that the new version contains some massive changes to the internal database. So I guess you should wait some time (maybe an hour?). Or you completely uninstall it and install it again, with a clean database.

**Comment by yvolk** [comment]
@gil-andre Please report here how you resolved the problem (or maybe how AndStatus resolved it itself)

**Comment by gil-andre** [comment]
@annando : the update was **9 days** ago. So far, almost nothing has resolved it. 

@yvolk : I have NOT (entirely) resolved the issue, otherwise, I would not have opened a report here.

I have been able to resolve this issue with the Twitter timeline, by selecting "Settings > Storage > Check and fix data". This has "restarted" the Twitter timeline, who now displays updated tweets.

Both GNU Social and Mastodon are still stuck on messages dated 9 days ago, despite multiple sync & "Check and fix data". Any help would be greatly appreciated.

**Comment by gil-andre** [comment]
Any help would be greatly appreciated...

**Comment by yvolk** [comment]
@gil-andre  In order to solve a problem with syncing, please see solutions / advices here: https://github.com/andstatus/andstatus/issues/295 If that advices don't help in your case, please follow-up 
on syncing problems in that thread.
