### ISSUE TITLE
Feature request:  Option to hide or summarize duplicate reposts.

### ISSUE THREAD

**Issue by georgedorn** [andstatus/andstatus#481]
AndStatus is the only client that does most of what I need, but it is missing a feature that results in my timeline being a great deal noisier than it needs to be.  Every time a toot goes woolly* my timeline ends up showing it to me several dozen times.

One option would be to only show me any given post once a day, but a more graceful option would be to roll up all of the reposts that have happened _after_ my last-read location in the timeline into single copies, with the list of all of the reposters in the Actors menu.

**Comment by georgedorn** [comment]
They're not adjacent to each other except by coincidence.  I sometimes have two posts that alternate for several pages.

**Comment by yvolk** [comment]
I see. I already noticed this limitation.
I think think won't take me much time to extend maximum "distance" between duplicated posts from "1"  to maybe 5 ?!

**Comment by georgedorn** [comment]
Maybe make it configurable?  I'm not sure what the de-dupe process looks
like, so maybe that won't scale past a certain point...

**Comment by yvolk** [comment]
Collapsing of notes/actions is done on the UI level, so it shouldn't take much tive and works fast even for large local cache, see "duplicates" method https://github.com/andstatus/andstatus/blob/master/app/src/main/java/org/andstatus/app/note/BaseNoteViewItem.java

**Comment by yvolk** [comment]
Implemented in v.38.02, please try https://github.com/andstatus/andstatus/issues/456
