### ISSUE TITLE
[pump.io] Private message is public

### ISSUE THREAD

**Issue by ansorg** [andstatus/andstatus#482]
hi, I'm just playing with a self hosted pump.io instance and the AndStatus app. 

I have two users on the server who follow each other. 

In the AndStatus app I'm logged in with one account "A". I see the messages I got from account "B". Tapping one of those messages gives me the option to send a "private message". But when I do this it's not private at all, I can see this on https://www.inventati.org/ppump/

What am I doing wrong? Bug?

**Comment by ansorg** [comment]
![image](https://user-images.githubusercontent.com/3541784/38915654-be16f68c-42e4-11e8-8b70-55b946cac537.png)

**Comment by yvolk** [comment]
@ansorg I noticed this bug also. 
And fixed it, I hope.
Please try the new v.38.00 Beta https://github.com/andstatus/andstatus/issues/456
