### ISSUE TITLE
GNUsocial group name autocomplete

### ISSUE THREAD

**Issue by thelovebug** [andstatus/andstatus#484]
AndStatus already supports autocomplete for **@mentions**, and it does it really well.

What I'd like to see is autocomplete for GNUsocial **!groups** also.

I'm not sure there's any more detail I can give for this, but feel free to correct me on that!

**Comment by yvolk** [comment]
There is even no notion of a Group in AndStatus yet. See similar request: https://github.com/andstatus/andstatus/issues/248
We will need to start from addition to the AndStatus data model a **Group**, as an Actor Type (in terms of https://www.w3.org/TR/activitystreams-vocabulary/#dfn-group ). Unfortunately, addressing a group in a note's text in GNU Social is not like user mentioning...

**Comment by rozzin** [comment]
> Unfortunately, addressing a group in a note's text in GNU Social is not like user mentioning...

@yvolk, I don't quite understand what you mean here. I'm worried that it might just be an artifact of misunderstanding what "groups" in GNU social even are? I've added a more detailed response to that at #248....
