### ISSUE TITLE
One activity is notified many times.

### ISSUE THREAD

**Issue by amanohotori** [andstatus/andstatus#488]
AndStatus is the only client that that most of what I need,But there are still some problems. I'm not good at English, but I would like to improve this promising application by issue sharing and contribution to development.
I may be misunderstanding a implementation as I have not read the source code yet. I'll read on it right away.

The problem of the highest priority in practical use is that notifications are made many times until you read one notification. I will ask for notification from the application, but I am giving up and turning off notifications to solve this problem.
Notifications are pushed at regular intervals until read them. It seems to be notified every time it synchronizes with the server. I want to make notifications only once.

I don't yet know if this is my configuration problem or the specification issue. If the specification is reason, is this the appropriate user experience?

**Comment by yvolk** [comment]
@amanohotori Yes, currently notifications are accumulated until a User opens corresponding timeline.
As written in the ChangeLog ( http://andstatus.org/changelog.html ):

> Notifications, shown in Android Notification area and in the AndStatus Widget, are not forgotten anymore. These notifications are persisted even after device reboot. Notifications are reset when a User opens correspondent timeline e.g. by clicking on the Notification or a Widget. #367 and #398

It looks like we need to detect, when a User explicitly dismissed a notification and "forget" corresponding events (see https://stackoverflow.com/questions/12665131/how-to-detect-if-a-notification-has-been-dismissed ):

> I believe that Notification.deleteIntent is what you are looking for. The doc says:
>> The intent to execute when the notification is explicitly dismissed by the user, either with the "Clear All" button or by swiping it away individually. This probably shouldn't be launching an activity since several of those will be sent at the same time.

This means that each notified event should know corresponding Notification ID (one notification may be about several events...) so an app will know, which event to forget...

**Comment by zilti** [comment]
Actually in my case, the notification appears again and again and again and again even if I click and view it inside andstatus.

**Comment by yvolk** [comment]
I monitored my Notifications in #AndStatus for some days, and today I thought that I found a bug: I saw "2 mentions", but Notifications timeline didn't show me anything that I didn't see in the morning.
I searched in logs for "NewNotification" and found out that in this case the two mentions were expected: 4 days ago I was mentioned by some user at mastodon.social, but only today I got two copies of the same note/mention: from mstdn.io and from loadaverage.org. Naturally these two new mentions were collapsed with that 4 days old mention, and this is why I didn't notice them...

**Comment by yvolk** [comment]
I just thought that maybe when you click on a Notification, some new, special timeline should be opened called "New notifications", which would contain only activities that you didn't see before (as the application thinks...), and nothing more?! 
That timeline won't be refreshed automatically in order not to forget activities that were "new" seconds ago, but aren't new now as they have been shown to you already.
Notes in the "New Notifications" timeline should be sorted by time, when they were received by the client application, and not by the time, when they were sent. Otherwise we are risking to be confused, which "new notifications" we received and when.

**Comment by yvolk** [comment]
I think that "Unread Notifications" timeline added in AndStatus v.45 solves this issue.
