### ISSUE TITLE
[GNU Social] Convert "somebody favorited something by otheruser..." notes into actual favoriting activities

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#491]
As we discussed with @moshpirit in #279 
we want to allow a User to see that somebody favorited his/her note (in Notifications timeline)
AND "somebody favorited something by otheruser:" words should be automatically removed from all incoming notes.

Using #ActivityPub terminology, AndStatus should::
1. Detect GNU Social "favoriting actions" formatted like ordinary notes (using "somebody favorited something by otheruser:" "favoriting prefix") during processing of downloaded timelines.
2. And convert such notes into LIKE actions of original ("favorited") notes. Text of that "original" note should be re-constructed by removing the "favoriting prefix".
As a result, timelines won't contain that "somebody favorited something by otheruser:" words, but will have LIKE (favoriting) actions of somewhat not fully reconstructed "favorited notes"...

As a side effect, this change will make timeline opening a bit faster, as the application won't need to search for that  "somebody favorited something by otheruser:" - it does this now in order to collapse duplicates...

**Comment by yvolk** [comment]
I implemented this, but decided not to spend time on fixing notes that are already stored in the local cache. This means that the new feature will work for newly downloaded notes only.

**Comment by moshpirit** [comment]
Good enough! :) thanks!

**Comment by yvolk** [comment]
Implemented in v.40

**Comment by moshpirit** [comment]
AWESOME!! Thank you so much!
