### ISSUE TITLE
People are sharing full movies in GNU Social and AndStaus download it and fill my smartphone memory

### ISSUE THREAD

**Issue by colegota** [andstatus/andstatus#492]
Hi!

there is people sharing direct links to movie pictures in GNU Social and Andstatus see it as an attachment and download it. As the movie size are close to 1Gb with a few of it I have my memory full.

So we need to have a limit of size to download ASAP.

References:
[https://gnusocial.villanos.net/notice/92600](https://gnusocial.villanos.net/notice/92600)
[https://gnusocial.villanos.net/notice/92262](https://gnusocial.villanos.net/notice/92262)
[https://gnusocial.villanos.net/notice/92898](https://gnusocial.villanos.net/notice/92898)
[https://gnusocial.villanos.net/notice/91429](https://gnusocial.villanos.net/notice/91429)

**Comment by yvolk** [comment]
I see, added your request to #459 
Starting...

**Comment by yvolk** [comment]
Implemented in v.40
