### ISSUE TITLE
Need to know from which account it's a message at combined timeline

### ISSUE THREAD

**Issue by colegota** [andstatus/andstatus#493]
Hi!

I'm using AndStatus with 3 GNU Social accounts from the same node so I'd like to use a combined timeline but in that case I can't distinguish which message it's from each account and having common followed accounts sometimes I did reply with the wrong own account.

Could be possible to difference each message account by for example the avatar or a different background colour?

I think we talk about it some years ago in GNU Social but maybe it's not implemented.

Until now I have different accounts at different nodes and I can see the node written at the message header, but now I'm running my own GNU Social node and it's the same for the 3 accounts so no way to difference it and I can't use combined timelines.

**Comment by yvolk** [comment]
Information on an Account, which was used to download each Activity (Note...) is stored, so it can be easily shown. 
This could be an option in Settings -> Timeline: "Show my account, which downloaded the activity/note"

The question is: how to show this properly:
* "My account" doesn't have any color associated with it yet... 
* Showing account's avatar in some additional place may help, but where to put it? 
* We may simply add " account:accountname" to each Note's details (after "... in Reply to...")

@colegota Any concrete UI design suggestions?!

**Comment by colegota** [comment]
I'm using 39.0 but can't find that option Settings -> Timeline: "Show my account, which downloaded the activity/note".

At this moment I got the server in the top (gnusocial.villanos.net in my case) but not the account (colegota/tomatuordenador/cayentana@gnusocial.villanos.net).

Did found my proposals when we talk about this last year.
![propuestas-andstatus-c01](https://user-images.githubusercontent.com/5110784/40933657-6cbecf80-6832-11e8-81d7-d2ffd2de5226.png)

There is no much space for the avatar while maybe at bottom left corner of the message. 
Maybe as a background image "washed" almost white to allow legibility... :)

**Comment by yvolk** [comment]
> I'm using 39.0 but can't find that option Settings -> Timeline: "Show my account, which downloaded the activity/note".

1. I only suggested to add this. So there is no such setting yet. I think that maybe I will add text without color first.
2. Thank you for finding the screenshots. Seeing your proposed UI I see that "Account color" setting is unavoidable :-) Will think about this.

**Comment by yvolk** [comment]
I added this in v.40, so far as text only below the note's text: "a:accountname". I hope this will allow you understanding if this option is really helpful...
![scr-account-which-downloaded-40](https://user-images.githubusercontent.com/207716/41120512-6ca8f336-6a9e-11e8-9a19-bc1e2ce4a607.png)

**Comment by colegota** [comment]
Thank you a lot!

Will check it as soon as I can upgrade from FDroid.
I'll keep you informed.
