### ISSUE TITLE
Need new logo?

### ISSUE THREAD

**Issue by anaufalm** [andstatus/andstatus#495]
Hi, Im freelance graphic designer.

I just look at your application, and unfortunately I do not see the identity in the logo and less interesting. I want to contribute to your project. I can create a new logo for your app. What do you think? :)

Rgrd,
Naufal

[My Recent portfolio](https://www.instagram.com/faal.id/)

**Comment by yvolk** [comment]
Hi Naufal.
I don't know about logo, 
but I know that AndStatus has problems with GUI / activities layout design. Because users tell me this.
So maybe your experience and talents will be more needed in that area?!
