### ISSUE TITLE
Documentation. 

### ISSUE THREAD

**Issue by princekelly1** [andstatus/andstatus#497]
Hi, 
Am a content creator, and will love to create a FAQ and privacy policy for the app. With necessary information from you.

**Comment by yvolk** [comment]
@princekelly1  Thank you for offering your help.
AndStatus does have already the FAQ https://github.com/andstatus/andstatus/wiki/FAQ
and the Privacy policy https://github.com/andstatus/andstatus/wiki/Privacy-Policy
Feel free to suggest improvements for them. Anyway, I think that knowing the AndStatus application is the required prerequisite for such improvements ;-)
