### ISSUE TITLE
First run issue: can't "Get Started" - DATABASE_UNAVAILABLE

### ISSUE THREAD

**Issue by keverets** [andstatus/andstatus#505]
Installed v47.09 from F-Droid.

Starting application shows an "AndStatus" screen with a back arrow in the upper left (slightly confusing... back to what? seems to close the application), a gear in the upper-right (does nothing when pressed), and a "GET STARTED" button at the bottom.

Touching on the "GET STARTED" loads a modal dialog box containing:

> ! AndStatus
> Loading
>     OK

Touching "OK" just goes back to the initial screen. It's not clear what it might be "Loading" (changelog? Something else?) but it never completes.

**Comment by keverets** [comment]
Device is sgh-t989 running Android 7.1.2 (LineageOS 14.1)

**Comment by keverets** [comment]
![Screenshot_20190401-142305](https://user-images.githubusercontent.com/502780/55351399-3c940900-548c-11e9-8a2a-c858eed0c7d9.png)

![Screenshot_20190401-142300](https://user-images.githubusercontent.com/502780/55351411-49186180-548c-11e9-9b0e-18de208194ad.png)

**Comment by yvolk** [comment]
Aha, thank you. I see "DATABASE UNAVAILABLE". I saw this sometimes on an Emulator...
You need to kill the app either by removing it from he list of recent apps, or by rebooting. Next time app should start correctly.
?!

**Comment by yvolk** [comment]
Got it, thanks for trying.
I will review the first time run code again in order to recover from such a state...

**Comment by yvolk** [comment]
@keverets As the cause of such problem is unknown (maybe even Android bug...), I ended up with helpful diagnostic message in place of previous "Loading":

> We couldn't open local cache (database with notes and activities). Please try to reboot your device or reinstall AndStatus.
