### ISSUE TITLE
Content warning not intuitive

### ISSUE THREAD

**Issue by BalooUriza** [andstatus/andstatus#507]
When using networks that support content warnings/folds (e.g. Mastodon), there's presently no way to keep sensitive images or warned content from being displayed automatically.  Likewise, creating a new Mastodon post with a CW is not intuitive.

**Comment by yvolk** [comment]
Yes, really. There is no special support of Mastodon's "CW" feature. Just more generic "Note Name/Title" notion is adapted to be used with Mastodon.
Mastodon doesn't support "Name/Title", and I figured out that having mapping of more generic "Name" (which is used in Pump.io and ActivityPub) to Mastodon's "CW" is better than nothing...

**Comment by BalooUriza** [comment]
I agree, it's better than nothing on submitting (perhaps labeling the fields as such when posting to Mastodon and any other networks that support CWs would help).  But on the reading side, not having CWs collapsed by default (or at least a way to enable collapsing them) is problematic due to NSFW posts.

**Comment by yvolk** [comment]
Do you think that "Collapse notes with titles" option (initially without identifying, if the Title is a CW or a simply Name/Title) and "show" button in collapsed notes ("toots"...) in AndStatus Settings could help?

**Comment by BalooUriza** [comment]
Mostly, yes.  If it's something that can be set as a default, even better.
Obviously show the title even if it's CW stuff, but collapse the rest.
Something similar should happen with media on posts with sensitive media
that isn't CW.  By comparison, Tusky get sensitive media and content
warning right but can't hang on phones with lots of data dropouts.

>

**Comment by yvolk** [comment]
This is anther case, as I understand:
> Something similar should happen with media on posts with sensitive media that isn't CW...

I didn't understand fully, starting with this phrase. 
How do I know if the media is sensitive if the note doesn't have any title/name/CW text?

**Comment by BalooUriza** [comment]
I believe it's a subset of the same case, I don't fully understand the
internal workings of Mastodon, but it is possible to send a toot that has
the images hidden and the text not.

**Comment by yvolk** [comment]
The second case with media only is not the the same, if we don't extract Mastodon - specific "sensitive" flag from the Note...

**Comment by yvolk** [comment]
OK, so I see that instead of a hack we really need to add separate "Sensitive" property that could be used both in Mastodon and at least in ActivityPub.

See this thread regarding on ActivityPub: https://github.com/w3c/activitypub/issues/231 In ends with the proposed extension: "sensitive" property" (see https://www.w3.org/wiki/Activity_Streams_extensions#as:sensitive_property )

**Comment by yvolk** [comment]
Released in v.50.01
