### ISSUE TITLE
Notifications for new notices from people I follow

### ISSUE THREAD

**Issue by rozzin** [andstatus/andstatus#508]
If you don't follow too many people, it's nice to get notified when any messages have arrived from the people that you do follow in your home timeline (I guess these are "Friends"), instead of having to keep checking manually for new messages.

I get this with e-mail, RSS feeds, XMPP, and all sorts of other communication tools, and I could have sworn that I *used to* get this from Andstatus..., but maybe I'm misremembering. It would be nice to be able to get notifications when news is available from friends.

**Comment by yvolk** [comment]
@rozzin In December 2017 I reimplemented Notifications in AndStatus and removed notifications on new messages in the Home timeline, thinking that this is unneeded "notification type". I guess you are remembering that "Home" notification.
"Notes from people I follow" will be a good addition now to the list of existing "notification types".
I will add this. This won't be exactly old "Home" notification, but I think that this is good: it will be a way to check, why each note (notice, toot...) was included in the Notifications timeline.
?!

**Comment by rozzin** [comment]
On 5/12/19 12:28 PM, Yuri Volkov wrote:
> @rozzin <https://github.com/rozzin> In December 2017 I reimplemented Notifications in AndStatus and removed notifications on new messages in the Home timeline, thinking that this is unneeded "notification type". I guess you are remembering that "Home" notification.
> "Notes from people I follow" will be a good addition now to the list of existing "notification types".
> I will add this. This won't be exactly old "Home" notification, but I think that this is good: it will be a way to check, why each note (notice, toot...) was included in the Notifications timeline.
> ?!

Thanks! Yes, I think the old `Home' notifications is what I was remembering.

And, yes--I agree that having finer-grained control over which things generate notifications  is better than `all or nothing'.

It would also be nice to have a checkbox to let AndStatus generate notifications for messages that arrive via OStatus groups, if that's possible.

The concern that leads me to ask for both of those things is an `induction of new users' problem:
we convince people to create an account, get a client set up, they subscribe to some things
that they actually find interesting..., and then they never see any notices, so they forget the whole thing.

I've had this conversation with people I've introduced to GNU social and Andstatus before--
If I ask something like "Why have you been so silent since joining? You never even favor anything anyone posts,
and there were a few I saw that I thought for sure you would have really liked, like this one...",
the answer is always something like "Oh! <uncrontrollable laughter>, yeah--that _is hilarous_!
But I never even saw it. I guess I forgot that there was yet another thing that I had to
specifically remember to go look at--I can't keep track of that stuff manually".

**Comment by yvolk** [comment]
> It would also be nice to have a checkbox to let AndStatus generate notifications for messages that arrive via OStatus groups, if that's possible.

Different Social networks, including GNU Social, use a concept of "Home" (or "Inbox") for notes from Followers, subscribed Lists/Groups etc... so it's not trivial to figure out, why any concrete note was received via the Inbox.

So I better start with adding "Home notes" notification, which will cover both cases that you mentioned, and maybe later will add other, more granular notifications.

**Comment by yvolk** [comment]
"Home" notifications are published in v.49.00 (currently in Beta) here #456
