### ISSUE TITLE
[Hubzilla] Pictures in posts are not displayed

### ISSUE THREAD

**Issue by csolisr** [andstatus/andstatus#510]
I currently use Hubzilla on a self-hosted instance, and use AndStatus using Hubzilla's StatusNet compatibility layer. When browsing my timeline, none of the images appear, instead being consistently replaced by a small teal-colored square. Attempting to use the "view in browser" option as a workaround redirects to an invalid page (probably the fault of the compatibility layer, and that merits its own issue). Profile pictures are loaded without issue however, which leads me to think the problem resides on the way AndStatus renders the posts.

**Comment by yvolk** [comment]
AndStatus doesn't parse HTML content for embedded images. Nothing specific to Hubzilla here, I suspect.
Anyway, I think that using ActivityPub Client to Server protocol is the way to go.
I've heard Hubzilla devs are doing this?!

...But you are we!come to provide your PR for this feature in AndStatus
