### ISSUE TITLE
Unable to add or edit any account

### ISSUE THREAD

**Issue by geofrey** [andstatus/andstatus#511]
Same problem as issue #471 on a Galaxy S6, original Samsung software (Android 7.0). AndStatus version 50.01 from F-Droid.

As previously described, an empty 'add this account' screen displays briefly, then the UI backs out to the main menu. Happens for all account types, repeatedly. Only one time I saw a login form flash on screen for a fraction of a second before disappearing.

**Comment by yvolk** [comment]
Please turn on logs,as described here https://github.com/andstatus/andstatus/issues/225 including turning on "Backup log files"
Then resteart device, try to create an account once, and please create a backup with data for me to analyse. Please attach the zipped backup folder to this issue, or send to me directly...

**Comment by geofrey** [comment]
Will do!

**Comment by geofrey** [comment]
I've emailed the logs to you@yourwebsite; I'll be happy to perform more troubleshooting.

**Comment by yvolk** [comment]
Thank you for testing.
I can think of another way to move forward before I create the permanent fix: Restore AndStatus data from a backup, created on a device, where everything works as expected.
This device could be even Android emulator.

**Comment by hieronymousch** [comment]
Same problem on Nokia running stock Android 9

**Comment by yvolk** [comment]
@colegota I tried to add new account in #AndStatus v.50.01, and I cannot do this either.
Actually, I'm using v.50.01 now and didn't notice any other problems yet. But I didn't add new accounts since last upgrade. 
So existing users seems like unaffected by this bug.

Will fix the latest version as soon as I will be at my PC (I'm still faraway...) 

For the new users:
1. Please uninstall v.50.01, 
2. Install v.49 using G-Droid/F-Droid app. I just tried G-Droid, see screenshot - three versions of AndStatus are available. https://f-droid.org/en/packages/org.gdroid.gdroid/
3. Add all necessary accounts. 
4. Create a backup in AndStatus Settings -> Storage -> "Back up app data to SD card".
Backups are always good, and in a case step 5 fails you can quickly restore everything, reinstalling v.49 and then Restore this backup from the first screen of the app.
5. (optionally) Update AndStatus to v.50.01 in the same G-Droid/F-Droid app. #G-Droid misbehaved here for me on a first attempt... but after I had restarted it, it updated AndStatus successfully. https://loadaverage.org/attachment/5398183

**Comment by colegota** [comment]
Did it and seems to work OK! 

Installed v49, created accounts and upgraded to v50. 

No need to restart. 

Thanks a lot!
Colegota 

El 2019-06-17 20:42, Yuri Volkov escribió:

> @colegota [1] I tried to add new account in #AndStatus v.50.01, and I cannot do this either.
> Actually, I'm using v.50.01 now and didn't notice any other problems yet. But I didn't add new accounts since last upgrade.
> So existing users seems like unaffected by this bug. 
> 
> Will fix the latest version as soon as I will be at my PC (I'm still faraway...) 
> 
> For the new users: 
> 
> * Please uninstall v.50.01,
> * Install v.49 using G-Droid/F-Droid app. I just tried G-Droid, see screenshot - three versions of AndStatus are available. https://f-droid.org/en/packages/org.gdroid.gdroid/
> * Add all necessary accounts.
> 
> * Create a backup in AndStatus Settings -> Storage -> "Back up app data to SD card".
> Backups are always good, and in a case step 5 fails you can quickly restore everything, reinstalling v.49 and then Restore this backup from the first screen of the app.     * (optionally) Update AndStatus to v.50.01 in the same G-Droid/F-Droid app. #G-Droid misbehaved here for me on a first attempt... but after I had restarted it, it updated AndStatus successfully. https://loadaverage.org/attachment/5398183
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

 

Links:
------
[1] https://github.com/colegota
[2]
https://github.com/andstatus/andstatus/issues/511?email_source=notifications&amp;email_token=ABG7YAHQPWGV5MRI4SDQRNDP27LI7A5CNFSM4HWIH2I2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX4CXXQ#issuecomment-502803422
[3]

**Comment by geofrey** [comment]
Confirming workaround is good. ✔️ 
F-Droid had a problem installing v49 as a downgrade but, not having anything to lose, I uninstalled v50 first and the rest went fine.
Was able to add my accounts in v49 and then upgrade back to v50.

**Comment by colegota** [comment]
Now I had again part of the problem that causes I did remove and reinstall the app. 

My timelines are little confused. Unread notifications shows Home (personal timeline, Inicio in Spanish version) while notifications now are shown in Interactions. But this timeline it's not shown when click on widget.

Not sure if open a new issue or wait for next version.

Regards!
Colegota

**Comment by yvolk** [comment]
I think "Timeline confusion" could be a good new issue, thank you.

BUT showing Home timeline by default is the new feature:
https://github.com/andstatus/andstatus/issues/508

It is mentioned in v.49 http://andstatus.org/changelog.html

I should had set it off for old users... but was lazy... sorry for the
confusion

**Comment by remram44** [comment]
Ran into this trying out AndStatus today. It's unfortunate that this makes the app completely unusable for new users. Hopefully you don't lose too many potential adopters this way :cold_sweat:

Will you please let me know when the Play store is updated? Thank you!

**Comment by yvolk** [comment]
@remram44 Fixed in v.50,02. see #456

**Comment by remram44** [comment]
Looks like v50.02 was released yesterday soon after my comment. Neat!
