### ISSUE TITLE
How do I get why a message is not sent

### ISSUE THREAD

**Issue by Mannshoch** [andstatus/andstatus#513]
I shared a picture from my cam to andstatus and tried to publish it on friendica. An hour later i detected that I have a message in the outbox. I do not get any error if I manually try to send it.

**Comment by yvolk** [comment]
Please find the posting "command" in the menu -> "Commands in a Queue". You will see the error message there and will be able to Resend the command, i.e. to retry the sending.

**Comment by Mannshoch** [comment]
> Origin:{name:federatedservices.ch, type:OriginType: {id:3, title:'GnuSocial'}, url:https://social.federatedservices.ch, SSL mode:SECURE},
> Status code=BAD_REQUEST; hard;
> statusLine:'HTTP/1.1 400 Bad Request'; statusLine:'HTTP/1.1 400 Bad Request';
> statusCode:BAD_REQUEST (400); url:'https://social.federatedservices.ch/api/statusnet/conversation/andstatustemp:note:1561719627092.json'; 
> authenticated; 
> response:'{"status":{"error":"User not found.",…'; error='?',
> CommandData:{command:get-conversation, account: michel@social.federatedservices.ch/GnuSocial, itemId: 1825, foreground, created:vor 1 Sekunden, CommandResult:{error:Hard}}

**Comment by yvolk** [comment]
@Mannshoch In this your example AndStatus tried to download conversation, for which it didn't know real id (we see "andstatustemp:..." instead of the real id here).
I improved this just now (will be in v.50.03+):  it won't even try to download in such cases.
