### ISSUE TITLE
When starting after a long time, Andstatus tries to load all missing posts

### ISSUE THREAD

**Issue by annando** [andstatus/andstatus#514]
I haven't used AndStatus now for about 9 month. Now I started it again. Since several minutes the system now seems to fetch all missing items - so the system will now want to load some thousand items, which is an impossible task.

Just while writing these lines the syncing stopped (it lasted around 30 minutes) - but the newest post is still 9 month away.

I would prefer if AndStatus would only load the few newest items instead.

**Comment by yvolk** [comment]
We have an option for this in Settings -> Syncing -> Don't synchronize old activities, if previous sync was more than ... hours ago

Please try!

**Comment by annando** [comment]
Since the program had been that slow, I ended up with removing the profile and adding it again. Even the removal lasted several minutes. I will now see how the system reacts.
