### ISSUE TITLE
GNU social account fails to verify 

### ISSUE THREAD

**Issue by franny23dmt** [andstatus/andstatus#517]
my gnu social account fails to verify / authenticate.     😬
![Screenshot_2019-09-26-21-33-33-710_org andstatus app](https://user-images.githubusercontent.com/6313539/65685452-56ae4d00-e0a5-11e9-887f-b9b028d8bd9a.png)

**Comment by yvolk** [comment]
Hi @franny23dmt , 
I just checked Verify Credentials of my user on exactly this server - and it works!
Please note that username is case sensitive also AFAIK.
