### ISSUE TITLE
403 Forbidden on posting a Twitter update 

### ISSUE THREAD

**Issue by szpak** [andstatus/andstatus#518]
I'm new to AndStatus and I cannot send a simple Twitter update. My message (simple text + a picture) I kept as unseen. From the "Commands in a queue" I see that the application thrown `HttpResponseException` with a status `403` and a reason phrase "Forbidden".

I tried to resent that message multiple times, but the error remains the same. I tried to "Reverify credentials" and it works fine. I see updates from Twitter. The app in the twitter settings is NOT "restricted from performing write actions". What else could be wrong?

v51.01 (297) from Google Play.

**Comment by yvolk** [comment]
We saw similar problem 3 years ago, see https://github.com/andstatus/andstatus/issues/415
Now I logged into my dev Twitter account and checked if the AndStatus app is blocked - no.
I also posted a message with a picture - no problem also: https://twitter.com/AndStatus1/status/1183814319949123584

BUT, once saw "Internal error" message on Twitter site now, so maybe Twitter has problems today.
Another possible reason - too large attachment. Try to send smaller picture.

?!

**Comment by szpak** [comment]
It seems that the problem was caused by too large image. Once reduced to 1000px width the post was sent successfully. Thanks for a tip.

Anyway, maybe AndStatus could suggest somehow that an image/attachment is too large (if there are any limits mentioned in the Twitter API).

**Comment by yvolk** [comment]
@szpak It's interesting about image size:
I the above post I successfully sent an image 3840x2160 pixels, 3.4 MB
