### ISSUE TITLE
Unable to close "Unread notifications" with "Mark all as read"

### ISSUE THREAD

**Issue by provost359** [andstatus/andstatus#519]
Hello,

when I open AndStatus' "Unread notifications" from the notifications area and then click the button "Mark all as read", the "Unread notifications" remains open with no further items - see first screenshot below.
Is this intended? Because it seems somewhat counter intuitive - if there are no more unread notifications, what's the point of showing a blank screen? It would be nice if the application then jumped to the Default Timeline - which is the only reasonable option in the upper left menu anyway. See second screenshot below.

If I missed something, or screwed up my settings, don't hesitate to let me know.

Thanks a lot.

![Screenshot_20200219-191220](https://user-images.githubusercontent.com/10998568/74862617-beaf4980-534c-11ea-97fc-91364515bc79.png)

![Screenshot_20200219-192143](https://user-images.githubusercontent.com/10998568/74863100-98d67480-534d-11ea-8828-ca72797d6b2c.png)

**Comment by yvolk** [comment]
@provost359 Hello!
For me it would be strange if any view was auto closing in a case there were no items to show in it...

E.g. I remember looking at the empty "Spam" view in the GMail app after cleaning it: it still shows me that there are no items left there... Empty Outbox is still shown after successful sending of a message...

Why "Unread notifications" in AndStatus should be different? I mean, I understand that you may like this (why not...), but why do you think that this "view auto switching" is expected by other users?

BTW, you can switch to another timeline by tapping the timeline title also...

**Comment by provost359** [comment]
@yvolk Hello,

thanks for the response. It is enough for me to know that it's intended behaviour. And I definitely don't assume to know what other users might want :)

Also, thanks for the application, and keeping it open source.

**Comment by yvolk** [comment]
@provost359 Thank you.
I'm curious, if and why it really matters for you that the app is Open Source?
