### ISSUE TITLE
Can't authenticate to GNU Social 2.0-dev

### ISSUE THREAD

**Issue by colegota** [andstatus/andstatus#520]
Hi!
some time ago I did upgraded my site to GNU Social 2.-development edition.
This is not an stable version, but it's the first one that allow some compatibility with activity pub and it allows to connect -Mastodon accounts with some issues.

Since then, I can read timelines in Andstatus, even I got some notifications that I did not receive via web, but I can't publish messages.
When I try to publish a message I got this error at message queue:

E; Publicar , foreground "Prueba",
Creado hace 31 minutos,
executed:1, last:hace 31 minutos, retriesLeft:9, error:Hard,
updateNote; content:'Prueba',
Status code=UNAUTHORIZED; hard;
; statusLine:'HTTP/1.1 401 Unauthorized'; statusCode:UNAUTHORIZED (401); url:'https://gnusocial.villanos.net/api/statuses/update.json'; legacy HTTP; authenticated; posted:'{"status":"Prueba","source":"AndStatus"}'; response:'{"error":"No ha sido posible...'; error='No ha sido posible autenticarte.',
CommandData:{command: update-status, account: colegota@gnusocial.villanos.net/GnuSocial "Prueba", itemId: 62184, foreground, created:hace 8 segundos, CommandResult:{error:Hard}}

Also had 401 Unauthorized in https://gnusocial.villanos.net/api/account/verify_credentials.json;
when trying to authenticate account in Verify Credentials button.

Let me know if I can give you some more details.

Regards!
Colegota

**Comment by yvolk** [comment]
@colegota In order to fix this issue I need to have a test account at that GNU Social instance. Could you create one for me?

**Comment by colegota** [comment]
sure! remember me your emal account to send you credentials.

**Comment by yvolk** [comment]
Let's use this email: andstatus@gmail.com

**Comment by colegota** [comment]
You'll receive an email with an invitation there.

Thanks!

**Comment by diogogithub** [comment]
Well, since we already know that AndStatus is working fine and that this is most likely a GS issue or a simple misconfiguration, please move this to https://notabug.org/diogo/gnu-social/issues so that we don't pollute AndStatus's repository needlessly.

Enable GNU social's debug log with:
````php
$config['site']['logfile'] = 'errors.txt';
$config['site']['logdebug'] = true;
````

and post that and php's error_log in a new issue at GS's repo, together with the already provided information and the output of `git log -1`.

Thanks! :)

**Comment by colegota** [comment]
Followed here:
https://notabug.org/diogo/gnu-social/issues/123
