### ISSUE TITLE
Twitter Home timeline

### ISSUE THREAD

**Issue by arnauldb** [andstatus/andstatus#521]
Hello,
Could you tell me how to have my Twitter Home timeline? The names in andstatus are not the same.
Thank you.

**Comment by yvolk** [comment]
Hello,

1. I just did clean install of AndStatus, 
2. pressed "Get started" of the first screen, 
3. selected Twitter type of social network,
4. logged in on the Twitter's web page as "andstatus1",
5. authorized my app on a prompt,
5. and I was automatically forwarded to this Home page (see screenshot below).

At what step do you have a problem?

![Screenshot_1589616023](https://user-images.githubusercontent.com/207716/82114284-7ee9d980-9764-11ea-8811-817044ff4337.png)

**Comment by arnauldb** [comment]
I am french so my phone uses French language. On my timelines I have one called "Principale" (please see screenshot below), I suppose (but I am not sure) it is the "Accueil" (Home) timeline.
![Screenshot_20200516-103754_AndStatus](https://user-images.githubusercontent.com/13196747/82115318-979cc400-9751-11ea-9c65-23bc33ae500a.png)
So to check, I changed the settings in AndStatus to use English in the app. But the "principale" timeline didn't change and is still called "principale" (it should have switched to English I suppose).

Thank you.

**Comment by yvolk** [comment]
Looks like this is a bug: Names of timelines are always in Device default language, and not in the selected "App language".
I will fix this now and let you know!

**Comment by yvolk** [comment]
@arnauldb I made a fix plus updated translations, please test v.56.04 from here: https://github.com/andstatus/andstatus/issues/456

**Comment by arnauldb** [comment]
> I made a fix plus updated translations, please test v.56.04 from here: #456

Thank you. I installed through F-Droid so I prefer to wait for a F-Droid update rather than installing an .apk directly.
