### ISSUE TITLE
Support for Parler

### ISSUE THREAD

**Issue by michuvon** [andstatus/andstatus#522]
It seems that Parler might turn out to be a actual alternative to Twitter. Do you plan to add it at some point in the future?

**Comment by yvolk** [comment]
Hi @michuvon 
Current trend in "alternative"/ non-corporate social networks: implementation of ActivityPub Client to Server protocol thus allowing creation and usage of generic client apps. See https://github.com/andstatus/andstatus/issues/499 on that protocol's support in AndStatus.
Does Parler support or plan to support this protocol? 

If no, maybe it supports (is compatible with) any other social network's client-to-server protocol? Any links to its API?

**Comment by michuvon** [comment]
sorry I can't answer your question(s) at this point. For one because I lack the technical knowledge and second because I don't have time to go into it right now. If one day I research more about it I'll post it here. But it will be basic. I'm a user+ only, not a programmer.
I'm looking up to you guys and often only understand what you are talking about after hours of duckduckgo-ing the terms you use. lol

**Comment by boehs** [comment]
I think this can probably be closed
