### ISSUE TITLE
Impossible to add Twitter Account

### ISSUE THREAD

**Issue by steph-92** [andstatus/andstatus#526]
On AndStatus v 57.05, I can't add a Twitter Account, each time I end up on a Twitter page telling my browser is not compatible. Even though I have firefox and Chrome on my phone.
In the [issue 511](https://github.com/andstatus/andstatus/issues/511) it should be possible by using version 49, but I can(t find this version, I'm using F-droid.

**Comment by abrianceau** [comment]
Hi, I am new to Andstatus and I have the same issue.

**Comment by yvolk** [comment]
@steph-92 @abrianceau Thank you for noticing!
It appeared that Twitter doesn't like "AndStatus" user agent anymore. This is ID of the app's internal web browser that worked for more than 10 years...

Fixed in v.57.07. Just posted it to #456 and to app stores.
