### ISSUE TITLE
Using AndStatus as debug tool for local development

### ISSUE THREAD

**Issue by zgoda** [andstatus/andstatus#527]
Hi, I'm implementing parts of ActivityPub in my project and I'm trying to use AndStatus as debug tool, basically trying to connect, register and do some basic operations. Is it possible at all to run AndStatus against local server, running eg. on http://192.168.1.21:5500? Note I'd like to avoid setting up SSL on my dev server.

Now it fails at registering account, eg `user1@192.168.1.21:5500`.

**Comment by yvolk** [comment]
@zgoda No problem to turn SSL off (in Setting -> Accounts -> Manage Social networks -> you may add new Social network there with any parameters.
Not sure if setting custom port will work that way. 
Please let me know if that works for you (and look also at https://github.com/andstatus/andstatus/issues/525 where I made quick changes exactly to allow custom port... )
