### ISSUE TITLE
No client_id in the OAuth 2.0 "Access Token Request"

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#530]
As @rustra noticed in https://github.com/andstatus/andstatus/issues/528#issuecomment-824094928 :

> I'm implementing C2S for the general semantic ActivityPub server [CPub](https://github.com/openEngiadina/cpub/). Passing initial OAuth client registration flow I see that `POST /oauth/token` request misses the required `client_id` parameter according to [The OAuth 2.0 specification](https://tools.ietf.org/html/rfc6749#section-4.1.3). Could you please look at that in your spare time?

I checked the code and see that the "Access Token Request" is created inside ScribeJava https://github.com/scribejava/scribejava/blob/0142ceb93648047256d57e0056554f161816c97d/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth20Service.java#L189 com.github.scribejava.core.oauth.OAuth20Service#createAccessTokenRequest

The line adds required client_id parameter to the body, BUT only in a case non-default Client Authentication method is configured: https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth2/clientauthentication/RequestBodyAuthenticationScheme.java
``` 
api.getClientAuthentication().addClientAuthentication(request, getApiKey(), getApiSecret());
```

AndStatus has default HTTP Basic Authentication configured, see it https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth2/clientauthentication/HttpBasicAuthenticationScheme.java

The spec does allow two methods of Client Authentication (see section 2.3. https://tools.ietf.org/html/rfc6749#section-2.3 ), but section "4.1.3.  Access Token Request" requires client_id to be in the HTTP request entity-body only. This is why HttpBasicAuthenticationScheme produces invalid "Access Token Request".

Note: All servers, that I tested OAuth with, work with such an invalid request though  :-) 

Fixing this by configuring RequestBodyAuthenticationScheme in ScribeJava.

**Comment by rustra** [comment]
Thank you for such a quick reaction!

**Comment by yvolk** [comment]
@rustra Please see comment in the ScribeJava issues: https://github.com/scribejava/scribejava/issues/1005#issuecomment-824592413
Looks like this is not so simple...

**Comment by rustra** [comment]
@yvolk Not sure about all the details of OAuth implementation in ScribeJava. In my understanding the point is _dynamic_ client registration. More confidential clients could be pre-registered (like here in Github: https://github.com/settings/applications). However to identify dynamically registered client its `client_id` is the must. But maybe i'm missing the main point of the issue.

**Comment by yvolk** [comment]
Hi @rustra Re-reading answer from SribeJava issue 1005 (see above) I realize that I really need to revert my change, i.e. leave AndStatus behavior as is, because it is a preferred one.

Do you agree with that arguments and conclusions?

**Comment by rustra** [comment]
Maybe that's fine for general ScribeJava library and indeed HTTP Basic Authentication is a proper default option. But i believe it should be possible in AndStatus to use non-default Client Authentication method during dynamic OAuth client app registration which will allow to send `client_id`. What do you think?

**Comment by yvolk** [comment]
> However to identify dynamically registered client its client_id is the must. But maybe i'm missing the main point of the issue.

I also thought so, when I wrote my top message of this thread. But it appears that during "Access Token Request" a Client DOES send both client_id and client_secret, but not in the body, but in the header instead (using Basic Authentication). So there is no need to send the same client_id in the body also,

> But i believe it should be possible in AndStatus to use non-default Client Authentication method during dynamic OAuth client app registration which will allow to send client_id. What do you think?

The main problem here is that AndStatus, like any other OAuth2 Client app, connects to different hosts with different OAuth2 implementations. Not only to hosts, where Accounts are configured in the app, but to hosts of other federated instances, to which Activities and Actor profiles refer...

I mean it's impossible (impractical) to configure different Client Authentication methods per host. If we would have non-default Authentication method configured in AndStatus, we risk not to be able to connect using OAuth2 to a properly implemented Servers.

This means that for connection to all that unknown instances Client app should use methods that MUST be present in any OAuth2-compliant server. And "HTTP Basic Authentication" is that must have, as I understand. Meaning that if OAuth2 fails we can assume that this is a server that failed to implement OAuth2 properly, not the Client app.

Of course, you could say here: "I don't care about others, I want AndStatus to connect to MY server"...
Is this, what you really want?

**Comment by rustra** [comment]
Absolutely not, i want friendly federation! ;)
Ok, in case it's also possible to fetch `client_id` from headers that's not a problem at all to get it there. I will tweak CPub and come back with the results. Please revert your changes.

**Comment by yvolk** [comment]
@rustra Thank you for discussion and helping to come to the deliberate solution. Please come back in a case of any problem.

**Comment by rustra** [comment]
Just a short update that CPub needs only `code` and checks `redirect_uri`.

**Comment by yvolk** [comment]
I didn't get: if AndStatus works properly?

**Comment by rustra** [comment]
Yes, it does.
