### ISSUE TITLE
Send with ENTER doesn't work

### ISSUE THREAD

**Issue by muellerto** [andstatus/andstatus#533]
AndStatus v.58.02 (341), using a Twitter account

My AndStatus does not send when I tab on ENTER (option has been set). It just inserts a line break. I would like to use this feature because I find the send button on top not good at all and too small.

**Comment by yvolk** [comment]
@muellerto Thanks for noticing. Looks like this is a regression bug. Will fix it.

**Comment by yvolk** [comment]
@muellerto I guess you mean "soft" ENTER key, i.e. a key on a touchscreen keyboard.
I investigated the problem, and it looks like the "soft" ENTER key didn't work for a long time, at least since the time, when notes became multiline.

I'm thinking about proper implementation.
1. Should I make an editable text "single line", when "ENTER key sends a note" option is set.
2. Or maybe it could still be multiline, but at attempt to add a line break at the end of it should trigger sending a note instead of adding the new line
?!

**Comment by muellerto** [comment]
Am Wed, 02 Jun 2021 12:24:38 -0700
schrieb Yuri Volkov ***@***.***>:

> @muellerto I guess you mean "soft" ENTER key, i.e. a key on a
> touchscreen keyboard. I investigated the problem, and it looks like
> the "soft" ENTER key didn't work for a long time, at least since the
> time, when notes became multiline.

I can't confirm that. I use it just for a few weeks. In my case it
never worked.

> 1. Should I make an editable text "single line", when "ENTER key
> sends a note" option is set.

I think you must. Otherwise you must give the user an opportunity to
enter an intended line break somehow. This would require a new key or
button or something like that.

> 2. Or maybe it could still be multiline, but at attempt to add a
> line break at the end of it should trigger sending a note instead of
> adding the new line ?!

But you don't know what the user means when the user taps on the Enter
key. Even double Enters and many blank lines at the end must be allowed
in a multiline text. When the feature is called "ENTER key sends" then
you must send immediatly on the first Enter.

I guess not many people will use this "ENTER key sends". Most people
will use the Send button. I was searching for an alternative because
the Send button is so small, Two or three times a week I tap on the
paper clip instead. And another disadvantage is the long distance
between writing a message (the keyboard is at the bottom) and the Send
button on top.

In my case it would also be a very good solution to have the Send
button on the right end of the input line. See my attached "Design
Study" :) This is the case in many SMS and Messenger apps. On
Blackberry devices they had also a second button there (the paper
clip for attachments).

OK, when you have the Send button there this leads sometimes to
unintended sendings. But this is rare. The user learns that.

T.M.

**Comment by yvolk** [comment]
@muellerto Aha, so what you really need is having "Send" button near the text of a composed note :-)

As the "ENTER key sends a note" option doesn't work anyway, we could easily drop it
and implement "Show 'Send' button near the composed note" instead?!

Unfortunately your attachment with a proposed design obviously was dropped by GitHub, please attach it here directly.

**Comment by muellerto** [comment]
(Damned, I answered per mail on an email I got.)

>As the "ENTER key sends a note" option doesn't work anyway, we could easily drop it
>and implement "Show 'Send' button near the composed note" instead?!

Best idea. I would use it.

Perhaps, if you want an option for this, you could also make an option for the paper clip, I mean for both buttons. Then the user can decide completely which stuff he want's here or there.

You could even put the button(s) on the same line with the number of characters left and save some space. In this case I would place this line under the text.

My design study was this (don't ask about my tweets):
![AndStatus](https://user-images.githubusercontent.com/5188366/120598634-c5c97080-c446-11eb-9cf6-0fba9a787770.png)

**Comment by yvolk** [comment]
The "Paperclip" could be placed right under the "Send" button to leave more space for typing ?!

**Comment by muellerto** [comment]
When you place the button(s) and the characters-left-information all together on one line I would put this line under the text. If so the text itself could have the full with on each line. Just a suggestion.

(Probably a right-to-left writer would be more familiar with the buttons on the left side.)

![AndStatus](https://user-images.githubusercontent.com/5188366/120604410-5440f080-c44d-11eb-964a-2771255803b4.png)

**Comment by yvolk** [comment]
I released this in v.59.01, see #456 

![a00ec20cdd361de2](https://user-images.githubusercontent.com/207716/123686842-e83d8680-d858-11eb-8bc0-013adaeab137.png)
