### ISSUE TITLE
ActivityPub: support for Magnet URIs

### ISSUE THREAD

**Issue by rustra** [andstatus/andstatus#535]
That would be great if AndStatus could understand Magnet URIs which refer to content-addressable data.
The related discussion about the role of such URIs: [Content-addressing and URN resolution](https://socialhub.activitypub.rocks/t/content-addressing-and-urn-resolution/1674).

https://en.wikipedia.org/wiki/Magnet_URI_scheme

**Comment by rustra** [comment]
As an example:

`GET http://074661a15e2e.ngrok.io/users/bob/inbox`

```
{
  "@context": ["https://www.w3.org/ns/activitystreams#", "http://litepub.social/ns#"],
  "id": "http://074661a15e2e.ngrok.io/users/bob/inbox",
  "items": "magnet:?xs=http://074661a15e2e.ngrok.io/uri-res/N2R?urn:erisx2:AAADNWEJALNQLKXYIKCOA6X2HEXZOLT7YF7S5KYKXJIIQGPSWJKCWZTMQFEBEMHYRJXOTESONTM7NNJV4XO7WWBKVQRZ7SQRU7KDGLIZWA&xt=urn:erisx2:AAADNWEJALNQLKXYIKCOA6X2HEXZOLT7YF7S5KYKXJIIQGPSWJKCWZTMQFEBEMHYRJXOTESONTM7NNJV4XO7WWBKVQRZ7SQRU7KDGLIZWA",
  "ldp:member": {
    "id": "magnet:?xs=http://074661a15e2e.ngrok.io/uri-res/N2R?urn:erisx2:AAADNWEJALNQLKXYIKCOA6X2HEXZOLT7YF7S5KYKXJIIQGPSWJKCWZTMQFEBEMHYRJXOTESONTM7NNJV4XO7WWBKVQRZ7SQRU7KDGLIZWA&xt=urn:erisx2:AAADNWEJALNQLKXYIKCOA6X2HEXZOLT7YF7S5KYKXJIIQGPSWJKCWZTMQFEBEMHYRJXOTESONTM7NNJV4XO7WWBKVQRZ7SQRU7KDGLIZWA"
  },
  "type": ["ldp:BasicContainer", "Collection"]
}
```

**Comment by yvolk** [comment]
So we need to list "atomic" features that will constitute the "support for Magnet URIs":

- [ ] Parse "xs" parameter for URL of the Object.
- [ ] ...

**Comment by rustra** [comment]
[ ] Client should _know_ that any URI could be both URL and _URN_ and could _re-reference_ an URN;
[ ] Magnet URNs contain the `xs` parameter with an URL where associated content should be fetched by client;
 - a response with content type `application/activity+json` or `application/ld+json` should be considered as JSON-LD object;
 - (OPTIONAL) a response with content type `text/uri-list` should be considered as a list of URIs (see [RFC 2169, Appendix A](https://tools.ietf.org/html/rfc2169) for details);
[ ] (OPTIONAL) The `xt` parameter identifies the content unequivocally according to content-addressing principle and could be used as a _key_ for this content for caching;
[ ] (OPTIONAL) The rest possible Magnet URI parameters are optional (for now at least).

**Comment by yvolk** [comment]
@rustra I see that Decoding (and encoding) of Magnet URIs is not a trivial task.
There is a JavaScript implementation that uses some dependencies: https://github.com/webtorrent/magnet-uri
But we need something preferably in Kotlin.
 
In order to not reinvent the wheel we need to find existing library OR create a new public GIT repo for such a general feature, hoping to get support from other developers...
What do you think?

**Comment by rustra** [comment]
I agree with you that having a separate small library for that would be nice. It requires some effort however not so much. For example check implementation in Elixir: https://github.com/rustra/magnet/tree/fancy/lib.

Magnet URIs originally came from BitTorrent, so some code for their support could be found in appropriate BitTorrent-related repositories. This project in Java looks interesting: https://github.com/atomashpolskiy/bt.
Possibly it's outdated but here is some references as well: http://magnet-uri.sourceforge.net.

For the quick workaround support of `magnet:?xs=<URL>` is enough.

**Comment by yvolk** [comment]
@rustra Most of what you wrote is implemented except for "a response with content type text/uri-list should be considered as a list of alternative URIs for fetching the same content".
Please test v.59.00, available here: #456

**Comment by rustra** [comment]
@yvolk Thank you! I'll check it tomorrow. And no worries about `text/uri-list`, CPub does not use it yet.

**Comment by yvolk** [comment]
@rustra Does this work for you?
