### ISSUE TITLE
Mastodon: Transmit "client_id" and "client_secret" when requesting a token

### ISSUE THREAD

**Issue by annando** [andstatus/andstatus#537]
I'm currently implementing the Mastodon API at Friendica. At the moment I'm testing several apps against my current test installation.

AndStatus is failing at my tests since it doesn't provide `client_id` and `client_secret` when requesting a token via `/oauth/token`. According to the Mastodon documentation this data is required: https://docs.joinmastodon.org/methods/apps/oauth/#obtain-a-token

For this reason Friendica rejects the request. Providing at least the `client_id` is documented here as well: https://aaronparecki.com/oauth-2-simplified/ Since all other tested application do provide this data (and since the documentation states so as well), it would be great if AndStatus could provide this data as well.

**Comment by yvolk** [comment]
Hi @annando 
This issue is exactly about the same problem: https://github.com/andstatus/andstatus/issues/530

In short: current behavior is correct. client_id is in the header...

**Comment by annando** [comment]
Okay. I'm now fetching the data from there as well, this seems to work.
