### ISSUE TITLE
Mastodon: use regular post fields instead of a json string when creating an app

### ISSUE THREAD

**Issue by annando** [andstatus/andstatus#538]
When testing the Mastodon-style API in Friendica I also had problems with the way AndStatus is registering an application. According to the documentation the needed data has to be provided as regular post variables: https://docs.joinmastodon.org/methods/apps/

Instead AndStatus is transmitting them as a JSON encoded string in the post data:
```
{"client_name":"AndStatus","redirect_uris":"http:\/\/oauth-redirect.andstatus.org","scopes":"read write follow","website":"http:\/\/andstatus.org"}"}

All other tested applications provide this data as regular post variables.
```

**Comment by yvolk** [comment]
First of all, this works with Mastodon.
And second: client registration protocol is not invented by Mastodon, so Mastodon's documentation is not the Golden source here.
Anyway I will lookup more info on this...

**Comment by annando** [comment]
I tested several other mobile apps like Tusky, Husky, twitlatte, Twidere and Subway Tooter. They all behaved the other way. But I already coded a workaround for this.

**Comment by yvolk** [comment]
I see, were the Dynamic Registration comes from: "OAuth 2.0 Dynamic Client Registration Protocol", see https://datatracker.ietf.org/doc/html/rfc7591#section-2 
The section "2.  Client Metadata" says, in particular:
```
All data member types
   (strings, arrays, numbers) are defined in terms of their JSON
   [RFC7159] representations.
```

So it looks like sending Client metadata in JSON format is at least a correct one.

**Comment by annando** [comment]
Okay. Friendica does now accept both ways. The basic test with AndStatus did work. So I guess I can close this issue.
