### ISSUE TITLE
support for friendica

### ISSUE THREAD

**Issue by annando** [andstatus/andstatus#55]
Friendica is a social network software that is using an API that is compatible to status.net.

Trying to add an account doesn't work at the moment, there appears an error message that disappears too fast to recognize.

I'm contributing code to friendica. So I would love to make it work.

**Comment by yvolk** [comment]
Basic support is implemented.
Let's raise focused issues for individual enhancements of Friendica support, which are most important...

**Comment by morphtown** [comment]
Am 01.02.2015 um 09:19 schrieb Yuri Volkov:
>
> Basic support is implemented.
> Let's raise focused issues for individual enhancements of Friendica
> support, which are most important...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andstatus/andstatus/issues/55#issuecomment-72356101>.
>

Wow, will it work then with Red Matrix also? This would be awesome and
make AndStatus one killer application.

**Comment by yvolk** [comment]
@morphtown turn on all logs and test!  ☺

**Comment by morphtown** [comment]
Still unsure what account credentials are necessary. Just user/pw seems
not to work with the host defined as GNUsocial. I managed to connect to
the redmatrix with mustard though just read not post.

**Comment by yvolk** [comment]
@morphtown  Maybe Mustard allows "connection" without prior authentication as a user?! 
E.g. to read and search Public timeline?!
If account creation is a stumbling block,  AndStatus may be cheated :-)
1. Create new account in GNU social via web.
2.  Create new Microblogging system in AndStatus,  call it e.g. RedMatrix, but set URL as for that account in point 1.
3. Create an account in the "RedMatrix".
4. Go to Settings and change URL etc of RedMatrix to the real URL of Red Maxrix (whatever it is).
5. Switch to Public timeline and refresh, try Global search...

**Comment by morphtown** [comment]
@yvolk The cheat does not work. AndStatus then still tries to connect to
//redmatrix.tld/api/statusnet

**Comment by morphtown** [comment]
BTW ... how can I delete the borked test accounts? :D

**Comment by yvolk** [comment]
@morphtown It does work, but maybe api path inside typed URL is different?!
Anyway,  connecting another similar system is a piece of cake. 
We only need documentation or source code of working client. 

Remove account the same way you would remove Google account. Goto Android settings - Accounts and Sync - AndStatus - select account to remove - Remove account in the menu.

**Comment by morphtown** [comment]
@yvolk Ha, they're all there! Thanks for the pointer.
