### ISSUE TITLE
Homescreen widget doesn't appear to do anything

### ISSUE THREAD

**Issue by DetroitLibertyPenguin** [andstatus/andstatus#553]
I have used the app for about 2 weeks now and it always says nothing new
![Screenshot_20220317-232854_One UI Home](https://user-images.githubusercontent.com/65328167/158933741-0f7990be-0d3b-4a49-8d13-211b92c4232f.jpg)

**Comment by yvolk** [comment]
Hello @DetroitLibertyPenguin 
The AndStatus Widget shows Notifications that are configured in Settings -> Notifications.
As we can read in the http://andstatus.org/changelog.html 

> Notifications, shown in Android [Notification area](https://developer.android.com/guide/topics/ui/notifiers/notifications.html) and in the AndStatus Widget, are not forgotten anymore. These notifications are persisted even after device reboot.
> Notifications are reset when a User opens correspondent timeline e.g. by clicking on the Notification or a Widget. [#367](https://github.com/andstatus/andstatus/issues/367) and [#398](https://github.com/andstatus/andstatus/issues/398)

**Comment by DetroitLibertyPenguin** [comment]
Thaanks
