### ISSUE TITLE
Background sync on Android 12?

### ISSUE THREAD

**Issue by kr428** [andstatus/andstatus#557]
Using Andstatus 58.05 on an Android 12 Samsung device, I noticed that (even though having sync set to fetch updates every 10 minutes) the app only syncs when it's actually running. Is that intended / expected behaviour? Also tried to disable battery optimization but that doesn't seem to change much.
Thanks and best regards!

**Comment by yvolk** [comment]
I need to check if AndStatus has special means to make Android allow its background syncing...

Meanwhile you may try to create a widget, so Android would refresh it periodically. And syncing should be initiated during such refreshes...

**Comment by kr428** [comment]
Ok, thanks, will try whether that works for my purposes.

**Comment by yvolk** [comment]
Hi @kr428 ! Recently I updated AndStatus to use JobScheduler instead of running a "Service" directly, and now background sync works on Android 13 as I see. Please check v.59.10+ #456

**Comment by kr428** [comment]
> Hi @kr428 ! Recently I updated AndStatus to use JobScheduler instead of running a "Service" directly, and now background sync works on Android 13 as I see. Please check v.59.10+ #456

Neat, thanks. Does it need any additional settings to work though? Because it doesn't seem to show a different behaviour here...?

**Comment by yvolk** [comment]
No any additional settings. I checked logs on my Android 13 phone: AndStatus successfully synced a couple of times at night...
