### ISSUE TITLE
Diaspora: Many comments lost in thread those that are there are attributed to incorrect users

### ISSUE THREAD

**Issue by DetroitLibertyPenguin** [andstatus/andstatus#559]
The entire thread can be found at https://despora.de/posts/9c40df40ffdc013afbf1543d7eeced27 contained there in you will find the screen shot that shows what I saw on AndStatus. 

![image](https://user-images.githubusercontent.com/65328167/186918250-817c19b4-884d-4e26-a9d6-26263727284a.png)

On AndStatus all of the comments that where displayed showed as if they came for the OP, and even then many of the comments where not included. 
![image](https://user-images.githubusercontent.com/65328167/186916383-9a1e43d3-3b5e-4434-9697-923fdcc10b3e.png)

Same thread from my instance: https://libranet.de/display/9c40df40ffdc013afbf1543d7eeced27

![image](https://user-images.githubusercontent.com/65328167/186915974-a13cb4de-0082-4664-9dd8-45c46c8ed1af.png)

This is the first time I know for sure I have seen this failure, but do to the nature of the failure I may well have seen it many times and never realized it. 

Upon further investigation, what I saw on AndStatus showed three comments, in the thread, all three showed the avatar of the OP but the other two that she did not post did show they were replies to OP but didn't indicate from whom

**Comment by yvolk** [comment]
Hi @DetroitLibertyPenguin 
1. What AndStatus version do you use?
2. Your account at what host downloaded the Conversation that you show on your screenshot.
3. The whole conversation isn't loaded by default: you need to click "Sync with the Internet" button on the Action bar to try to load the whole conversation. Otherwise you see only those notes of the conversation that were downloaded via your automatically synched timelines.
4. Please try.

**Comment by DetroitLibertyPenguin** [comment]
Fu@libranet.de (Friendica connected as GNU Social)

AndStatus v59.05 from F-Droid.

Choosing SYNC WITH INTERNET does not fix error of showing wrong partcipants. Example of failure

**Comment by DetroitLibertyPenguin** [comment]
Fu@libranet.de (Friendica connected as GNU Social)

AndStatus v59.05 from F-Droid.

Choosing SYNC WITH INTERNET does not fix error of showing wrong partcipants. Example of failure  

AndStatus 
https://libranet.de/photo/21012944706348d79d0c71f383492880-0.jpg

Original
https://libranet.de/photo/28938746146348d7fde821e793599282-0.jpg

Seen on the instance I'm on
https://libranet.de/photo/14038124746348d807cef35108564955-0.jpg


I'm not sure if it's relevant but both this thread, as well as the one in my first set of screenshots, the OP is on a Diospara instance that I'm viewing from Friendica.

**Comment by yvolk** [comment]
Hi @DetroitLibertyPenguin 
The original thread / screensots are from "Diaspora" type of social network.
Further you mention Friendica - another type (or close one...), connected via GNU Social API.
Quality and correctness of that systems' access via GNU Social client to server API is unknown. Moreover, it is known that GNU Social client API as a Twitter-like API uses server's local IDs for users/authors and for their posts. 
In case of several interacting servers this can easily lead to IDs clashes, and your case may be expected.

May be interesting for you this quite old but still actual discussion on centralized Twitter/GNU Social API vs a federated one. See around this comment: https://github.com/andstatus/andstatus/issues/419#issuecomment-254060882

Regarding integration with #Diaspora please see #391. We are waiting for news from Diaspora developers for a long time... Hope ActivityPub C2S API will allow us to communicate, at last...

**Comment by yvolk** [comment]
I noticed similar problem in one of Friendica servers after its migration from one version to another... 
https://github.com/andstatus/andstatus/issues/569#issuecomment-1382673389
The problem was caused by changed IDs at server side. The only thing you can do: create NEW Social Network for the same server and add your account to that new social network.
