### ISSUE TITLE
Support for loading objects via the Location header when creating an object via C2S

### ISSUE THREAD

**Issue by tsileo** [andstatus/andstatus#563]
When `POST`ing an object to the outbox, the AP C2S [spec](https://www.w3.org/TR/activitypub/#client-to-server-interactions) only requires a `Location` header with the AP ID of the newly created object.

From @yvolk 

> Regarding rationale of getting more than Activity id only from server:
1.1. During Create Activity at least TWO objects created: an Activity and a Note. So we need id of the Note anyway.
1.2. Knowing object's "published" and "updated" timestamps are important in knowing, when we need to update an object in the local cache (this is how AndStatus works...)

The response will contain the AP ID of the activity, if the response body is empty, the created object should be fetched/dereferenced.

It seems most software returns the created object (and so does microblog.pub), so I don't think this is urgent. It is mostly a matter of compatibility with the spec.

Thanks!

**Comment by yvolk** [comment]
Hi @tsileo I implemented this in v.59.14, please check #456
It would be good if you could provide me with some test account (test blog by @JD557 doesn't work now)

**Comment by JD557** [comment]
FYI, just enabled the test blog again.

(I'll eventually have to shut it down, as my server is really starving for resources, but I'll try to keep it online for a while)

**Comment by yvolk** [comment]
Regarding testing, it would be good to have full-feature test account, of course. With ability to see other Actor's activities, following other Actors, etc...

**Comment by yvolk** [comment]
Closing as I cannot check if this works.
