### ISSUE TITLE
ActivityPub: wrong object type in a Follow activity is sent via C2S

### ISSUE THREAD

**Issue by tsileo** [andstatus/andstatus#564]
I noticed the following activity was sent via C2S when trying to follow an actor:

```
{
  '@context': 'https://www.w3.org/ns/activitystreams',
  'type': 'Follow',
  'to': ['https://www.w3.org/ns/activitystreams#Public'],
  'actor': 'https://redacted',
  'object': {
    'id': 'https://mastodon.social/users/warandpeas',
    'type': 'Note',
    'to': ['https://www.w3.org/ns/activitystreams#Public']
  }
}
```

I think the object should just be `https://mastodon.social/users/warandpeas`/the AP ID.

Most software will send `"object": "https://mastodon.social/users/warandpeas"` directly.

I also think the `to` property could be skipped.

At least for microblog.pub, the C2S API parse the fields and will rebuild the message using the same helpers as the UI, so by getting the ID of the object, it still return the correct AP object.

Thanks! And let me know if you need more details!

**Comment by yvolk** [comment]
Hi @tsileo, as I understand reading the spec, this example is valid and an existing object inside an Activity may be referenced in two ways: either by its id only or the object with its properties may be included in the Activity, see examples below.
Server should support both variants, I think.

So this ticket is about possible optimization, about shortening of the Activity payload.

The specification has examples for both cases for Like Activity:
1. Object with its properties included, https://www.w3.org/TR/activitypub/#obj
```
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Like",
  "actor": "https://example.net/~mallory",
  "to": ["https://hatchat.example/sarah/",
         "https://example.com/peeps/john/"],
  "object": {
    "@context": {"@language": "en"},
    "id": "https://example.org/~alice/note/23",
    "type": "Note",
    "attributedTo": "https://example.org/~alice",
    "content": "I'm a goat"
  }
}
```
2. Only object id is present, https://www.w3.org/TR/activitystreams-core/#activities
```
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "summary": "Joe liked a note",
  "type": "Like",
  "id": "http://www.test.example/activity/1",
  "actor": "http://example.org/profiles/joe",
  "object": "http://example.com/notes/1",
  "published": "2014-09-30T12:34:56Z"
}
```

**Comment by yvolk** [comment]
Regarding "to" property of the Activity:
I think it really matters. For example:
1. Addressing the "Follow" activity to Public ( 'https://www.w3.org/ns/activitystreams#Public' ) make the Activity visible to all visitors... 
2. Addressing to Followers should cause sending the Activity to the Actor's followers.

**Comment by yvolk** [comment]
Oh, I didn't notice that the object type is wrong. That is clearly a bug, will try to fix.

I just thought, why would the object's properties may be interesting... and it came to me that they really could help: e.g. in a case the target object is on a server that is not accessible right now (for any reason...) and so the Actor's server, to which the Activity is sent, cannot "dereference" the object id right now...
