### ISSUE TITLE
Confusing Timeline title and Actor's icon

### ISSUE THREAD

**Issue by DetroitLibertyPenguin** [andstatus/andstatus#566]
PROCEDURE: Launch app

By default it loads and shows the avatar from my Mastodon account Fu@hostux.social, shows title as HOME yatfirefaithfellowship@datamost.com (a pump.io account) and the timeline actually displayed is of my other pump.io account jimfulner@identi.ca 

R; Get Actor information "FOLLOWERS.of.jxself.11804"

R; Get Actor information , foreground "FOLLOWERS.of.jxself.11804",
Created 45 minutes ago,
executed: 3, last: two minutes ago, retriesLeft: 7, error: Soft
Get Actor information "FOLLOWERS.of.jxself.11804",
Status code: OK; soft; Unexpected exception
Caused by java.lang.Exception: Actor is empty, getActor;; username='FOLLOWERS.of.jxself.11804'
,
CommandData: {command: get-user, id: 1671996997859, foreground, account: jimfulner@identi.ca/Pump.io, username: FOLLOWERS.of.jxself.11804, Timeline: {Pump.io, User{id=11093; knownAs=FOLLOWERS.of.jxself.11804@datamost.com}, type: sent_at_origin, actorActor: {origin:Pump.io, id: 11806, oid: https://datamost.com/api/user/jxself/followers, username: FOLLOWERS.of.jxself.11804, realName: FOLLOWERS.of.jxself.11804, groupType: FOLLOWERS, User{id=11093; knownAs=FOLLOWERS.of.jxself.11804@datamost.com}, avatarFile: AvatarFile11806: id:11806 IMAGE, MediaMetadata: {}, DownloadFile filename:, parentId: 11804}}, created:43 minutes ago, CommandResult: {executed: 2, last: 23 minutes ago, retriesLeft: 8, error: Soft
Actor is empty, getActor;; username='FOLLOWERS.of.jxself.11804',
CommandData: {command: get-user, id: 1671996997859, foreground, account: jimfulner@identi.ca/Pump.io, username: FOLLOWERS.of.jxself.11804, Timeline: {Pump.io, User{id=11093; knownAs=FOLLOWERS.of.jxself.11804@datamost.com}, type: sent_at_origin, actorActor: {origin:Pump.io, id: 11806, oid: https://datamost.com/api/user/jxself/followers, username: FOLLOWERS.of.jxself.11804, realName: FOLLOWERS.of.jxself.11804, groupType: FOLLOWERS, User{id=11093; knownAs=FOLLOWERS.of.jxself.11804@datamost.com}, avatarFile: AvatarFile11806: id:11806 IMAGE, MediaMetadata: {}, DownloadFile filename:, parentId: 11804}}, created:43 minutes ago, CommandResult: {executed: 2, last: 23 minutes ago, retriesLeft: 8, error: Soft}}}}![Screenshot_20221225-142505_AndStatus.png](https://user-images.githubusercontent.com/65328167/209481253-8b0b1b59-6951-44d5-a41e-f34bdfe82bab.png)![Screenshot_20221225-142539_AndStatus.png](https://user-images.githubusercontent.com/65328167/209481257-f25d3c6f-5512-44e3-9656-3a98b83744b3.png)

**Comment by yvolk** [comment]
Hi @DetroitLibertyPenguin, thank you for paying attention to this confusion.
First of all: "Unexpected exception... Actor is empty" is not related to this: that is incomplete implementation of Groups/Lists in AndStatus. I'm fixing that separately...

Regarding the confusion about what you see on the screen. I didn't remember details, so also made some checks after addition of several accounts from different types of Social networks...

So, what we have now on the application start:
1. Default timeline opens. The timeline is configured via the "Manage timelines" menu item.
2. Default Account is selected. This is the topmost account in the "Settings -> Accounts -> Manage Accounts" screen. You may reorder accounts on that screen by dragging them... 
Default Account is not related to the Default timeline. It can even be from the other Social network type (i.e. useless in the context of current timeline)
Icon of this selected account is shown in the left top corner of the screen.

Above doesn't explain discrepancy between the timeline title and its actual contents though. I couldn't reproduce this.

**Comment by DetroitLibertyPenguin** [comment]
Okay. Is there anything I can do to get you more data?

**Comment by yvolk** [comment]
@DetroitLibertyPenguin  1. The only unexplained thig for me: if the bug really exists: " discrepancy between the timeline title and its actual contents". Please try to reproduce it and make sure that it really exists. Or confirm that not.

2. We need to think about fixing the "known" confusion.
2.1. On app start current account should be the one that belongs to current timeline.
2.2. ...

**Comment by yvolk** [comment]
@DetroitLibertyPenguin Please check the latest v.60.01 with fixes https://github.com/andstatus/andstatus/issues/456
