### ISSUE TITLE
Show Follow status for profiles?

### ISSUE THREAD

**Issue by kr428** [andstatus/andstatus#567]
At the moment, I can follow accounts from within Andstatus. Would it be possible to also add an information on users profile page whether I'm already following this account (and maybe best also whether this account is a follower too)?

**Comment by yvolk** [comment]
When you see an Activity (a Note) of an Actor (User...) in a timeline, please select "Notes by <this actor>" in the Note's Activity's context menu.
The "Notes by <that Actor>" screen opens, and it has (at least should have) information on the Actor's profile, and if they follow you or your Actor follows them... You can retrieve a list of Friends and Followers of that Actor from the Actor's context menu (tap on the Actor's avatar)...

**Comment by kr428** [comment]
Hmmm, where do I see that in this particular view? Maybe I'm missing the obvious here....?

**Comment by yvolk** [comment]
This is an example of the "Notes by \<Some Actor>" screen and in this case we see "Follows andstatus@identi.ca" on it.
By we see this only in a case #AndStatus already knows that the Actor if following us:
either by explicitly requesting our Actor's Follower (in this profile's context menu) or by receiving a notification that the Actor followed us... 
I see that getting lists of Followers or Friends aren't quick enough, working on this now...
![image](https://user-images.githubusercontent.com/207716/209718689-7003d45a-c394-4f18-a4a9-8e81adf75204.png)
