### ISSUE TITLE
Twitter list support

### ISSUE THREAD

**Issue by agn-gpl** [andstatus/andstatus#570]
Currently, AndStatus does not support twitter list timeline. Hope that we can view the timelines of twitter lists which we subscribed.

**Comment by yvolk** [comment]
Hello @agn-gpl 
Some time ago I started, but still didn't finish Mastodon's lists support. As that implementation is quite generic and will potentially fit into different Social networks somehow, I think yo saw some part of it, see https://github.com/andstatus/andstatus/issues/542
