### ISSUE TITLE
No tweets displayed.

### ISSUE THREAD

**Issue by DocSniper** [andstatus/andstatus#579]
No tweets are displayed since a week.
Here is an excerpt from the log:
[andstatuslog.txt](https://github.com/andstatus/andstatus/files/12073423/andstatuslog.txt)

**Comment by yvolk** [comment]
Hi @DocSniper 
1. Please try to log out and then log into Twitter in AndStatus.
2. In a case the problem is still present, please turn on "Log network level messages to files". This will allow to read the error message completely. Currently in your log file I see only "You currently…"

This could be end of support for the free Twitter API (v.1.1) that AndStatus is using. 
E.g. I see something about this here: https://twittercommunity.com/t/what-is-the-deadline-for-twitter-api-v1-1-deprecation/189788/17

**Comment by DocSniper** [comment]
This could be the cause of the problem:
https://twittercommunity.com/t/what-is-the-deadline-for-twitter-api-v1-1-deprecation/189788/17
... and maybe unfortunately also the end of third-party clients. 🙁

**Comment by DocSniper** [comment]
Other clients have this problem too:
![TwidereX](https://github.com/andstatus/andstatus/assets/3104188/056d1fec-d231-40e1-bd49-aeabf7935b2d)

**Comment by obigroup** [comment]
> No tweets are displayed since a week. Here is an excerpt from the log: [andstatuslog.txt](https://github.com/andstatus/andstatus/files/12073423/andstatuslog.txt)

Hello,

I got the same error. Since 15 days, I can't sync my tweets.

I tried to log more but I didn't found the log file.

Here the simple error log : 

```
FORBIDDEN; hard; URL: https://api.twitter.com/1.1/statuses/hometimeline.json?tweetmode=extended&count=20&userid=USERID;
Caused by Status code: FORBIDDEN; hard; Error='?'; ; statusLine:'HTTP/1.1 403 Forbidden'; statusCode:FORBIDDEN (403); url:'https://api.twitter.com/1.1/statuses/hometimeline.json?tweetmode=extended&count=20&userid=USERID'; response:'{"errors":[{"message":"You currently…'
Requested: uri: 'https://api.twitter.com/1.1/statuses/hometimeline.json?tweetmode=extended&count=20&userid=UDERID', (no params), authenticate
```

I replaced my user id by USERID.
I also tried to log out and log in. And also delete my account and add it again.

Thx.

**Comment by yvolk** [comment]
I visited the "Getting Started with the Twitter API" page https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api and as I understand it there is NO free access to reading tweets anymore. See the screenshot taken today.
![2023-07-29-Getting-started-with-the-Twitter-API](https://github.com/andstatus/andstatus/assets/207716/3773c664-fb81-427a-bc7d-68ce35e7b654)
