### ISSUE TITLE
Change Password?

### ISSUE THREAD

**Issue by DetroitLibertyPenguin** [andstatus/andstatus#584]
I changed the password on my GNUsocial account and there doesn't seem to be a way to change login credentials without removing the account and then adding the same account. 

As a user I am worried about losing all my data if I do that.

**Comment by yvolk** [comment]
Hello @DetroitLibertyPenguin 
Since some time ago AndStatus account management screen has "LOG OUT" button at the bottom of the screen.
Please use it to have a chance to retype your credentials.
