### ISSUE TITLE
Failed to add account with "dn42" TLD

### ISSUE THREAD

**Issue by marek22k** [andstatus/andstatus#586]
Hello,

when I set up an ActivityPub account `marek22k@social.dn42`, "Invalid value: Username" appears. However, when I use an ICANN TLD, a different message appears and the AndStatus tries to contact the server. I can resolve social.dn42 on my mobile device and use the instance on the web browser, but I can't seem to set it up in AndStatus.

**Comment by yvolk** [comment]
@marek22k In order to make a good fix, we need to understand the whole flow.
As I cannot check this, you could fix that regexp, create your own AndStatus build and test further?!

**Comment by yvolk** [comment]
@marek22k The question is not only about the regex changing.
Your goal is to have successful connection to the ActivityPub server, and **that** may need additional changes (maybe at both sides. I mean, changes in AndStatus AND in the server). See, for example this discussion: https://github.com/andstatus/andstatus/issues/585

**Comment by yvolk** [comment]
I found the related discussion: https://stackoverflow.com/questions/9071279/number-in-the-top-level-domain
and I think this conclusion (backed by a long list of RFCs) is good for us:

Q: Does top-level domain can contain a number at the end?

A: Yes technically, except if it is purely numerical, then it can not be a TLD, under current rules and for easy reasons to understand (to disambiguate with IP addresses). And it can not contain a number at the end, except if it is an IDN TLD, for reasons enforced by ICANN.

**Comment by yvolk** [comment]
Hi @marek22k I made the fix and posted updated v.61.01 to #456
