### ISSUE TITLE
Mastodon: Change the default number of letters in a message

### ISSUE THREAD

**Issue by pygopero** [andstatus/andstatus#600]
By default, a message cannot be longer than 500 characters, but the instance where I have my account allows messages up to 2000.
Is there a way to change that figure in Andstatus? Right now Andstatus doesn't allow messages longer than 500

**Comment by yvolk** [comment]
Hello @pygopero !
What's that instance? What is its "Social network type" and its version?

**Comment by pygopero** [comment]
Hi!
Thanks for asking. The servers is masto.es, of course is a mastodon server. And version is 4.3.1
By the way, with the beta version of Andstatus,  I am able to sign in this server, with the previous version it was impossible.
Thanks again.

**Comment by yvolk** [comment]
Thank you for the details,
For a long time Mastodon didn't have config option allowing a Client app to know the text limit, I see my notes in AndStatus about this https://github.com/andstatus/andstatus/blob/master/app/src/main/kotlin/org/andstatus/app/net/social/ConnectionMastodon.kt#L531

Looking at this now I see that Gargron added such config in https://github.com/mastodon/mastodon/pull/16485, so I will add this to AndStatus also.

**Comment by yvolk** [comment]
@pygopero Please try v.62.02 at #456 
Now AndStatus rereads Maximum number of characters from the server on every account verification. Go to Account -> "Reverify credentials" button.

**Comment by pygopero** [comment]
I will test it right now!

**Comment by pygopero** [comment]
It works!
With a little trick: The number of characters available in a reply is 2000 minus the length of the account I am answering to.
Is that correct?

**Comment by yvolk** [comment]
I' m not sure about details, but think yes, I didn't correct that "2000" from your server.

**Comment by pygopero** [comment]
I've checked and that is the usual, so everithing is ok.
