### ISSUE TITLE
Indicator when AndStatus is syncing

### ISSUE THREAD

**Issue by annando** [andstatus/andstatus#63]
To see if AndStatus is currently working, it would be nice if AndStatus would show an Indicator in the notifications. (Like K9 is doing while syncing mails)

**Comment by yvolk** [comment]
Now syncing indicator is at a bottom of the screen and it is above a timeline, overlapping it, not shifting, as before.
![scr-syncing-indicator-at-the-bottom](https://cloud.githubusercontent.com/assets/207716/6097310/6453d4ea-afca-11e4-8eef-168b8558ab6e.png)
