### ISSUE TITLE
Jump to the newest message

### ISSUE THREAD

**Issue by annando** [andstatus/andstatus#68]
I guess I mentioned it before in some other issue.

I'm getting many, many messages since friendica is combining twitter, diaspora, facebook, pump.io, rss feeds and its own network in one stream. When I haven't used my mobile device for several days I have to scroll up several minutes to be at the current messages. I can't even move by touching the scroll bar, since it is extremely little in that situation.

So it would be great to be able to jump to the newest messages by touching an icon or a menu entry.

**Comment by yvolk** [comment]
We're getting rid of this "Fast Scroll thumb", see #255
