### ISSUE TITLE
Manual should be more comprehensive

### ISSUE THREAD

**Issue by dalb8** [andstatus/andstatus#78]
It's great that Andstatus covers many different systems. One cannot yet make new accounts but for sure, it will be many people's introduction to pump.io and gnu social. But having one interface for all these can obscure the differences. So I'd propose a larger manual. Following Android design guidelines, it should be accessible throughout the app, only covering material relevant to the current activity. It should be readily translatable too. I don't have a suggestion for how to achieve this; there's already a wiki, but it's not mobile-friendly and it has no translation interface. Perhaps there are already guides that can be pressed into action?

**Comment by yvolk** [comment]
This is mostly done,  see #229
