### ISSUE TITLE
 Discovery of Open GNU Social instances

### ISSUE THREAD

**Issue by pztrn** [andstatus/andstatus#84]
Right now I have to go to settings and add instance by hand. Why do not request instance URL while adding account rather then current "Add another system" thing? Because right now you're propagate Quitter, and user have no choice between instances.

There is another idea, if you do not want to change current behaviour: why not to use gstools.org for fetching open instances list, so user will have a choice?

**Comment by yvolk** [comment]
@pztrn I see the time came for me to implement this discovery request into AndStatus. 
From the first look everything looks good.  The questions are: 
1. How do this list is composed? I mean, how your system discovers that "Open instances", what is a "golden source" of this information?
2. How often is the list updated? 
3. And the most interesting for me: Do really so few open instances exist?

**Comment by pztrn** [comment]
1. This list is composed on voluteer basis, plugin not yet merged with gnusocial mainline. So if instance admin wants to be listed in this list - he must install a plugin and add his instance to database.
2. Right now updater performs its actions once per hour, and I see no intentions to change it.
3. Apparently there are more of them, but there is no single directory of them :smile: Possibly in future GSTools will be that directory, but not now.

**Comment by yvolk** [comment]
Got it, thank you. 
So I can join my list of AndStatus preconfigured servers with this one and present it to a User for selection. Maybe this use case will stimulate others to join this list/install the plugin...
Starting implementation...

**Comment by pztrn** [comment]
Great news! Thanks!

**Comment by yvolk** [comment]
@pztrn I see a line line this: "'instance_address': 'http://quitter.es', 'ssl_enabled': 1"
- "http" in URL and SSL is enabled 8-o
Q1. Is this a data error (conflicting values)
Q2. Why at all we may need 'ssl_enabled' if 'instance_address' already has this information?

**Comment by pztrn** [comment]
Oh, unintended bug :)

1. No data error.
2. 'ssl_enabled' can be used for sorting, e.g. when user wants to see only ssl enabled instances.

BTW, thanks for asking, I see a little bug here - on ssl enabled instance URL is still in HTTP. Will fix it tomorrow.

**Comment by yvolk** [comment]
The Discovery of Open GNU Social instances implemented.
Works like a charm :-)
Now we need to more Open instances to be registered in this service...

The screenshot below shows only instances, which were not imported into AndStatus on this particular device yet. Names are automatically modified to fit into AndStatus.
![scr-discover-open-instances](https://cloud.githubusercontent.com/assets/207716/6092841/07d1dad2-af02-11e4-804f-4580bac7f741.png)

**Comment by yvolk** [comment]
This works
